/**
 * Emoji as pictures for the 看图题 and word categories for 分类 (no image
 * assets). Only words with one clear, unambiguous picture are listed, and only
 * emoji up to Emoji 12 (they show on older Android tablets and Windows too).
 */

/** 英语 words (as spelled in the EN banks) → their picture. */
export const EN_EMOJI: Record<string, string> = {
  // en-g2a
  see: '👀',
  hear: '👂',
  smell: '👃',
  taste: '👅',
  cat: '🐱',
  hat: '🎩',
  bat: '🦇',
  map: '🗺️',
  tap: '🚰',
  nap: '😴',
  man: '👨',
  pan: '🍳',
  van: '🚐',
  'toy plane': '✈️',
  'toy bear': '🧸',
  ball: '⚽',
  robot: '🤖',
  'jigsaw puzzle': '🧩',
  bed: '🛏️',
  red: '🟥',
  cinema: '🎬',
  park: '🏞️',
  hen: '🐔',
  pen: '🖊️',
  ten: '🔟',
  cow: '🐄',
  sheep: '🐑',
  duck: '🦆',
  chick: '🐤',
  pig: '🐷',
  pin: '🧷',
  bin: '🗑️',
  ship: '🚢',
  lip: '👄',
  mooncake: '🥮',
  lantern: '🏮',
  moon: '🌕',
  // en-g4a
  city: '🏙️',
  building: '🏢',
  house: '🏠',
  eagle: '🦅',
  owl: '🦉',
  honeybee: '🐝',
  panda: '🐼',
  tree: '🌳',
  fish: '🐟',
  hill: '⛰️',
  plus: '➕',
  minus: '➖',
  apple: '🍎',
  banana: '🍌',
  pear: '🍐',
  supermarket: '🛒',
  money: '💰',
  spring: '🌸',
  summer: '🏖️',
  autumn: '🍂',
  winter: '⛄',
  hot: '🥵',
  cold: '🥶',
  snow: '🌨️',
  rain: '🌧️',
  sunflower: '🌻',
  leaf: '🍃',
  plant: '🌱',
  road: '🛣️',
  run: '🏃',
  look: '👀',
  left: '⬅️',
  right: '➡️',
  grandpa: '👴',
  grandma: '👵',
  'go shopping': '🛍️',
  'go for a walk': '🚶',
  'use the internet': '💻',
  'do housework': '🧹',
};

/** Words a picture could be taken for: never together in one 看图题. */
export const EN_SIMILAR: string[][] = [
  ['chick', 'chicken', 'hen'],
  ['house', 'home', 'flat', 'building'],
  ['city', 'building', 'street'],
  ['see', 'look'],
  ['summer', 'hot', 'warm'],
  ['winter', 'cold', 'snow', 'cool'],
  ['spring', 'flower', 'warm'],
  ['autumn', 'leaf', 'cool'],
  ['flower', 'sunflower', 'plant', 'grow'],
  ['leaf', 'plant', 'tree'],
  ['hill', 'country', 'park'],
  ['moon', 'mooncake', 'look at the moon', 'Mid-Autumn Festival'],
  ['lantern', 'play with lanterns'],
  ['supermarket', 'shop', 'go shopping', 'money', 'yuan', 'how much'],
  ['grandpa', 'grandma', 'grandparents', 'old', 'man'],
  ['nap', 'bed'],
  ['toy bear', 'toy', 'doll'],
  ['ball', 'toy'],
  ['fish', 'fin'],
  ['cinema', 'toy shop'],
  ['road', 'street', 'cross'],
  ['run', 'go for a walk'],
  ['red', 'red light'],
  ['plus', 'minus', 'equal', 'answer', 'number'],
];

/** 英语 words → category (the buckets of 英语 分类). */
export const EN_CATEGORY: Record<string, string> = {
  ...Object.fromEntries(
    ['cat', 'bat', 'hen', 'cow', 'sheep', 'duck', 'chick', 'chicken', 'pig', 'eagle', 'owl', 'honeybee', 'panda', 'fish'].map((w) => [w, '🐾 动物']),
  ),
  ...Object.fromEntries(['see', 'hear', 'smell', 'taste', 'feel'].map((w) => [w, '👀 感官'])),
  ...Object.fromEntries(['uncle', 'aunt', 'cousin', 'man', 'grandpa', 'grandma', 'grandparents'].map((w) => [w, '🧑 人物'])),
  ...Object.fromEntries(['old', 'young', 'cute'].map((w) => [w, '✨ 样子'])),
  ...Object.fromEntries(['doll', 'toy plane', 'toy bear', 'ball', 'robot', 'jigsaw puzzle'].map((w) => [w, '🧸 玩具'])),
  ...Object.fromEntries(['pet shop', 'fruit shop', 'toy shop', 'cinema', 'zoo', 'park'].map((w) => [w, '📍 地方'])),
  ...Object.fromEntries(['play with lanterns', 'eat mooncakes', 'solve riddles', 'look at the moon'].map((w) => [w, '🎉 中秋活动'])),
  ...Object.fromEntries(['mooncake', 'lantern', 'moon', 'riddle'].map((w) => [w, '🏮 中秋的东西'])),
  ...Object.fromEntries(['in', 'on', 'under'].map((w) => [w, '📦 方位'])),
  ...Object.fromEntries(['apple', 'banana', 'pear'].map((w) => [w, '🍎 水果'])),
  ...Object.fromEntries(
    ['odd numbers', 'even numbers', 'plus', 'minus', 'equal', 'answer', 'number', 'twenty'].map((w) => [w, '🔢 数学']),
  ),
  ...Object.fromEntries(['spring', 'summer', 'autumn', 'winter'].map((w) => [w, '🗓️ 季节'])),
  ...Object.fromEntries(['warm', 'hot', 'cool', 'cold', 'snow', 'rain'].map((w) => [w, '🌡️ 天气'])),
  ...Object.fromEntries(['wait', 'cross', 'look', 'run'].map((w) => [w, '🏃 动作'])),
  ...Object.fromEntries(['left', 'right'].map((w) => [w, '↔️ 方向'])),
  ...Object.fromEntries(
    ['go shopping', 'go for a walk', 'use the internet', 'do exercise', 'do housework', 'do gardening'].map((w) => [w, '🎈 活动']),
  ),
};

/** 语文 dictation words (词语听写表) → their picture. */
export const YW_EMOJI: Record<string, string> = {
  // yw-g2a
  太阳: '☀️',
  花朵: '🌸',
  冬天: '⛄',
  海洋: '🌊',
  飞鸟: '🐦',
  铜号: '🎺',
  树叶: '🍃',
  世界: '🌍',
  云彩: '☁️',
  拍手: '👏',
  星星: '⭐',
  奶奶: '👵',
  爷爷: '👴',
  勺子: '🥄',
  小岛: '🏝️',
  水果: '🍇🍎🍌',
  黄狗: '🐕',
  灯光: '💡',
  城市: '🏙️',
  叶子: '🍃',
  虫子: '🐛',
  孤舟: '🛶',
  唱歌: '🎤',
  散步: '🚶',
  白云: '☁️',
  着火: '🔥',
  树林: '🌳🌳🌳',
  船只: '🚢',
  椅子: '🪑',
  眼泪: '😢',
  水花: '💦',
  青草: '🌿',
  太极: '☯️',
  // yw-g4a
  香蕉: '🍌',
  蚊子: '🦟',
  蝙蝠: '🦇',
  帽子: '👒',
  嘴巴: '👄',
  山峰: '🏔️',
  斧头: '🪓',
  玫瑰: '🌹',
  锁链: '⛓️',
  麻雀: '🐦',
  猴子: '🐒',
  狮子: '🦁',
  拳头: '✊',
  胳膊: '💪',
  酒瓶: '🍾',
  辣椒: '🌶️',
  红薯: '🍠',
  连衣裙: '👗',
  葡萄: '🍇',
};

/** Things to count in 数学 pictures, with their name and 量词. */
export const COUNTABLES: Array<{ e: string; name: string; unit: string }> = [
  { e: '🍎', name: '苹果', unit: '个' },
  { e: '🍓', name: '草莓', unit: '个' },
  { e: '🍊', name: '橘子', unit: '个' },
  { e: '🍑', name: '桃子', unit: '个' },
  { e: '🥕', name: '胡萝卜', unit: '根' },
  { e: '⭐', name: '星星', unit: '颗' },
  { e: '🌸', name: '花', unit: '朵' },
  { e: '🐟', name: '鱼', unit: '条' },
  { e: '🎈', name: '气球', unit: '个' },
  { e: '🍬', name: '糖', unit: '颗' },
  { e: '🍪', name: '饼干', unit: '块' },
  { e: '🐤', name: '小鸡', unit: '只' },
];
