import type { EnglishBank } from './types';

/** 英语 四年级上册（沪教牛津版 深圳用）Unit 1–2。kp = 知识点 id 去掉 "en-g4a."；zh 在本册内不重复。 */
export const EN_G4A: EnglishBank = {
  words: [
    // ---------------------------------------------------------------- Unit 1
    { kp: 'u1.words', level: 1, en: 'meet', zh: '遇见', misspell: ['meit', 'meeet', 'mtee'] },
    { kp: 'u1.words', level: 1, en: 'new', zh: '新的', misspell: ['nwe', 'niw', 'neu'] },
    { kp: 'u1.words', level: 1, en: 'classmate', zh: '同学', misspell: ['classmat', 'clasmate', 'classmete'] },
    { kp: 'u1.words', level: 1, en: 'boy', zh: '男孩' },
    { kp: 'u1.words', level: 1, en: 'girl', zh: '女孩', misspell: ['gril', 'gerl', 'gilr'] },
    { kp: 'u1.words', level: 1, en: 'he', zh: '他' },
    { kp: 'u1.words', level: 1, en: 'she', zh: '她' },
    { kp: 'u1.words', level: 2, en: 'his', zh: '他的', misspell: ['hsi', 'hiz', 'hise'] },
    { kp: 'u1.words', level: 2, en: 'her', zh: '她的', misspell: ['hre', 'hur', 'herr'] },
    { kp: 'u1.introduce', level: 1, en: 'name', zh: '名字', misspell: ['nmae', 'neme', 'naem'] },
    { kp: 'u1.introduce', level: 1, en: 'this', zh: '这个', misspell: ['tihs', 'thes', 'thiss'] },
    { kp: 'u1.introduce', level: 1, en: 'my', zh: '我的' },
    { kp: 'u1.introduce', level: 2, en: 'nice', zh: '美好的', misspell: ['nise', 'niec', 'nicce'] },
    { kp: 'u1.introduce', level: 2, en: 'too', zh: '也' },
    {
      kp: 'u1.introduce',
      level: 2,
      en: 'Nice to meet you',
      zh: '见到你很高兴',
      misspell: ['Nise to meet you', 'Nice to meet yuo', 'Nice to meeet you'],
    },
    { kp: 'u1.introduce', level: 1, en: 'Good morning', zh: '早上好', misspell: ['Good moring', 'Good monring', 'Good mornig'] },
    { kp: 'u1.introduce', level: 1, en: 'Good afternoon', zh: '下午好', misspell: ['Good afternon', 'Good aftenoon', 'Good afternooon'] },
    { kp: 'u1.introduce', level: 2, en: 'Good evening', zh: '晚上好', misspell: ['Good evning', 'Good eveing', 'Good evenning'] },
    { kp: 'u1.introduce', level: 2, en: 'Good night', zh: '晚安', misspell: ['Good nigth', 'Good nihgt', 'Good niht'] },
    // ---------------------------------------------------------------- Unit 2
    { kp: 'u2.words', level: 1, en: 'swim', zh: '游泳', misspell: ['swin', 'swimm', 'siwm'] },
    { kp: 'u2.words', level: 1, en: 'skate', zh: '滑冰', misspell: ['sakte', 'skeat', 'skait'] },
    { kp: 'u2.words', level: 2, en: 'ride a bicycle', zh: '骑自行车', misspell: ['ride a bicyle', 'ride a bycicle', 'ride a bicycel'] },
    { kp: 'u2.words', level: 3, en: 'bicycle', zh: '自行车', misspell: ['bicyle', 'bycicle', 'bicycel'] },
    { kp: 'u2.words', level: 2, en: 'run fast', zh: '跑得快', misspell: ['run fest', 'rnu fast', 'run fsat'] },
    { kp: 'u2.words', level: 2, en: 'jump high', zh: '跳得高', misspell: ['jump hihg', 'jmup high', 'jupm high'] },
    { kp: 'u2.words', level: 1, en: 'fly', zh: '飞' },
    { kp: 'u2.words', level: 1, en: 'draw', zh: '画画', misspell: ['darw', 'dorw', 'draww'] },
    { kp: 'u2.words', level: 1, en: 'sing', zh: '唱歌', misspell: ['seng', 'sinng', 'sieng'] },
    { kp: 'u2.words', level: 1, en: 'dance', zh: '跳舞', misspell: ['dence', 'danse', 'dacne'] },
    { kp: 'u2.can-questions', level: 1, en: 'can', zh: '能；会' },
    { kp: 'u2.can-questions', level: 2, en: "can't", zh: '不能；不会', misspell: ["can'nt", "cann't", "ca'nt"] },
    { kp: 'u2.can-questions', level: 2, en: 'what', zh: '什么', misspell: ['waht', 'wath', 'whta'] },
    { kp: 'u2.can-but', level: 2, en: 'but', zh: '但是' },
    { kp: 'u2.can-but', level: 2, en: 'welcome', zh: '欢迎', misspell: ['wellcome', 'welcom', 'walcome'] },
    { kp: 'u2.can-but', level: 1, en: 'class', zh: '班级', misspell: ['calss', 'clas', 'clsas'] },
    { kp: 'u2.can-but', level: 3, en: 'our', zh: '我们的' },
  ],
  items: [
    // ------------------------------------------------------ u1.words
    {
      kp: 'u1.words',
      level: 1,
      kind: '选词填空',
      prompt: 'This is Peter. （　） is a boy.',
      answer: 'He',
      wrong: [
        ['She', 'en-meaning'],
        ['His', 'en-sentence'],
      ],
      explain: 'Peter 是男孩，“他是”用 He is。',
    },
    {
      kp: 'u1.words',
      level: 1,
      kind: '选词填空',
      prompt: 'This is Jill. （　） is a girl.',
      answer: 'She',
      wrong: [
        ['He', 'en-meaning'],
        ['Her', 'en-sentence'],
      ],
      explain: 'Jill 是女孩，“她是”用 She is。',
    },
    {
      kp: 'u1.words',
      level: 2,
      kind: '选词填空',
      prompt: "This is Peter. （　） name's Peter.",
      answer: 'His',
      wrong: [
        ['Her', 'en-meaning'],
        ['He', 'en-sentence'],
      ],
      explain: "Peter 是男孩，“他的名字”是 his name，所以说 His name's Peter.",
    },
    {
      kp: 'u1.words',
      level: 2,
      kind: '选词填空',
      prompt: "This is Jill. （　） name's Jill.",
      answer: 'Her',
      wrong: [
        ['His', 'en-meaning'],
        ['She', 'en-sentence'],
      ],
      explain: "Jill 是女孩，“她的名字”是 her name，所以说 Her name's Jill.",
    },
    {
      kp: 'u1.words',
      level: 2,
      kind: '选词填空',
      prompt: "This is my new （　）. His name's Ben.",
      answer: 'classmate',
      wrong: [
        ['meet', 'en-meaning'],
        ['new', 'en-meaning'],
      ],
      explain: 'my new classmate 是“我的新同学”。',
    },
    {
      kp: 'u1.words',
      level: 1,
      kind: '选词填空',
      prompt: 'Nice to （　） you.',
      answer: 'meet',
      wrong: [
        ['new', 'en-meaning'],
        ['name', 'en-meaning'],
      ],
      explain: 'meet 是“遇见、认识”，Nice to meet you. 意思是见到你很高兴。',
    },
    {
      kp: 'u1.words',
      level: 1,
      kind: '看中文选英文',
      prompt: '这是我的新同学。',
      answer: 'This is my new classmate.',
      wrong: [
        ['This is my classmate new.', 'en-sentence'],
        ['This is her new classmate.', 'en-meaning'],
      ],
      explain: 'new（新的）要放在 classmate（同学）前面；“我的”是 my。',
    },
    {
      kp: 'u1.words',
      level: 2,
      kind: '情景交际',
      prompt: '同学指着一个男孩问你他是谁，你想说“他是新同学”，你说（　）',
      answer: 'He is a new classmate.',
      wrong: [
        ['She is a new classmate.', 'en-meaning'],
        ['His is a new classmate.', 'en-sentence'],
      ],
      explain: '说男孩“他是”用 He is；his 是“他的”，后面要跟名词。',
    },
    {
      kp: 'u1.words',
      level: 2,
      kind: '补全对话',
      prompt: '— Is he a new classmate too?\n— Yes. （　）',
      answer: "His name's Joe.",
      wrong: [
        ["Her name's Joe.", 'en-meaning'],
        ["He name's Joe.", 'en-sentence'],
      ],
      explain: "问的是 he（男孩），说他的名字用 His name's…",
    },
    {
      kp: 'u1.words',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子（Jill 是女孩）：',
      answer: "Her name's Jill.",
      wrong: [
        ["His name's Jill.", 'en-meaning'],
        ["She name's Jill.", 'en-sentence'],
        ["her name's Jill.", 'en-sentence'],
      ],
      explain: "女孩的名字用 Her name's…，句首字母要大写。",
    },
    {
      kp: 'u1.words',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：他是一个男孩。',
      answer: 'He is a boy.',
      wrong: [
        ['She is a boy.', 'en-meaning'],
        ['His is a boy.', 'en-sentence'],
        ['he is a boy.', 'en-sentence'],
      ],
      explain: '“他是”用 He is，句首字母 H 要大写。',
    },

    // ------------------------------------------------------ u1.introduce
    {
      kp: 'u1.introduce',
      level: 1,
      kind: '情景交际',
      prompt: '向好朋友介绍新同学 Tom，你说（　）',
      answer: 'This is Tom.',
      wrong: [
        ["I'm Tom.", 'en-sentence'],
        ['Goodbye, Tom.', 'en-sentence'],
      ],
      explain: '介绍别人用 This is…。',
    },
    {
      kp: 'u1.introduce',
      level: 1,
      kind: '补全对话',
      prompt: '— Nice to meet you.\n— （　）',
      answer: 'Nice to meet you too.',
      wrong: [
        ['Thank you.', 'en-sentence'],
        ['Good night.', 'en-sentence'],
      ],
      explain: '别人说 Nice to meet you.，要回答 Nice to meet you too.',
    },
    {
      kp: 'u1.introduce',
      level: 1,
      kind: '情景交际',
      prompt: '第一次见到新同学，你可以说（　）',
      answer: 'Nice to meet you.',
      wrong: [
        ['Good night.', 'en-sentence'],
        ['Goodbye.', 'en-sentence'],
      ],
      explain: '第一次认识新朋友说 Nice to meet you.（见到你很高兴）。',
    },
    {
      kp: 'u1.introduce',
      level: 1,
      kind: '看中文选英文',
      prompt: '她的名字叫 Alice。',
      answer: "Her name's Alice.",
      wrong: [
        ["His name's Alice.", 'en-meaning'],
        ["My name's Alice.", 'en-meaning'],
      ],
      explain: "“她的名字”是 her name，name's 就是 name is。",
    },
    {
      kp: 'u1.introduce',
      level: 2,
      kind: '看中文选英文',
      prompt: '这是 Kitty。',
      answer: 'This is Kitty.',
      wrong: [
        ["I'm Kitty.", 'en-meaning'],
        ['This is kitty.', 'en-sentence'],
      ],
      explain: '介绍别人用 This is…，人名首字母要大写。',
    },
    {
      kp: 'u1.introduce',
      level: 2,
      kind: '情景交际',
      prompt: '你叫 Kitty，你想告诉大家自己的名字，你说（　）',
      answer: "My name's Kitty.",
      wrong: [
        ["Her name's Kitty.", 'en-sentence'],
        ["His name's Kitty.", 'en-sentence'],
      ],
      explain: "说自己的名字用 My name's…（我的名字是……）。",
    },
    {
      kp: 'u1.introduce',
      level: 2,
      kind: '补全对话',
      prompt: "— Good morning, Kitty. This is my new classmate. Her name's Jill.\n— （　）",
      answer: 'Nice to meet you, Jill.',
      wrong: [
        ['Good night, Jill.', 'en-sentence'],
        ["My name's Jill.", 'en-sentence'],
      ],
      explain: '认识新朋友时说 Nice to meet you，后面可以加上名字。',
    },
    {
      kp: 'u1.introduce',
      level: 3,
      kind: '补全对话',
      prompt: "— This is my new classmate. His name's Ben.\n— （　）",
      answer: 'Nice to meet you, Ben.',
      wrong: [
        ['Nice to meet you too, Ben.', 'en-sentence'],
        ["Her name's Ben.", 'en-meaning'],
      ],
      explain: '第一个说“见到你很高兴”的人说 Nice to meet you.；回答别人时才加 too。',
    },
    {
      kp: 'u1.introduce',
      level: 2,
      kind: '情景交际',
      prompt: '下午在学校门口遇到方老师，你说（　）',
      answer: 'Good afternoon, Miss Fang.',
      wrong: [
        ['Good morning, Miss Fang.', 'en-sentence'],
        ['Good night, Miss Fang.', 'en-sentence'],
      ],
      explain: '下午见面说 Good afternoon.',
    },
    {
      kp: 'u1.introduce',
      level: 3,
      kind: '情景交际',
      prompt: '晚上七点在深圳湾公园遇到邻居，见面时你说（　）',
      answer: 'Good evening.',
      wrong: [
        ['Good night.', 'en-sentence'],
        ['Good afternoon.', 'en-sentence'],
      ],
      explain: '晚上见面说 Good evening.；Good night. 是睡前或晚上道别时说的。',
    },
    {
      kp: 'u1.introduce',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：这是 Peter。',
      answer: 'This is Peter.',
      wrong: [
        ['this is Peter.', 'en-sentence'],
        ['This is peter.', 'en-sentence'],
        ['This is Peter', 'en-sentence'],
      ],
      explain: '句首字母大写，人名首字母大写，句末要有句号。',
    },
    {
      kp: 'u1.introduce',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：见到你也很高兴。',
      answer: 'Nice to meet you too.',
      wrong: [
        ['Nice to meet you to.', 'en-spelling'],
        ['nice to meet you too.', 'en-sentence'],
        ['Nice to meet too you.', 'en-sentence'],
      ],
      explain: '“也”是 too（两个 o），放在句子末尾；句首字母要大写。',
    },

    // ------------------------------------------------------ u2.words
    {
      kp: 'u2.words',
      level: 1,
      kind: '选词填空',
      prompt: 'A bird can （　）.',
      answer: 'fly',
      wrong: [
        ['skate', 'en-meaning'],
        ['ride a bicycle', 'en-meaning'],
      ],
      explain: '小鸟会飞：A bird can fly.',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '看中文选英文',
      prompt: '我会骑自行车。',
      answer: 'I can ride a bicycle.',
      wrong: [
        ['I can ride bicycle.', 'en-sentence'],
        ['I can run fast.', 'en-meaning'],
      ],
      explain: '骑自行车是 ride a bicycle，中间的 a 不能漏。',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '看中文选英文',
      prompt: '我能跳得很高。',
      answer: 'I can jump high.',
      wrong: [
        ['I can run fast.', 'en-meaning'],
        ['I can jump fast.', 'en-meaning'],
      ],
      explain: '跳得高是 jump high，high 是“高”。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '看中文选英文',
      prompt: '我能跑得很快。',
      answer: 'I can run fast.',
      wrong: [
        ['I can fast run.', 'en-sentence'],
        ['I can swim fast.', 'en-meaning'],
      ],
      explain: '跑得快是 run fast，fast 放在 run 后面。',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '情景交际',
      prompt: '在游泳池边，你想告诉朋友你会游泳，你说（　）',
      answer: 'I can swim.',
      wrong: [
        ['I can skate.', 'en-meaning'],
        ['I can sing.', 'en-meaning'],
      ],
      explain: 'swim 是游泳，skate 是滑冰，sing 是唱歌。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: 'Kitty 在冰场上滑来滑去。She can （　）.',
      answer: 'skate',
      wrong: [
        ['swim', 'en-meaning'],
        ['draw', 'en-meaning'],
      ],
      explain: '在冰上滑是滑冰，滑冰是 skate。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: 'I can （　） a bicycle.',
      answer: 'ride',
      wrong: [
        ['run', 'en-meaning'],
        ['jump', 'en-meaning'],
      ],
      explain: '骑自行车是 ride a bicycle。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: 'I can run （　）.',
      answer: 'fast',
      wrong: [
        ['high', 'en-sentence'],
        ['bicycle', 'en-meaning'],
      ],
      explain: '跑得快是 run fast；high 和 jump 在一起：jump high。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: 'Kitty 又唱又跳。She can sing and （　）.',
      answer: 'dance',
      wrong: [
        ['draw', 'en-meaning'],
        ['fly', 'en-meaning'],
      ],
      explain: '又唱又跳是 sing and dance，dance 是跳舞。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '找不同',
      prompt: '下面哪个不是表示动作（本领）的词？',
      answer: 'classmate',
      wrong: [
        ['swim', 'en-meaning'],
        ['dance', 'en-meaning'],
      ],
      explain: 'swim 游泳、dance 跳舞都是动作，classmate 是“同学”。',
    },
    {
      kp: 'u2.words',
      level: 3,
      kind: '看中文选英文',
      prompt: '骑自行车（选出完全正确的短语）',
      answer: 'ride a bicycle',
      wrong: [
        ['ride bicycle', 'en-sentence'],
        ['ride a bicyle', 'en-spelling'],
        ['a ride bicycle', 'en-sentence'],
      ],
      explain: 'ride a bicycle：a 放在 ride 和 bicycle 中间，bicycle 拼作 b-i-c-y-c-l-e。',
    },

    // ------------------------------------------------------ u2.can-questions
    {
      kp: 'u2.can-questions',
      level: 1,
      kind: '补全对话',
      prompt: '— Can you swim?\n— Yes, （　）.',
      answer: 'I can',
      wrong: [
        ["I can't", 'en-sentence'],
        ['you can', 'en-sentence'],
      ],
      explain: "用 Yes 回答，后面接 I can；用 No 回答才接 I can't。",
    },
    {
      kp: 'u2.can-questions',
      level: 1,
      kind: '补全对话',
      prompt: '— Can you skate?\n— No, （　）.',
      answer: "I can't",
      wrong: [
        ['I can', 'en-sentence'],
        ["you can't", 'en-sentence'],
      ],
      explain: "用 No 回答，后面接 I can't（我不会）。",
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '补全对话',
      prompt: '— Can he run fast?\n— Yes, （　）.',
      answer: 'he can',
      wrong: [
        ['she can', 'en-sentence'],
        ['I can', 'en-sentence'],
      ],
      explain: '问的是 he（他），回答也用 he：Yes, he can.',
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '补全对话',
      prompt: '— Can Kitty dance?\n— No, （　）.',
      answer: "she can't",
      wrong: [
        ["he can't", 'en-sentence'],
        ['she can', 'en-sentence'],
      ],
      explain: "Kitty 是女孩，用 she；No 后面接 can't：No, she can't.",
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '补全对话',
      prompt: '— What can you do?\n— （　）',
      answer: 'I can skate.',
      wrong: [
        ['Yes, I can.', 'en-sentence'],
        ["No, I can't.", 'en-sentence'],
      ],
      explain: 'What can you do? 问“你会做什么”，要说出本领：I can…；不能用 Yes / No 回答。',
    },
    {
      kp: 'u2.can-questions',
      level: 1,
      kind: '情景交际',
      prompt: '你想问朋友会不会游泳，你说（　）',
      answer: 'Can you swim?',
      wrong: [
        ['Do you can swim?', 'en-sentence'],
        ['Can you swims?', 'en-sentence'],
      ],
      explain: '问“你会……吗？”用 Can you…?，can 后面的动作词不变。',
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '情景交际',
      prompt: '你想问新同学会做什么，你说（　）',
      answer: 'What can you do?',
      wrong: [
        ['What do you can?', 'en-sentence'],
        ['What you can do?', 'en-sentence'],
      ],
      explain: '问“你会做什么？”固定说 What can you do?',
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '看中文选英文',
      prompt: '不，我不会。',
      answer: "No, I can't.",
      wrong: [
        ['No, I can.', 'en-sentence'],
        ["Yes, I can't.", 'en-sentence'],
      ],
      explain: "否定回答用 No, I can't.，No 和 can't 要一致。",
    },
    {
      kp: 'u2.can-questions',
      level: 2,
      kind: '选词填空',
      prompt: '— （　） you jump high?\n— Yes, I can.',
      answer: 'Can',
      wrong: [
        ['Do', 'en-sentence'],
        ['Are', 'en-sentence'],
      ],
      explain: '回答是 Yes, I can.，所以问句用 Can you…?',
    },
    {
      kp: 'u2.can-questions',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：她会游泳。',
      answer: 'She can swim.',
      wrong: [
        ['She can swims.', 'en-sentence'],
        ['She cans swim.', 'en-sentence'],
        ['He can swim.', 'en-meaning'],
      ],
      explain: 'can 和后面的动作词都不加 s；“她”是 she。',
    },
    {
      kp: 'u2.can-questions',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：他会骑自行车。',
      answer: 'He can ride a bicycle.',
      wrong: [
        ['He can rides a bicycle.', 'en-sentence'],
        ['He cans ride a bicycle.', 'en-sentence'],
        ['She can ride a bicycle.', 'en-meaning'],
      ],
      explain: 'he 后面也是 can + 动作词原形，都不加 s。',
    },
    {
      kp: 'u2.can-questions',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的问句：你会滑冰吗？',
      answer: 'Can you skate?',
      wrong: [
        ['Can you skate.', 'en-sentence'],
        ['can you skate?', 'en-sentence'],
        ['Do you can skate?', 'en-sentence'],
      ],
      explain: '问句用问号，句首字母大写，直接用 Can you…? 提问。',
    },

    // ------------------------------------------------------ u2.can-but
    {
      kp: 'u2.can-but',
      level: 1,
      kind: '选词填空',
      prompt: "I can skate, （　） I can't swim.",
      answer: 'but',
      wrong: [
        ['so', 'en-sentence'],
        ['or', 'en-sentence'],
      ],
      explain: '会滑冰、不会游泳，意思相反，用 but 连接。',
    },
    {
      kp: 'u2.can-but',
      level: 2,
      kind: '选词填空',
      prompt: '我不会唱歌，但是我会跳舞。I can\'t sing, （　） I can dance.',
      answer: 'but',
      wrong: [
        ['and', 'en-sentence'],
        ['or', 'en-sentence'],
      ],
      explain: '“但是”用 but，连接一件不会的事和一件会的事。',
    },
    {
      kp: 'u2.can-but',
      level: 2,
      kind: '选词填空',
      prompt: 'Kitty 会画画，不会唱歌。She can draw, but she （　） sing.',
      answer: "can't",
      wrong: [
        ['can', 'en-sentence'],
        ['cans', 'en-sentence'],
      ],
      explain: "不会唱歌用 can't sing。",
    },
    {
      kp: 'u2.can-but',
      level: 1,
      kind: '选词填空',
      prompt: '（　） to our class!',
      answer: 'Welcome',
      wrong: [
        ['Nice', 'en-meaning'],
        ['Meet', 'en-meaning'],
      ],
      explain: 'Welcome to our class! 意思是“欢迎来到我们班！”',
    },
    {
      kp: 'u2.can-but',
      level: 1,
      kind: '情景交际',
      prompt: '新同学 Jill 第一天来到你们班，你说（　）',
      answer: 'Welcome to our class, Jill.',
      wrong: [
        ['Good night, Jill.', 'en-sentence'],
        ['Goodbye, Jill.', 'en-sentence'],
      ],
      explain: '欢迎别人来到我们班，说 Welcome to our class.',
    },
    {
      kp: 'u2.can-but',
      level: 2,
      kind: '读一读',
      prompt: "This is Peter. He can run fast and jump high, but he can't skate.\nPeter 不会做什么？",
      answer: 'skate',
      wrong: [
        ['run fast', 'en-meaning'],
        ['jump high', 'en-meaning'],
      ],
      explain: "but 后面的 he can't skate 说明 Peter 不会滑冰。",
    },
    {
      kp: 'u2.can-but',
      level: 2,
      kind: '读一读',
      prompt: "This is Kitty. She can draw, but she can't swim or skate.\nKitty 会做什么？",
      answer: '画画',
      wrong: [
        ['游泳', 'en-meaning'],
        ['滑冰', 'en-meaning'],
      ],
      explain: "She can draw 说明 Kitty 会画画；can't swim or skate 说明她不会游泳和滑冰。",
    },
    {
      kp: 'u2.can-but',
      level: 3,
      kind: '读一读',
      prompt: "Kitty can sing and dance, but she can't swim.\nCan Kitty swim?",
      answer: "No, she can't.",
      wrong: [
        ['Yes, she can.', 'en-sentence'],
        ["No, he can't.", 'en-sentence'],
      ],
      explain: "短文说 she can't swim，Kitty 是女孩，所以回答 No, she can't.",
    },
    {
      kp: 'u2.can-but',
      level: 2,
      kind: '看中文选英文',
      prompt: '我会游泳，但是我不会滑冰。',
      answer: "I can swim, but I can't skate.",
      wrong: [
        ['I can swim, but I can skate.', 'en-sentence'],
        ["I can't swim, but I can skate.", 'en-meaning'],
      ],
      explain: "会游泳是 I can swim，不会滑冰是 I can't skate，中间用 but。",
    },
    {
      kp: 'u2.can-but',
      level: 3,
      kind: '情景交际',
      prompt: '你想说自己会骑自行车，但不会滑冰，你说（　）',
      answer: "I can ride a bicycle, but I can't skate.",
      wrong: [
        ["I can't ride a bicycle, but I can skate.", 'en-meaning'],
        ['I can ride a bicycle, but I can skate.', 'en-sentence'],
      ],
      explain: "会的用 can，不会的用 can't，but 连接两件相反的事。",
    },
    {
      kp: 'u2.can-but',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：她会画画，但是不会唱歌。',
      answer: "She can draw, but she can't sing.",
      wrong: [
        ["She can draw, but she can't sings.", 'en-sentence'],
        ["She can draws, but she can't sing.", 'en-sentence'],
        ['She can draw, but she can sing.', 'en-meaning'],
      ],
      explain: "can 和 can't 后面的动作词都不加 s；不会唱歌是 can't sing。",
    },
    {
      kp: 'u2.can-but',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：他跑得快，但是跳不高。',
      answer: "He can run fast, but he can't jump high.",
      wrong: [
        ['He can run fast, but he can jump high.', 'en-sentence'],
        ["He can run fast, but he can't jumps high.", 'en-sentence'],
        ["He can runs fast, but he can't jump high.", 'en-sentence'],
      ],
      explain: "but 前后是一件会、一件不会的事；can 和 can't 后面的动作词不加 s。",
    },
  ],
};
