import type { EnglishBank } from './types';

/** 英语 二年级上册（沪教牛津版 深圳用）Unit 1–2。kp = 知识点 id 去掉 "en-g2a."；zh 在本册内不重复。 */
export const EN_G2A: EnglishBank = {
  words: [
    // ---------------------------------------------------------------- Unit 1
    { kp: 'u1.greetings', level: 1, en: 'morning', zh: '早上', misspell: ['moring', 'mornig', 'monring'] },
    { kp: 'u1.greetings', level: 1, en: 'afternoon', zh: '下午', misspell: ['afternon', 'aftrenoon', 'afteroon'] },
    { kp: 'u1.greetings', level: 1, en: 'evening', zh: '晚上', misspell: ['evenning', 'evning', 'eveing'] },
    { kp: 'u1.greetings', level: 1, en: 'night', zh: '夜里', misspell: ['nigth', 'nignt', 'niht'] },
    { kp: 'u1.greetings', level: 1, en: 'Good morning', zh: '早上好', misspell: ['Good moring', 'Good monring', 'Goed morning'] },
    { kp: 'u1.greetings', level: 2, en: 'Good afternoon', zh: '下午好', misspell: ['Good afternon', 'Good aftenoon', 'Good afternooon'] },
    { kp: 'u1.greetings', level: 2, en: 'Good evening', zh: '晚上好', misspell: ['Good evning', 'Good eveing', 'Good evenning'] },
    { kp: 'u1.greetings', level: 2, en: 'Good night', zh: '晚安', misspell: ['Good nigth', 'Good nihgt', 'Good niht'] },
    { kp: 'u1.greetings', level: 1, en: 'Hello', zh: '你好', misspell: ['Helo', 'Hellow', 'Heloo'] },
    { kp: 'u1.greetings', level: 1, en: 'Goodbye', zh: '再见', misspell: ['Godbye', 'Goodbey', 'Goodbay'] },
    { kp: 'u1.how-are-you', level: 1, en: 'fine', zh: '很好的', misspell: ['fien', 'fline', 'fime'] },
    { kp: 'u1.how-are-you', level: 1, en: 'Thank you', zh: '谢谢你', misspell: ['Thenk you', 'Thank yuo', 'Thnak you'] },
    { kp: 'u1.how-are-you', level: 2, en: 'how', zh: '怎么样' },
    // ---------------------------------------------------------------- Unit 2
    { kp: 'u2.words', level: 1, en: 'boy', zh: '男孩', misspell: ['boi', 'byo', 'booy'] },
    { kp: 'u2.words', level: 1, en: 'girl', zh: '女孩', misspell: ['gril', 'grl', 'gilr'] },
    { kp: 'u2.words', level: 1, en: 'big', zh: '大的', misspell: ['bgi', 'bigg', 'bia'] },
    { kp: 'u2.words', level: 1, en: 'small', zh: '小的', misspell: ['smal', 'samll', 'smoll'] },
    { kp: 'u2.i-am-you-are', level: 1, en: 'tall', zh: '高的', misspell: ['tal', 'taal', 'tlal'] },
    { kp: 'u2.i-am-you-are', level: 1, en: 'short', zh: '矮的', misspell: ['shrot', 'shotr', 'shorte'] },
    { kp: 'u2.i-am-you-are', level: 2, en: "I'm", zh: '我是' },
    { kp: 'u2.i-am-you-are', level: 2, en: "you're", zh: '你是', misspell: ['youre', "you'er", "yuo're"] },
  ],
  items: [
    // ------------------------------------------------------ u1.greetings
    {
      kp: 'u1.greetings',
      level: 1,
      kind: '情景交际',
      prompt: '早上见到老师，你说（　）',
      answer: 'Good morning.',
      wrong: [
        ['Good evening.', 'en-sentence'],
        ['Good night.', 'en-sentence'],
      ],
      explain: '早上见面说 Good morning.',
    },
    {
      kp: 'u1.greetings',
      level: 1,
      kind: '情景交际',
      prompt: '下午放学时见到老师，你说（　）',
      answer: 'Good afternoon.',
      wrong: [
        ['Good morning.', 'en-sentence'],
        ['Good night.', 'en-sentence'],
      ],
      explain: '下午见面说 Good afternoon.',
    },
    {
      kp: 'u1.greetings',
      level: 2,
      kind: '情景交际',
      prompt: '晚上散步遇到邻居，见面打招呼说（　）',
      answer: 'Good evening.',
      wrong: [
        ['Good night.', 'en-sentence'],
        ['Good morning.', 'en-sentence'],
      ],
      explain: '晚上见面说 Good evening.；Good night. 是睡觉前或晚上分别时说的。',
    },
    {
      kp: 'u1.greetings',
      level: 1,
      kind: '情景交际',
      prompt: '睡觉前和妈妈说（　）',
      answer: 'Good night.',
      wrong: [
        ['Good evening.', 'en-sentence'],
        ['Good afternoon.', 'en-sentence'],
      ],
      explain: '睡觉前说 Good night.（晚安）。',
    },
    {
      kp: 'u1.greetings',
      level: 3,
      kind: '情景交际',
      prompt: '晚上从朋友家离开，和朋友道别时说（　）',
      answer: 'Good night.',
      wrong: [
        ['Good evening.', 'en-sentence'],
        ['Good morning.', 'en-sentence'],
      ],
      explain: '晚上分别时说 Good night.；Good evening. 只在晚上见面时说。',
    },
    {
      kp: 'u1.greetings',
      level: 2,
      kind: '情景交际',
      prompt: '早上见到同学 Kitty，你说（　）',
      answer: 'Good morning, Kitty.',
      wrong: [
        ['Good night, Kitty.', 'en-sentence'],
        ['Goodbye, Kitty.', 'en-sentence'],
      ],
      explain: '早上见面打招呼说 Good morning，后面加上名字。',
    },
    {
      kp: 'u1.greetings',
      level: 1,
      kind: '看中文选英文',
      prompt: '下午好。',
      answer: 'Good afternoon.',
      wrong: [
        ['Good morning.', 'en-meaning'],
        ['Good evening.', 'en-meaning'],
      ],
      explain: 'afternoon 是下午，下午好就是 Good afternoon.',
    },
    {
      kp: 'u1.greetings',
      level: 1,
      kind: '看中文选英文',
      prompt: '晚安。',
      answer: 'Good night.',
      wrong: [
        ['Good evening.', 'en-meaning'],
        ['Goodbye.', 'en-meaning'],
      ],
      explain: '晚安是 Good night.；Good evening. 是晚上好，Goodbye. 是再见。',
    },
    {
      kp: 'u1.greetings',
      level: 2,
      kind: '补全对话',
      prompt: '— Good morning, Miss Fang.\n— （　）',
      answer: 'Good morning.',
      wrong: [
        ['Good night.', 'en-sentence'],
        ['Good afternoon.', 'en-sentence'],
      ],
      explain: '别人说 Good morning，我们也回答 Good morning.',
    },
    {
      kp: 'u1.greetings',
      level: 2,
      kind: '选词填空',
      prompt: '晚上见到方老师：Good （　）, Miss Fang.',
      answer: 'evening',
      wrong: [
        ['night', 'en-sentence'],
        ['morning', 'en-meaning'],
      ],
      explain: '晚上见面说 Good evening. night 用在 Good night（晚安）里。',
    },
    {
      kp: 'u1.greetings',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：早上好，Danny。',
      answer: 'Good morning, Danny.',
      wrong: [
        ['good morning, Danny.', 'en-sentence'],
        ['Good morning, danny.', 'en-sentence'],
        ['Good morning, Danny', 'en-sentence'],
      ],
      explain: '句子第一个字母要大写，名字第一个字母也大写，句子末尾有句号。',
    },
    {
      kp: 'u1.greetings',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：下午好，方老师。',
      answer: 'Good afternoon, Miss Fang.',
      wrong: [
        ['good afternoon, Miss Fang.', 'en-sentence'],
        ['Good afternoon, miss fang.', 'en-sentence'],
      ],
      explain: '句首的 Good 要大写，Miss Fang 两个词的第一个字母也要大写。',
    },

    // ------------------------------------------------------ u1.how-are-you
    {
      kp: 'u1.how-are-you',
      level: 1,
      kind: '情景交际',
      prompt: '别人问你 “How are you?”，你回答（　）',
      answer: "I'm fine. Thank you.",
      wrong: [
        ["I'm Danny.", 'en-sentence'],
        ['Good night.', 'en-sentence'],
      ],
      explain: "别人问你好不好，回答 I'm fine. Thank you.",
    },
    {
      kp: 'u1.how-are-you',
      level: 1,
      kind: '情景交际',
      prompt: '你想问老师身体好不好，你说（　）',
      answer: 'How are you?',
      wrong: [
        ['Thank you.', 'en-sentence'],
        ['Good night.', 'en-sentence'],
      ],
      explain: '问别人好不好，说 How are you?',
    },
    {
      kp: 'u1.how-are-you',
      level: 2,
      kind: '补全对话',
      prompt: '— Good morning, Danny. How are you?\n— （　）',
      answer: "I'm fine. Thank you.",
      wrong: [
        ['Good night.', 'en-sentence'],
        ["You're fine.", 'en-sentence'],
      ],
      explain: "听到 How are you? 要回答 I'm fine. Thank you.",
    },
    {
      kp: 'u1.how-are-you',
      level: 2,
      kind: '补全对话',
      prompt: "— How are you, Kitty?\n— I'm fine. （　）",
      answer: 'Thank you.',
      wrong: [
        ['Good night.', 'en-sentence'],
        ['Hello.', 'en-sentence'],
      ],
      explain: "回答 I'm fine 以后，别忘了说 Thank you. 谢谢对方的关心。",
    },
    {
      kp: 'u1.how-are-you',
      level: 1,
      kind: '看中文选英文',
      prompt: '你好吗？',
      answer: 'How are you?',
      wrong: [
        ["I'm fine.", 'en-meaning'],
        ['Thank you.', 'en-meaning'],
      ],
      explain: '“你好吗？”用英语说 How are you?',
    },
    {
      kp: 'u1.how-are-you',
      level: 1,
      kind: '看中文选英文',
      prompt: '我很好，谢谢你。',
      answer: "I'm fine. Thank you.",
      wrong: [
        ["I'm fine. Goodbye.", 'en-meaning'],
        ['How are you? Thank you.', 'en-meaning'],
      ],
      explain: "我很好是 I'm fine.，谢谢你是 Thank you.",
    },
    {
      kp: 'u1.how-are-you',
      level: 2,
      kind: '选词填空',
      prompt: 'How （　） you?',
      answer: 'are',
      wrong: [
        ['is', 'en-sentence'],
        ['am', 'en-sentence'],
      ],
      explain: '问“你好吗”固定说 How are you?',
    },
    {
      kp: 'u1.how-are-you',
      level: 2,
      kind: '选词填空',
      prompt: "I'm （　）. Thank you.",
      answer: 'fine',
      wrong: [
        ['night', 'en-meaning'],
        ['how', 'en-meaning'],
      ],
      explain: "fine 是“很好的”，I'm fine. 就是“我很好”。",
    },
    {
      kp: 'u1.how-are-you',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的问句：你好吗？',
      answer: 'How are you?',
      wrong: [
        ['How are you.', 'en-sentence'],
        ['how are you?', 'en-sentence'],
      ],
      explain: '问句末尾用问号“?”，句子第一个字母 H 要大写。',
    },
    {
      kp: 'u1.how-are-you',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：我很好。',
      answer: "I'm fine.",
      wrong: [
        ["i'm fine.", 'en-sentence'],
        ['Im fine.', 'en-sentence'],
      ],
      explain: "I 永远大写；I'm 是 I am 的缩写，中间有一撇。",
    },
    {
      kp: 'u1.how-are-you',
      level: 3,
      kind: '情景交际',
      prompt: '下午见到方老师，先打招呼再问好，你说（　）',
      answer: 'Good afternoon. How are you?',
      wrong: [
        ['Good night. How are you?', 'en-sentence'],
        ['Good afternoon. Thank you.', 'en-sentence'],
      ],
      explain: '下午打招呼说 Good afternoon.，问好说 How are you?',
    },

    // ------------------------------------------------------ u2.words
    {
      kp: 'u2.words',
      level: 1,
      kind: '选词填空',
      prompt: "Danny 是男孩：I'm a （　）.",
      answer: 'boy',
      wrong: [
        ['girl', 'en-meaning'],
        ['big', 'en-meaning'],
      ],
      explain: 'boy 是男孩，girl 是女孩。',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '选词填空',
      prompt: "Mary 是女孩：I'm a （　）.",
      answer: 'girl',
      wrong: [
        ['boy', 'en-meaning'],
        ['small', 'en-meaning'],
      ],
      explain: 'girl 是女孩，boy 是男孩。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: "把双臂张得大大的，说：I'm （　）!",
      answer: 'big',
      wrong: [
        ['small', 'en-meaning'],
        ['short', 'en-meaning'],
      ],
      explain: '张开双臂表示大，big 是大的。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '选词填空',
      prompt: "缩成小小的一团，说：I'm （　）!",
      answer: 'small',
      wrong: [
        ['big', 'en-meaning'],
        ['tall', 'en-meaning'],
      ],
      explain: '缩成一团表示小，small 是小的。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '配对词',
      prompt: 'big（大的）和哪个词意思正好相反？',
      answer: 'small',
      wrong: [
        ['boy', 'en-meaning'],
        ['girl', 'en-meaning'],
      ],
      explain: 'big 大的，small 小的，意思正好相反。',
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '配对词',
      prompt: 'boy（男孩）和哪个词是一对小伙伴词？',
      answer: 'girl',
      wrong: [
        ['big', 'en-meaning'],
        ['small', 'en-meaning'],
      ],
      explain: 'boy 男孩，girl 女孩，两个词成对记。',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '看中文选英文',
      prompt: '一个男孩',
      answer: 'a boy',
      wrong: [
        ['a girl', 'en-meaning'],
        ['boy a', 'en-sentence'],
      ],
      explain: '一个男孩说 a boy，a 放在前面。',
    },
    {
      kp: 'u2.words',
      level: 1,
      kind: '看中文选英文',
      prompt: '一个女孩',
      answer: 'a girl',
      wrong: [
        ['a boy', 'en-meaning'],
        ['a gril', 'en-spelling'],
      ],
      explain: '一个女孩说 a girl，girl 拼作 g-i-r-l。',
    },
    {
      kp: 'u2.words',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出正确的句子：我是一个男孩。',
      answer: "I'm a boy.",
      wrong: [
        ["I'm boy.", 'en-sentence'],
        ["I'm a girl.", 'en-meaning'],
        ["i'm a boy.", 'en-sentence'],
      ],
      explain: "说“一个男孩”要加 a：I'm a boy. I 要大写。",
    },
    {
      kp: 'u2.words',
      level: 2,
      kind: '找不同',
      prompt: '下面哪个词不是说人的？',
      answer: 'big',
      wrong: [
        ['boy', 'en-meaning'],
        ['girl', 'en-meaning'],
      ],
      explain: 'boy 男孩、girl 女孩是人，big 是“大的”。',
    },

    // ------------------------------------------------------ u2.i-am-you-are
    {
      kp: 'u2.i-am-you-are',
      level: 1,
      kind: '情景交际',
      prompt: '你叫 Mary，向别人介绍自己，你说（　）',
      answer: "I'm Mary.",
      wrong: [
        ["You're Mary.", 'en-sentence'],
        ['Hi, Mary.', 'en-sentence'],
      ],
      explain: "说自己用 I'm…，说对方用 You're…。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 1,
      kind: '情景交际',
      prompt: '你想告诉 Mary“你很高”，你说（　）',
      answer: "You're tall.",
      wrong: [
        ["I'm tall.", 'en-sentence'],
        ["You're short.", 'en-meaning'],
      ],
      explain: "说对方用 You're，高是 tall：You're tall.",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 1,
      kind: '看中文选英文',
      prompt: '我很矮。',
      answer: "I'm short.",
      wrong: [
        ["You're short.", 'en-sentence'],
        ["I'm tall.", 'en-meaning'],
      ],
      explain: "说自己用 I'm，矮是 short：I'm short.",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 2,
      kind: '看中文选英文',
      prompt: '你是一个女孩。',
      answer: "You're a girl.",
      wrong: [
        ["I'm a girl.", 'en-sentence'],
        ["You're a boy.", 'en-meaning'],
      ],
      explain: "“你是”说 You're，女孩是 girl，前面加 a。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 2,
      kind: '补全对话',
      prompt: "— Hello, I'm Danny.\n— Hi, Danny. （　）（Mary 说）",
      answer: "I'm Mary.",
      wrong: [
        ["You're Mary.", 'en-sentence'],
        ["I'm Danny.", 'en-sentence'],
      ],
      explain: "Mary 介绍自己，要说 I'm Mary.",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 1,
      kind: '选词填空',
      prompt: 'Danny 介绍自己：（　） Danny.',
      answer: "I'm",
      wrong: [
        ["You're", 'en-sentence'],
        ['I', 'en-sentence'],
      ],
      explain: "介绍自己说 I'm…，I'm 就是 I am（我是）。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 2,
      kind: '选词填空',
      prompt: "Mary 高，Danny 矮。Danny 说：Oh, （　） tall. I'm short.",
      answer: "you're",
      wrong: [
        ["I'm", 'en-sentence'],
        ['you', 'en-sentence'],
      ],
      explain: "Danny 说 Mary 高，说对方要用 you're（你是）。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：你很高。',
      answer: "You're tall.",
      wrong: [
        ["you're tall.", 'en-sentence'],
        ['Youre tall.', 'en-sentence'],
        ["You're tall", 'en-sentence'],
      ],
      explain: "句首字母大写，You're 中间有一撇，句末要有句号。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 3,
      kind: '选出正确的句子',
      prompt: '选出书写正确的句子：我是 Mary。',
      answer: "I'm Mary.",
      wrong: [
        ["I'm mary.", 'en-sentence'],
        ["i'm Mary.", 'en-sentence'],
        ['Im Mary.', 'en-sentence'],
      ],
      explain: "I 永远大写，名字首字母大写，I'm 中间有一撇。",
    },
    {
      kp: 'u2.i-am-you-are',
      level: 3,
      kind: '情景交际',
      prompt: '你个子小，朋友个子大。你对朋友说（　）',
      answer: "You're big. I'm small.",
      wrong: [
        ["I'm big. You're small.", 'en-sentence'],
        ["You're small. I'm big.", 'en-meaning'],
      ],
      explain: "朋友大，说 You're big.；自己小，说 I'm small.",
    },
  ],
};
