import type { ErrorTag } from '@xuexi/shared';
import type { BankLevel, ChoiceItem, EnglishBank, EnWord } from './types';

/**
 * 英语 二年级上册（沪教牛津版 深圳用，新版 Big Question 结构）Unit 1–6。
 * kp = 知识点 id 去掉 "en-g2a."；zh 在本册内不重复。
 * 单词、字母组合来自课本目录页；句型按 Big Question 推断（见 curriculum 的 sourceNote）。
 */

const M: ErrorTag = 'en-meaning';
const S: ErrorTag = 'en-sentence';
const P: ErrorTag = 'en-spelling';
type Tier = 'stretch' | 'creative';

function q(
  kp: string,
  level: BankLevel,
  kind: string,
  prompt: string,
  answer: string,
  wrong: ChoiceItem['wrong'],
  explain: string,
  tier?: Tier,
): ChoiceItem {
  return { kp, level, kind, prompt, answer, wrong, explain, ...(tier ? { tier } : {}) };
}

// ---- phonics helpers (word families) ----
const rhyme = (kp: string, level: BankLevel, base: string, ans: string, w1: string, w2: string, fam: string) =>
  q(kp, level, '拼读', `哪个单词和 ${base} 的结尾音一样？`, ans, [[w1, P], [w2, P]], `${base} 和 ${ans} 都在 ${fam} 家族，结尾的音一样。`);
const family = (kp: string, level: BankLevel, fam: string, ans: string, w1: string, w2: string) =>
  q(kp, level, '拼读', `选出 ${fam} 家族的单词`, ans, [[w1, P], [w2, P]], `${ans} 的结尾是 ${fam.slice(1)}，属于 ${fam} 家族。`);
const blend = (kp: string, level: BankLevel, onset: string, rime: string, ans: string, w1: string, w2: string) =>
  q(kp, level, '拼读', `${onset} + ${rime} = （　）`, ans, [[w1, P], [w2, P]], `${onset} 和 ${rime} 拼在一起，读作 ${ans}。`);
const swap = (kp: string, level: BankLevel, from: string, a: string, b: string, ans: string, w1: string, w2: string) =>
  q(kp, level, '拼读', `把 ${from} 开头的 ${a} 换成 ${b}，变成（　）`, ans, [[w1, P], [w2, P]], `${from} 去掉 ${a}，换上 ${b}，就是 ${ans}。`);
const odd = (kp: string, level: BankLevel, trio: string, ans: string, w1: string, w2: string, explain: string) =>
  q(kp, level, '拼读', `读一读，哪个单词的结尾音和另外两个不同？（${trio}）`, ans, [[w1, P], [w2, P]], explain);

const w = (kp: string, level: BankLevel, en: string, zh: string, misspell: string[]): EnWord => ({ kp, level, en, zh, misspell });

export const EN_G2A: EnglishBank = {
  words: [
    // ---------------------------------------------------------------- Unit 1
    w('u1.words', 1, 'see', '看见', ['seee', 'sse', 'siie']),
    w('u1.words', 1, 'hear', '听见', ['haer', 'heer', 'hiar']),
    w('u1.words', 1, 'smell', '闻', ['smel', 'smeel', 'smlel']),
    w('u1.words', 1, 'taste', '尝', ['tast', 'taset', 'tasde']),
    w('u1.words', 1, 'feel', '摸；感觉', ['fiel', 'feell', 'fele']),
    w('u1.words', 2, 'cat', '猫', ['cta', 'caat', 'catt']),
    w('u1.words', 2, 'hat', '帽子', ['hta', 'haat', 'hatt']),
    w('u1.words', 2, 'bat', '蝙蝠', ['bta', 'baat', 'bayt']),
    w('u1.words', 2, 'mat', '垫子', ['mta', 'maat', 'mayt']),
    w('u1.words', 2, 'map', '地图', ['mpa', 'maap', 'mapp']),
    w('u1.words', 2, 'tap', '水龙头', ['tpa', 'taap', 'tapp']),
    w('u1.words', 2, 'nap', '小睡', ['npa', 'naap', 'napp']),
    // ---------------------------------------------------------------- Unit 2
    w('u2.words', 1, 'uncle', '叔叔；舅舅', ['uncel', 'unkle', 'ancle']),
    w('u2.words', 1, 'aunt', '阿姨；姑姑', ['anut', 'aunnt', 'auntt']),
    w('u2.words', 1, 'cousin', '堂（表）兄弟姐妹', ['cusin', 'cousen', 'cuosin']),
    w('u2.words', 1, 'old', '年老的', ['odl', 'oold', 'olld']),
    w('u2.words', 1, 'young', '年轻的', ['yong', 'yuong', 'youg']),
    w('u2.words', 1, 'cute', '可爱的', ['cuet', 'kute', 'cutte']),
    w('u2.words', 2, 'ham', '火腿', ['hma', 'haam', 'hamn']),
    w('u2.words', 2, 'jam', '果酱', ['jma', 'jaam', 'jamm']),
    w('u2.words', 2, 'fan', '扇子', ['fna', 'faan', 'fann']),
    w('u2.words', 2, 'man', '男人', ['mna', 'maan', 'manm']),
    w('u2.words', 2, 'pan', '平底锅', ['pna', 'paan', 'pann']),
    w('u2.words', 2, 'van', '面包车', ['vna', 'vaan', 'vann']),
    // ---------------------------------------------------------------- Unit 3
    w('u3.words', 1, 'doll', '洋娃娃', ['dooll', 'dlol', 'dolll']),
    w('u3.words', 1, 'toy plane', '玩具飞机', ['toy plnae', 'toy palne', 'toy plaen']),
    w('u3.words', 1, 'toy bear', '玩具熊', ['toy baer', 'toy bera', 'tyo bear']),
    w('u3.words', 1, 'ball', '球', ['baal', 'bll', 'balll']),
    w('u3.words', 1, 'robot', '机器人', ['robt', 'rebot', 'robbot']),
    w('u3.words', 1, 'jigsaw puzzle', '拼图', ['jigsaw puzle', 'jigsow puzzle', 'jigsaw pazzle']),
    w('u3.words', 2, 'bed', '床', ['bde', 'beed', 'bedd']),
    w('u3.words', 2, 'red', '红色的', ['rde', 'redd', 'rred']),
    w('u3.words', 2, 'net', '网', ['nte', 'neet', 'netn']),
    w('u3.words', 2, 'pet', '宠物', ['pte', 'peet', 'pett']),
    w('u3.words', 2, 'wet', '湿的', ['wte', 'weet', 'wett']),
    // ---------------------------------------------------------------- Unit 4
    w('u4.words', 1, 'pet shop', '宠物店', ['pet shap', 'pet sohp', 'pte shop']),
    w('u4.words', 1, 'fruit shop', '水果店', ['fruit shap', 'friut shop', 'fruit sohp']),
    w('u4.words', 1, 'toy shop', '玩具店', ['toy shap', 'toy sohp', 'tyo shop']),
    w('u4.words', 1, 'cinema', '电影院', ['cinama', 'cinemma', 'sinema']),
    w('u4.words', 1, 'zoo', '动物园', ['zooo', 'zuo', 'zou']),
    w('u4.words', 1, 'park', '公园', ['prak', 'parck', 'paark']),
    w('u4.words', 2, 'hen', '母鸡', ['hne', 'heen', 'henn']),
    w('u4.words', 2, 'pen', '钢笔', ['pne', 'peen', 'pehn']),
    w('u4.words', 2, 'ten', '十', ['tne', 'tenn', 'tenh']),
    w('u4.words', 2, 'big', '大的', ['bgi', 'biig', 'bigg']),
    w('u4.words', 2, 'dig', '挖', ['dgi', 'diig', 'dihg']),
    w('u4.words', 2, 'wig', '假发', ['wgi', 'wiig', 'wigg']),
    // ---------------------------------------------------------------- Unit 5
    w('u5.words', 1, 'cow', '奶牛', ['cwo', 'coww', 'coow']),
    w('u5.words', 1, 'sheep', '绵羊', ['shep', 'sheeep', 'sheap']),
    w('u5.words', 1, 'duck', '鸭子', ['duk', 'dcuk', 'duckk']),
    w('u5.words', 1, 'chick', '小鸡', ['chik', 'chikc', 'chiick']),
    w('u5.words', 1, 'chicken', '鸡', ['chiken', 'chikcen', 'chickin']),
    w('u5.words', 1, 'pig', '猪', ['pgi', 'piig', 'pigg']),
    w('u5.words', 2, 'pin', '别针', ['pni', 'piin', 'pinn']),
    w('u5.words', 2, 'bin', '垃圾箱', ['bni', 'biin', 'binn']),
    w('u5.words', 2, 'fin', '鱼鳍', ['fni', 'fiin', 'finh']),
    w('u5.words', 2, 'ship', '轮船', ['shpi', 'shiip', 'shipp']),
    w('u5.words', 2, 'lip', '嘴唇', ['lpi', 'liip', 'lipp']),
    w('u5.words', 2, 'zip', '拉链', ['zpi', 'ziip', 'zipp']),
    // ---------------------------------------------------------------- Unit 6
    w('u6.words', 1, 'play with lanterns', '玩灯笼', ['play with lantens', 'play with lanterms', 'play wiht lanterns']),
    w('u6.words', 1, 'eat mooncakes', '吃月饼', ['eat mooncaks', 'eat moncakes', 'eat moomcakes']),
    w('u6.words', 1, 'solve riddles', '猜谜语', ['solve ridles', 'slove riddles', 'solve riddels']),
    w('u6.words', 1, 'look at the moon', '赏月', ['look at the moom', 'look at teh moon', 'look at the mooon']),
    w('u6.words', 2, 'mooncake', '月饼', ['moncake', 'mooncak', 'mooncaek']),
    w('u6.words', 2, 'lantern', '灯笼', ['lantren', 'lanteen', 'lanturn']),
    w('u6.words', 2, 'moon', '月亮', ['mooon', 'moom', 'mnoo']),
    w('u6.words', 2, 'riddle', '谜语', ['ridle', 'riddel', 'ridlde']),
    w('u6.words', 2, 'Mid-Autumn Festival', '中秋节', ['Mid-Autum Festival', 'Mid-Autumn Festivel', 'Mid-Autumn Fastival']),
  ],
  items: [
    // ================================================================ Unit 1
    // ------------------------------------------------------ u1.words
    rhyme('u1.words', 1, 'cat', 'hat', 'map', 'tap', '-at'),
    rhyme('u1.words', 1, 'map', 'tap', 'cat', 'hat', '-ap'),
    rhyme('u1.words', 2, 'bat', 'mat', 'nap', 'map', '-at'),
    family('u1.words', 1, '-at', 'bat', 'tap', 'map'),
    family('u1.words', 1, '-ap', 'nap', 'mat', 'cat'),
    blend('u1.words', 1, 'c', 'at', 'cat', 'hat', 'map'),
    blend('u1.words', 1, 'm', 'ap', 'map', 'mat', 'nap'),
    swap('u1.words', 2, 'cat', 'c', 'h', 'hat', 'map', 'tap'),
    swap('u1.words', 2, 'map', 'm', 't', 'tap', 'mat', 'cat'),
    odd('u1.words', 2, 'cat / mat / map', 'map', 'cat', 'mat', 'cat、mat 结尾是 -at，map 结尾是 -ap。'),
    odd('u1.words', 2, 'hat / nap / tap', 'hat', 'nap', 'tap', 'nap、tap 结尾是 -ap，hat 结尾是 -at。'),
    q('u1.words', 1, '选词填空', '用鼻子闻一闻花香，是（　）', 'smell', [['see', M], ['hear', M]], 'smell 是“闻”，用鼻子闻。'),
    q('u1.words', 1, '选词填空', '用耳朵听一听小鸟叫，是（　）', 'hear', [['see', M], ['feel', M]], 'hear 是“听见”，用耳朵听。'),
    q('u1.words', 1, '选词填空', '用嘴巴尝一尝荔枝，是（　）', 'taste', [['smell', M], ['hear', M]], 'taste 是“尝”，用嘴巴尝。'),
    q('u1.words', 1, '选词填空', '用手摸一摸小猫，是（　）', 'feel', [['see', M], ['taste', M]], 'feel 是“摸、感觉”，用手摸。'),
    q('u1.words', 1, '选词填空', '用眼睛看一看地图，是（　）', 'see', [['smell', M], ['feel', M]], 'see 是“看见”，用眼睛看。'),
    q('u1.words', 2, '补全单词', '选字母补全单词：m（　）p（地图）', 'a', [['e', P], ['u', P]], '地图 map 拼作 m-a-p。'),
    q('u1.words', 2, '补全单词', '选字母补全单词：c（　）t（猫）', 'a', [['e', P], ['i', P]], '猫 cat 拼作 c-a-t。'),
    q('u1.words', 2, '补全单词', '选字母补全单词：sm（　）ll（闻）', 'e', [['o', P], ['i', P]], '闻 smell 拼作 s-m-e-l-l，最后有两个 l。'),
    q('u1.words', 2, '补全单词', '选字母补全单词：t（　）ste（尝）', 'a', [['e', P], ['o', P]], '尝 taste 拼作 t-a-s-t-e。'),
    q('u1.words', 2, '补全单词', '选字母补全单词：h（　）ar（听见）', 'e', [['i', P], ['u', P]], '听见 hear 拼作 h-e-a-r。'),
    // 拔高
    q('u1.words', 3, '拼读', '哪一组单词的结尾音都一样？（-at / -ap）', 'cat, hat, bat', [['cat, nap, mat', P], ['map, tap, hat', P]], 'cat、hat、bat 都在 -at 家族。', 'stretch'),
    q('u1.words', 3, '拼读', 'cat 变成 hat，再变成 mat，每次变的是哪个字母？', '第一个字母', [['中间的字母', P], ['最后一个字母', P]], '同一家族的单词结尾不变，只换开头的字母。', 'stretch'),
    q('u1.words', 3, '找不同', '下面哪个词不是五种感官的动作？', 'map', [['see', M], ['hear', M]], 'see 看、hear 听都是感官动作，map 是“地图”。', 'stretch'),
    q('u1.words', 3, '拼读', '把 nap 开头的 n 换成 m，再把 m 换成 t，最后变成（　）', 'tap', [['map', P], ['mat', P]], 'nap → map → tap，结尾 -ap 一直不变。', 'stretch'),
    q('u1.words', 3, '拼读', '哪个单词和 cat 押韵，又能戴在头上？', 'hat', [['mat', M], ['map', P]], 'hat（帽子）和 cat 都在 -at 家族；mat 是垫子，map 是 -ap 家族。', 'stretch'),
    q('u1.words', 3, '补全单词', '两个词都要补对：c（　）t 猫、m（　）p 地图', 'a, a', [['a, e', P], ['e, a', P]], 'cat 和 map 中间都是字母 a。', 'stretch'),
    // 创新
    q('u1.words', 2, '读一读', 'Look! A cat. The cat is on the mat.\n猫在哪里？', '在垫子上', [['在帽子里', M], ['在地图上', M]], 'on the mat 是“在垫子上”，mat 是垫子。', 'creative'),
    q('u1.words', 2, '猜一猜', '猜一猜：铺在地上，和 cat 押韵，是（　）', 'mat', [['map', P], ['hat', M]], 'mat（垫子）铺在地上，和 cat 都在 -at 家族。', 'creative'),
    q('u1.words', 3, '看图说话', '图上：小猫戴着帽子，坐在一张地图上。选出正确的一组词', 'cat, hat, map', [['cat, hat, mat', M], ['bat, hat, map', M]], '小猫 cat，帽子 hat，地图 map。', 'creative'),
    q('u1.words', 2, '情景交际', '博物馆里的牌子写着“请勿触摸”，是不让我们用手（　）', 'feel', [['see', M], ['hear', M]], '用手摸是 feel。', 'creative'),

    // ------------------------------------------------------ u1.talk
    q('u1.talk', 1, '选词填空', 'I can see with my （　）.', 'eyes', [['ears', M], ['nose', M]], '看要用眼睛：see with my eyes。'),
    q('u1.talk', 1, '选词填空', 'I can hear with my （　）.', 'ears', [['eyes', M], ['mouth', M]], '听要用耳朵：hear with my ears。'),
    q('u1.talk', 1, '选词填空', 'I can smell with my （　）.', 'nose', [['ears', M], ['hands', M]], '闻要用鼻子：smell with my nose。'),
    q('u1.talk', 1, '选词填空', 'I can taste with my （　）.', 'mouth', [['eyes', M], ['ears', M]], '尝要用嘴巴：taste with my mouth。'),
    q('u1.talk', 1, '选词填空', 'I can feel with my （　）.', 'hands', [['ears', M], ['eyes', M]], '摸要用手：feel with my hands。'),
    q('u1.talk', 1, '选词填空', 'I can （　） with my eyes.', 'see', [['hear', M], ['taste', M]], '眼睛用来看：I can see with my eyes.'),
    q('u1.talk', 1, '选词填空', 'I can （　） with my ears.', 'hear', [['see', M], ['smell', M]], '耳朵用来听：I can hear with my ears.'),
    q('u1.talk', 1, '选词填空', 'I can （　） with my nose.', 'smell', [['taste', M], ['see', M]], '鼻子用来闻：I can smell with my nose.'),
    q('u1.talk', 1, '选词填空', 'I can （　） with my mouth.', 'taste', [['hear', M], ['see', M]], '嘴巴用来尝：I can taste with my mouth.'),
    q('u1.talk', 1, '选词填空', 'I can （　） with my hands.', 'feel', [['hear', M], ['see', M]], '手用来摸：I can feel with my hands.'),
    q('u1.talk', 2, '选词填空', 'I （　） see with my eyes.', 'can', [['am', S], ['is', S]], '“我能……”说 I can…'),
    q('u1.talk', 2, '选词填空', 'I can see （　） my eyes.', 'with', [['and', S], ['is', S]], '“用眼睛”说 with my eyes，with 是“用”。'),
    q('u1.talk', 2, '选词填空', 'What can you （　）? I can see a map.', 'see', [['hear', S], ['smell', S]], '回答是 I can see…，问句也用 see。'),
    q('u1.talk', 1, '看中文选英文', '我能用眼睛看。', 'I can see with my eyes.', [['I can see with my ears.', M], ['I can hear with my eyes.', M]], '看是 see，眼睛是 eyes。'),
    q('u1.talk', 1, '看中文选英文', '我能用耳朵听。', 'I can hear with my ears.', [['I can hear with my eyes.', M], ['I can smell with my ears.', M]], '听是 hear，耳朵是 ears。'),
    q('u1.talk', 1, '看中文选英文', '我能用鼻子闻。', 'I can smell with my nose.', [['I can smell with my mouth.', M], ['I can taste with my nose.', M]], '闻是 smell，鼻子是 nose。'),
    q('u1.talk', 1, '看中文选英文', '我能用手摸。', 'I can feel with my hands.', [['I can feel with my ears.', M], ['I can see with my hands.', M]], '摸是 feel，手是 hands。'),
    q('u1.talk', 1, '看中文选英文', '你能听见什么？', 'What can you hear?', [['What can you see?', M], ['What can you smell?', M]], '听见是 hear：What can you hear?'),
    q('u1.talk', 1, '句子意思', 'I can taste with my mouth. 的意思是（　）', '我能用嘴巴尝。', [['我能用鼻子闻。', M], ['我能用眼睛看。', M]], 'taste 是尝，mouth 是嘴巴。'),
    q('u1.talk', 1, '句子意思', 'I can hear with my ears. 的意思是（　）', '我能用耳朵听。', [['我能用眼睛看。', M], ['我能用耳朵闻。', M]], 'hear 是听，ears 是耳朵。'),
    q('u1.talk', 1, '句子意思', 'What can you see? 的意思是（　）', '你能看见什么？', [['你能听见什么？', M], ['我能看见一只猫。', M]], 'What 是“什么”，see 是“看见”。'),
    q('u1.talk', 2, '补全对话', '— What can you see?\n— （　）', 'I can see a cat.', [['I can hear a cat.', S], ['I can see with my ears.', S]], '问“能看见什么”，就用 I can see… 回答。'),
    q('u1.talk', 2, '补全对话', '— What can you hear?\n— （　）', 'I can hear a cat.', [['I can see a cat.', S], ['I can hear with my eyes.', S]], '问“能听见什么”，就用 I can hear… 回答。'),
    q('u1.talk', 2, '补全对话', '— （　）\n— I can see a hat.', 'What can you see?', [['What can you hear?', S], ['What can you smell?', S]], '回答是 I can see…，问句是 What can you see?'),
    q('u1.talk', 2, '补全对话', '— （　）\n— I can smell with my nose.', 'What can you do with your nose?', [['What can you do with your eyes?', S], ['What can you do with your ears?', S]], '回答说的是鼻子，问句就问 with your nose。'),
    q('u1.talk', 2, '补全对话', '— What can you do with your ears?\n— （　）', 'I can hear with my ears.', [['I can see with my eyes.', S], ['I can hear with my eyes.', M]], '问耳朵能做什么，回答 I can hear with my ears.'),
    q('u1.talk', 1, '情景交际', '你想问朋友“你能看见什么？”，你说（　）', 'What can you see?', [['What can you hear?', M], ['I can see.', S]], '问“能看见什么”说 What can you see?'),
    q('u1.talk', 2, '情景交际', '朋友问你 “What can you hear?”，你听见了猫叫，你回答（　）', 'I can hear a cat.', [['I can see a cat.', S], ['I can hear a hat.', M]], '听见猫叫，说 I can hear a cat.'),
    q('u1.talk', 2, '句型选择', '哪一句说的是用耳朵？', 'I can hear.', [['I can see.', M], ['I can taste.', M]], '耳朵用来听：hear。'),
    q('u1.talk', 2, '句型选择', '哪一句说的是用手？', 'I can feel.', [['I can smell.', M], ['I can see.', M]], '手用来摸：feel。'),
    q('u1.talk', 2, '连词成句', '把单词排成正确的句子：can / I / see / .', 'I can see.', [['Can I see.', S], ['I see can.', S]], '顺序是“I + can + 动作”：I can see.'),
    q('u1.talk', 3, '连词成句', '把单词排成正确的句子：with / I / hear / can / my / ears / .', 'I can hear with my ears.', [['I hear can with my ears.', S], ['I can hear my ears with.', S]], '先说 I can hear，再说 with my ears。'),
    q('u1.talk', 3, '选出正确的句子', '选出书写正确的句子：我能用眼睛看。', 'I can see with my eyes.', [['i can see with my eyes.', S], ['I can see with my eyes', S], ['I can sees with my eyes.', S]], 'I 永远大写，句末有句号，can 后面的 see 不加 s。'),
    // 拔高
    q('u1.talk', 3, '找错句', '下面哪一句说错了？', 'I can hear with my eyes.', [['I can see with my eyes.', S], ['I can smell with my nose.', S]], '耳朵才能听：I can hear with my ears.', 'stretch'),
    q('u1.talk', 3, '补全对话', '— （　）\n— I can hear a cat.', 'What can you hear?', [['What can you see?', S], ['What can you do with your eyes?', S]], '回答说 I can hear…，问句用 What can you hear?', 'stretch'),
    q('u1.talk', 3, '看中文选英文', '我能用眼睛看，也能用耳朵听。', 'I can see with my eyes. I can hear with my ears.', [['I can see with my ears. I can hear with my eyes.', M], ['I can see with my eyes. I can smell with my ears.', M]], '看 see 配 eyes，听 hear 配 ears。', 'stretch'),
    q('u1.talk', 3, '对话排序', '给对话排序：\n① I can see a cat.\n② What can you see?\n③ What can you hear?\n④ I can hear a cat.', '②①③④', [['①②④③', S], ['②④③①', S]], '先问 What can you see? 再答 I can see…；再问 What can you hear? 再答 I can hear…', 'stretch'),
    q('u1.talk', 3, '句型选择', '哪一组两句都说对了？', 'I can see with my eyes. I can feel with my hands.', [['I can see with my eyes. I can feel with my ears.', M], ['I can taste with my nose. I can hear with my ears.', M]], '看用眼睛，摸用手；尝要用嘴巴，不是鼻子。', 'stretch'),
    q('u1.talk', 3, '补全对话', '— What can you do with your mouth?\n— I can （　） with my mouth.', 'taste', [['smell', M], ['hear', M]], '嘴巴能尝：I can taste with my mouth.', 'stretch'),
    // 创新
    q('u1.talk', 2, '读一读', 'Look! A magic show! I can see a cat. I can see a hat.\n魔术表演上能看见什么？', '一只猫和一顶帽子', [['一只猫和一张地图', M], ['一只蝙蝠和一顶帽子', M]], 'I can see a cat. I can see a hat. 看见了猫和帽子。', 'creative'),
    q('u1.talk', 2, '读一读', 'Kitty: What can you hear, Sam?\nSam: I can hear a cat.\nSam 听见了什么？', '猫', [['帽子', M], ['地图', M]], 'Sam 说 I can hear a cat.，他听见了猫。', 'creative'),
    q('u1.talk', 2, '情景交际', '玩“蒙眼猜东西”游戏：眼睛看不见了，你告诉朋友你还能用手摸，你说（　）', 'I can feel with my hands.', [['I can see with my eyes.', M], ['I can feel with my ears.', M]], '用手摸：I can feel with my hands.', 'creative'),
    q('u1.talk', 2, '看图说话', '图上：一个小朋友把鼻子凑到花旁边。选出和图意相符的句子', 'I can smell with my nose.', [['I can taste with my mouth.', M], ['I can hear with my ears.', M]], '用鼻子闻花：I can smell with my nose.', 'creative'),

    // ================================================================ Unit 2
    // ------------------------------------------------------ u2.words
    rhyme('u2.words', 1, 'fan', 'man', 'ham', 'jam', '-an'),
    rhyme('u2.words', 1, 'ham', 'jam', 'pan', 'van', '-am'),
    family('u2.words', 1, '-an', 'van', 'jam', 'ham'),
    family('u2.words', 1, '-am', 'ham', 'pan', 'fan'),
    blend('u2.words', 1, 'p', 'an', 'pan', 'fan', 'ham'),
    blend('u2.words', 1, 'j', 'am', 'jam', 'ham', 'van'),
    swap('u2.words', 2, 'fan', 'f', 'v', 'van', 'man', 'jam'),
    swap('u2.words', 2, 'ham', 'h', 'j', 'jam', 'pan', 'man'),
    odd('u2.words', 2, 'fan / man / ham', 'ham', 'fan', 'man', 'fan、man 结尾是 -an，ham 结尾是 -am。'),
    odd('u2.words', 2, 'jam / ham / pan', 'pan', 'jam', 'ham', 'jam、ham 结尾是 -am，pan 结尾是 -an。'),
    q('u2.words', 1, '配对词', 'old（年老的）和哪个词意思正好相反？', 'young', [['cute', M], ['uncle', M]], 'old 年老的，young 年轻的，意思相反。'),
    q('u2.words', 1, '配对词', 'young（年轻的）和哪个词意思正好相反？', 'old', [['cute', M], ['aunt', M]], 'young 年轻的，old 年老的，意思相反。'),
    q('u2.words', 1, '选词填空', '爸爸的弟弟是我的（　）', 'uncle', [['aunt', M], ['cousin', M]], '叔叔、舅舅都是 uncle。'),
    q('u2.words', 1, '选词填空', '妈妈的妹妹是我的（　）', 'aunt', [['uncle', M], ['cousin', M]], '阿姨、姑姑都是 aunt。'),
    q('u2.words', 1, '选词填空', '叔叔的女儿是我的（　）', 'cousin', [['aunt', M], ['uncle', M]], '叔叔、阿姨家的孩子是 cousin（堂、表兄弟姐妹）。'),
    q('u2.words', 1, '选词填空', '小表妹笑起来真可爱，她很（　）', 'cute', [['old', M], ['uncle', M]], 'cute 是“可爱的”。'),
    q('u2.words', 2, '补全单词', '选字母补全单词：unc（　）e（叔叔）', 'l', [['k', P], ['r', P]], '叔叔 uncle 拼作 u-n-c-l-e。'),
    q('u2.words', 2, '补全单词', '选字母补全单词：v（　）n（面包车）', 'a', [['e', P], ['o', P]], '面包车 van 拼作 v-a-n。'),
    q('u2.words', 2, '补全单词', '选字母补全单词：y（　）ung（年轻的）', 'o', [['u', P], ['a', P]], '年轻的 young 拼作 y-o-u-n-g。'),
    q('u2.words', 2, '找不同', '下面哪个词不是说家人的？', 'cute', [['uncle', M], ['aunt', M]], 'uncle、aunt 是家人，cute 是“可爱的”。'),
    // 拔高
    q('u2.words', 3, '拼读', '哪一组单词的结尾音都一样？（-am / -an）', 'fan, man, van', [['fan, ham, pan', P], ['jam, man, ham', P]], 'fan、man、van 都在 -an 家族。', 'stretch'),
    q('u2.words', 3, '拼读', 'ham 变成 jam，变的是哪个字母？', '第一个字母', [['中间的字母', P], ['最后一个字母', P]], 'ham 和 jam 只有开头的 h、j 不同。', 'stretch'),
    q('u2.words', 3, '拼读', '把 man 最后的 n 换成 p，变成（　）', 'map', [['mat', P], ['man', P]], 'man 换掉结尾 n，变成 map（地图）。', 'stretch'),
    q('u2.words', 3, '拼读', '哪个单词和 fan 押韵，又能在厨房里找到？', 'pan', [['jam', P], ['van', M]], 'pan（平底锅）在厨房里，和 fan 都在 -an 家族；jam 结尾是 -am。', 'stretch'),
    q('u2.words', 3, '词义辨析', 'old 和 young 说的是人的（　）', '年纪', [['个子', M], ['长相', M]], 'old 年老的，young 年轻的，说的都是年纪。', 'stretch'),
    q('u2.words', 3, '配对词', '哪一组是一对意思相反的词？', 'old, young', [['old, cute', M], ['uncle, cousin', M]], 'old 和 young 意思相反。', 'stretch'),
    // 创新
    q('u2.words', 2, '读一读', "This is Uncle Bob. He's young. He's a man.\nUncle Bob 怎么样？", '年轻', [['年纪大', M], ['是个女的', M]], "He's young. 说明 Uncle Bob 很年轻。", 'creative'),
    q('u2.words', 2, '猜一猜', '猜一猜：甜甜的，涂在面包上，和 ham 押韵，是（　）', 'jam', [['ham', M], ['pan', P]], 'jam（果酱）甜甜的，和 ham 都在 -am 家族。', 'creative'),
    q('u2.words', 3, '看图说话', '图上：夏天，一个男人坐在面包车里扇扇子。选出正确的一组词', 'man, van, fan', [['man, pan, fan', M], ['ham, van, fan', M]], '男人 man，面包车 van，扇子 fan。', 'creative'),
    q('u2.words', 2, '情景交际', '奶奶今年 80 岁了，你说：Grandma is （　）.', 'old', [['young', M], ['cute', M]], '80 岁年纪大，说 old。', 'creative'),

    // ------------------------------------------------------ u2.talk
    q('u2.talk', 1, '选词填空', "This is my uncle. （　） old.", "He's", [["She's", S], ["I'm", S]], "uncle 是男的，说他用 He's。"),
    q('u2.talk', 1, '选词填空', "This is my aunt. （　） young.", "She's", [["He's", S], ["I'm", S]], "aunt 是女的，说她用 She's。"),
    q('u2.talk', 1, '选词填空', "This is my cousin Kitty. （　） cute.", "She's", [["He's", S], ['Is', S]], "Kitty 是女孩，说她用 She's。"),
    q('u2.talk', 1, '选词填空', "This is my cousin Tom. （　） cute.", "He's", [["She's", S], ['Is', S]], "Tom 是男孩，说他用 He's。"),
    q('u2.talk', 1, '选词填空', "This is my （　）. He's young.（爸爸的弟弟）", 'uncle', [['aunt', M], ['cousin', M]], '爸爸的弟弟是 uncle。'),
    q('u2.talk', 1, '选词填空', "This is my （　）. She's young.（妈妈的妹妹）", 'aunt', [['uncle', M], ['cousin', M]], '妈妈的妹妹是 aunt。'),
    q('u2.talk', 1, '选词填空', 'This is （　） cousin.', 'my', [['I', S], ["I'm", S]], '“我的”是 my：This is my cousin.'),
    q('u2.talk', 2, '选词填空', "（　） she? She's my cousin.", "Who's", [["What's", S], ['This', S]], "问“她是谁”用 Who's she?"),
    q('u2.talk', 2, '选词填空', "I like my aunt. She's （　）.（阿姨很年轻）", 'young', [['old', M], ['uncle', M]], '年轻是 young。'),
    q('u2.talk', 2, '选词填空', "This is my grandma. She's （　）.（奶奶 80 岁了）", 'old', [['young', M], ['cute', M]], '80 岁年纪大，说 old。'),
    q('u2.talk', 1, '看中文选英文', '这是我的叔叔。', 'This is my uncle.', [['This is my aunt.', M], ['This my uncle.', S]], '介绍家人说 This is my…，叔叔是 uncle。'),
    q('u2.talk', 1, '看中文选英文', '他年纪大了。', "He's old.", [["He's young.", M], ["She's old.", M]], "他是 He's，年纪大是 old。"),
    q('u2.talk', 1, '看中文选英文', '她很年轻。', "She's young.", [["He's young.", M], ["She's old.", M]], "她是 She's，年轻是 young。"),
    q('u2.talk', 2, '看中文选英文', '这是我的表妹，她很可爱。', "This is my cousin. She's cute.", [["This is my cousin. He's cute.", M], ["This is my aunt. She's cute.", M]], "表妹是 cousin，女孩用 She's，可爱是 cute。"),
    q('u2.talk', 1, '句子意思', "He's old. 的意思是（　）", '他年纪大了。', [['她年纪大了。', M], ['他很年轻。', M]], "He's 是“他是”，old 是“年老的”。"),
    q('u2.talk', 1, '句子意思', 'This is my aunt. 的意思是（　）', '这是我的阿姨。', [['这是我的叔叔。', M], ['这是我的表姐。', M]], 'aunt 是阿姨、姑姑。'),
    q('u2.talk', 1, '句子意思', "Who's she? 的意思是（　）", '她是谁？', [['他是谁？', M], ['她怎么样？', M]], "Who's 是“谁是”，she 是“她”。"),
    q('u2.talk', 1, '句子意思', "She's cute. 的意思是（　）", '她很可爱。', [['他很可爱。', M], ['她很年轻。', M]], "She's 是“她是”，cute 是“可爱的”。"),
    q('u2.talk', 1, '句子意思', 'I like my uncle. 的意思是（　）', '我喜欢我的叔叔。', [['我喜欢我的阿姨。', M], ['这是我的叔叔。', M]], 'I like 是“我喜欢”，uncle 是叔叔。'),
    q('u2.talk', 2, '补全对话', "— Who's he?\n— （　）", "He's my uncle.", [["She's my aunt.", S], ["I'm Sam.", S]], "问 Who's he?，用 He's my… 回答。"),
    q('u2.talk', 2, '补全对话', "— Who's she?\n— （　）", "She's my aunt.", [["He's my uncle.", S], ["She's old.", S]], "问她是谁，要说出她是家里的谁：She's my aunt."),
    q('u2.talk', 2, '补全对话', "— （　）\n— He's my cousin.", "Who's he?", [["Who's she?", S], ['This is my cousin.', S]], "回答用 He's，问句是 Who's he?"),
    q('u2.talk', 1, '情景交际', '你向朋友介绍你的阿姨，你说（　）', 'This is my aunt.', [['This is my uncle.', M], ["She's my uncle.", M]], '介绍阿姨说 This is my aunt.'),
    q('u2.talk', 1, '情景交际', '你想问朋友“她是谁？”，你说（　）', "Who's she?", [["Who's he?", M], ["She's my aunt.", S]], "问她是谁说 Who's she?"),
    q('u2.talk', 1, '情景交际', '你想夸小表妹很可爱，你说（　）', "She's cute.", [["She's old.", M], ["He's cute.", S]], "表妹是女孩用 She's，可爱是 cute。"),
    q('u2.talk', 2, '情景交际', '你想告诉朋友你的舅舅很年轻，你说（　）', 'My uncle is young.', [['My uncle is old.', M], ['My aunt is young.', M]], '舅舅是 uncle，年轻是 young。'),
    q('u2.talk', 2, '连词成句', '把单词排成正确的句子：is / my / this / aunt / .', 'This is my aunt.', [['This my is aunt.', S], ['My aunt this is.', S]], '介绍家人：This is my aunt.'),
    q('u2.talk', 2, '连词成句', '把单词排成正确的句子：uncle / my / is / old / .', 'My uncle is old.', [['My old is uncle.', S], ['Uncle my is old.', S]], '先说谁（My uncle），再说 is old。'),
    q('u2.talk', 3, '选出正确的句子', '选出书写正确的句子：他是我的叔叔。', "He's my uncle.", [["he's my uncle.", S], ['Hes my uncle.', S], ["He's my uncle", S]], "句首大写，He's 中间有一撇，句末有句号。"),
    q('u2.talk', 2, '句型选择', '哪一句说的是一个男的？', "He's my uncle.", [["She's my aunt.", M], ["She's my cousin.", M]], "he 说男的，she 说女的。"),
    q('u2.talk', 2, '句型选择', '哪一句是在问“他是谁”？', "Who's he?", [["Who's she?", M], ["He's my uncle.", S]], "Who's he? 是“他是谁？”"),
    // 拔高
    q('u2.talk', 3, '找错句', '（Uncle Bob 是男的）下面哪一句说错了？', "She's my uncle.", [['This is Uncle Bob.', S], ["He's my uncle.", S]], "uncle 是男的，要说 He's my uncle.", 'stretch'),
    q('u2.talk', 3, '补全对话', "— （　）\n— She's my aunt. She's young.", "Who's she?", [["Who's he?", S], ['This is my aunt.', S]], "回答用 She's，问句是 Who's she?", 'stretch'),
    q('u2.talk', 3, '看中文选英文', '这是我的舅舅，他很年轻。', "This is my uncle. He's young.", [["This is my uncle. She's young.", S], ["This is my aunt. He's young.", M]], "舅舅是 uncle，男的用 He's，年轻是 young。", 'stretch'),
    q('u2.talk', 3, '对话排序', "给对话排序：\n① She's my cousin.\n② Who's she?\n③ She's cute.", '②①③', [['①②③', S], ['③①②', S]], "先问 Who's she?，再答 She's my cousin.，最后说她很可爱。", 'stretch'),
    q('u2.talk', 3, '选词填空', 'Uncle Bob 20 岁，Grandma 80 岁。Uncle Bob is （　）. Grandma is （　）.', 'young / old', [['old / young', M], ['cute / young', M]], '20 岁年轻 young，80 岁年纪大 old。', 'stretch'),
    q('u2.talk', 3, '补全对话', "— Who's he?\n— He's my uncle. （　）（叔叔 25 岁）", "He's young.", [["He's old.", M], ["She's young.", S]], "叔叔 25 岁，很年轻：He's young.", 'stretch'),
    // 创新
    q('u2.talk', 2, '读一读', "At Uncle Bob's party.\nThis is Uncle Bob. He's young. This is Grandma. She's old.\n谁年纪大？", 'Grandma', [['Uncle Bob', M], ['一样大', M]], "Grandma 那句说 She's old.，奶奶年纪大。", 'creative'),
    q('u2.talk', 2, '读一读', "Kitty: Who's he?\nSam: He's my cousin. He's cute.\nSam 在介绍谁？", '他的表弟', [['他的叔叔', M], ['他的阿姨', M]], "He's my cousin. 说的是 Sam 的表弟（cousin）。", 'creative'),
    q('u2.talk', 3, '情景交际', '在 Uncle Bob 的派对上，朋友问你旁边的阿姨是谁，她是妈妈的妹妹。你回答（　）', "She's my aunt.", [["He's my uncle.", M], ["She's my cousin.", M]], "妈妈的妹妹是 aunt，女的用 She's。", 'creative'),
    q('u2.talk', 3, '情景交际', '你给同学看全家福，介绍叔叔：他是你的叔叔，年纪大了。你说（　）', "This is my uncle. He's old.", [["This is my uncle. He's young.", M], ["This is my aunt. She's old.", M]], "介绍用 This is my uncle.，年纪大是 He's old.", 'creative'),

    // ================================================================ Unit 3
    // ------------------------------------------------------ u3.words
    rhyme('u3.words', 1, 'bed', 'red', 'net', 'pet', '-ed'),
    rhyme('u3.words', 1, 'net', 'pet', 'bed', 'red', '-et'),
    family('u3.words', 1, '-et', 'wet', 'bed', 'red'),
    family('u3.words', 1, '-ed', 'bed', 'net', 'wet'),
    blend('u3.words', 1, 'b', 'ed', 'bed', 'red', 'net'),
    blend('u3.words', 1, 'p', 'et', 'pet', 'wet', 'bed'),
    swap('u3.words', 2, 'net', 'n', 'w', 'wet', 'pet', 'red'),
    swap('u3.words', 2, 'bed', 'b', 'r', 'red', 'net', 'wet'),
    odd('u3.words', 2, 'bed / red / net', 'net', 'bed', 'red', 'bed、red 结尾是 -ed，net 结尾是 -et。'),
    odd('u3.words', 2, 'pet / wet / red', 'red', 'pet', 'wet', 'pet、wet 结尾是 -et，red 结尾是 -ed。'),
    q('u3.words', 1, '选词填空', '会走路、会说话的铁皮玩具是（　）', 'robot', [['doll', M], ['ball', M]], 'robot 是机器人。'),
    q('u3.words', 1, '选词填空', '穿着漂亮裙子的布娃娃是（　）', 'doll', [['robot', M], ['ball', M]], 'doll 是洋娃娃。'),
    q('u3.words', 1, '选词填空', '圆圆的，能拍能踢的玩具是（　）', 'ball', [['doll', M], ['robot', M]], 'ball 是球。'),
    q('u3.words', 1, '选词填空', '很多小块拼成一幅画的玩具是（　）', 'jigsaw puzzle', [['toy plane', M], ['toy bear', M]], 'jigsaw puzzle 是拼图。'),
    q('u3.words', 1, '选词填空', '毛茸茸、可以抱着睡觉的玩具熊是（　）', 'toy bear', [['toy plane', M], ['robot', M]], 'toy bear 是玩具熊。'),
    q('u3.words', 1, '选词填空', '有翅膀、能“飞”的玩具是（　）', 'toy plane', [['toy bear', M], ['ball', M]], 'toy plane 是玩具飞机。'),
    q('u3.words', 2, '补全单词', '选字母补全单词：r（　）bot（机器人）', 'o', [['a', P], ['e', P]], '机器人 robot 拼作 r-o-b-o-t。'),
    q('u3.words', 2, '补全单词', '选字母补全单词：d（　）ll（洋娃娃）', 'o', [['a', P], ['y', P]], '洋娃娃 doll 拼作 d-o-l-l。'),
    q('u3.words', 2, '补全单词', '选字母补全单词：ba（　）l（球）', 'l', [['d', P], ['r', P]], '球 ball 拼作 b-a-l-l，有两个 l。'),
    q('u3.words', 2, '找不同', '下面哪个不是玩具？', 'bed', [['doll', M], ['ball', M]], 'doll、ball 是玩具，bed 是床。'),
    // 拔高
    q('u3.words', 3, '拼读', '哪一组单词的结尾音都一样？（-ed / -et）', 'net, pet, wet', [['bed, net, red', P], ['pet, red, wet', P]], 'net、pet、wet 都在 -et 家族。', 'stretch'),
    q('u3.words', 3, '拼读', '把 pet 最后的 t 换成 n，变成（　）', 'pen', [['pet', P], ['net', P]], 'pet 换掉结尾 t，变成 pen（钢笔）。', 'stretch'),
    q('u3.words', 3, '拼读', '哪个单词和 net 押韵，又是可以养的小动物？', 'pet', [['cat', P], ['wet', M]], 'pet（宠物）和 net 都在 -et 家族；cat 是 -at 家族。', 'stretch'),
    q('u3.words', 3, '词义辨析', 'toy plane 和 toy bear 里都有 toy，toy 的意思是（　）', '玩具', [['飞机', M], ['熊', M]], 'toy 是玩具：toy plane 玩具飞机，toy bear 玩具熊。', 'stretch'),
    q('u3.words', 3, '找不同', '哪个词和另外两个不是一类？（doll / robot / red）', 'red', [['doll', M], ['robot', M]], 'doll、robot 是玩具，red 是“红色的”。', 'stretch'),
    q('u3.words', 3, '补全单词', '两个词都要补对：r（　）d 红色的、w（　）t 湿的', 'e, e', [['a, e', P], ['e, a', P]], 'red 和 wet 中间都是字母 e。', 'stretch'),
    // 创新
    q('u3.words', 2, '读一读', 'My ball is red. It is on the bed.\n球是什么颜色？在哪里？', '红色，在床上', [['红色，在网里', M], ['蓝色，在床上', M]], 'red 是红色，on the bed 是“在床上”。', 'creative'),
    q('u3.words', 2, '猜一猜', '猜一猜：和 bed 押韵，是一种颜色（　）', 'red', [['wet', M], ['net', P]], 'red（红色的）和 bed 都在 -ed 家族。', 'creative'),
    q('u3.words', 3, '看图说话', '图上：小狗宠物全身湿漉漉的，趴在床上。选出正确的一组词', 'pet, wet, bed', [['pet, red, bed', M], ['net, wet, bed', M]], '宠物 pet，湿的 wet，床 bed。', 'creative'),
    q('u3.words', 2, '情景交际', '在玩具店里，你想找一盒能拼成一幅画的玩具，你要找（　）', 'jigsaw puzzle', [['toy plane', M], ['robot', M]], '拼成画的玩具是 jigsaw puzzle（拼图）。', 'creative'),

    // ------------------------------------------------------ u3.talk
    q('u3.talk', 1, '选词填空', "What's your （　） toy?", 'favourite', [['like', S], ['my', S]], "“最喜欢的玩具”是 favourite toy。"),
    q('u3.talk', 1, '选词填空', 'My favourite （　） is my doll.', 'toy', [['ball', M], ['bed', M]], '“我最喜欢的玩具”是 My favourite toy。'),
    q('u3.talk', 1, '选词填空', '（　） your favourite toy?', "What's", [["Who's", S], ["It's", S]], "问“是什么”用 What's。"),
    q('u3.talk', 2, '选词填空', '（　） it a robot? Yes, it is.', 'Is', [['It', S], ["What's", S]], "问“它是……吗？”用 Is it…?"),
    q('u3.talk', 2, '选词填空', "It's a doll. I like （　） doll.", 'my', [['I', S], ["It's", S]], '“我的洋娃娃”是 my doll。'),
    q('u3.talk', 2, '选词填空', 'My favourite toy （　） my robot.', 'is', [['am', S], ['are', S]], 'My favourite toy is… 用 is。'),
    q('u3.talk', 2, '补全对话', "— What's your favourite toy?\n— （　）", 'My favourite toy is my robot.', [['Yes, it is.', S], ["I'm a robot.", S]], '问最喜欢的玩具，回答 My favourite toy is…'),
    q('u3.talk', 2, '补全对话', '— （　）\n— My favourite toy is my toy bear.', "What's your favourite toy?", [['Is it a toy bear?', S], ["Who's he?", S]], "回答说最喜欢的玩具，问句是 What's your favourite toy?"),
    q('u3.talk', 1, '补全对话', '— Is it a ball?\n— Yes, （　）.', 'it is', [["it isn't", S], ['I am', S]], '用 Yes 回答 Is it…?，说 Yes, it is.'),
    q('u3.talk', 1, '补全对话', '— Is it a doll?\n— No, （　）.', "it isn't", [['it is', S], ["it's", S]], "用 No 回答 Is it…?，说 No, it isn't."),
    q('u3.talk', 2, '补全对话', "— Is it a robot?\n— （　） It's a doll.", "No, it isn't.", [['Yes, it is.', S], ["Yes, it isn't.", S]], "后面说 It's a doll.，说明不是机器人：No, it isn't."),
    q('u3.talk', 2, '补全对话', "— What's your favourite toy, Kitty?\n— My favourite toy is my （　）.（Kitty 抱着洋娃娃）", 'doll', [['robot', M], ['bed', M]], 'Kitty 抱着洋娃娃，doll 是洋娃娃。'),
    q('u3.talk', 1, '看中文选英文', '你最喜欢的玩具是什么？', "What's your favourite toy?", [["What's your toy?", M], ['Is it your favourite toy?', M]], "“最喜欢的玩具”是 favourite toy，问“是什么”用 What's。"),
    q('u3.talk', 1, '看中文选英文', '我最喜欢的玩具是我的洋娃娃。', 'My favourite toy is my doll.', [['My favourite toy is my ball.', M], ['My favourite doll is my toy.', S]], 'My favourite toy is… 后面接玩具名 my doll。'),
    q('u3.talk', 1, '看中文选英文', '它是一个球吗？', 'Is it a ball?', [["It's a ball.", S], ['Is it a doll?', M]], '问“它是……吗？”用 Is it a…?'),
    q('u3.talk', 1, '看中文选英文', '是的，它是。', 'Yes, it is.', [["No, it isn't.", M], ["Yes, it isn't.", S]], '肯定回答：Yes, it is.'),
    q('u3.talk', 1, '看中文选英文', '我喜欢我的球。', 'I like my ball.', [['I like my doll.', M], ["I'm my ball.", S]], '我喜欢是 I like，球是 ball。'),
    q('u3.talk', 1, '句子意思', 'My favourite toy is my toy plane. 的意思是（　）', '我最喜欢的玩具是我的玩具飞机。', [['我最喜欢的玩具是我的玩具熊。', M], ['我有一架飞机。', M]], 'favourite toy 是“最喜欢的玩具”，toy plane 是玩具飞机。'),
    q('u3.talk', 1, '句子意思', "No, it isn't. 的意思是（　）", '不，它不是。', [['是的，它是。', M], ['不，我不是。', M]], "No 是“不”，it isn't 是“它不是”。"),
    q('u3.talk', 1, '句子意思', 'I like my jigsaw puzzle. 的意思是（　）', '我喜欢我的拼图。', [['我喜欢我的机器人。', M], ['这是我的拼图。', M]], 'I like 是“我喜欢”，jigsaw puzzle 是拼图。'),
    q('u3.talk', 1, '句子意思', "What's your favourite toy? 的意思是（　）", '你最喜欢的玩具是什么？', [['你有什么玩具？', M], ['这是你的玩具吗？', M]], 'favourite 是“最喜欢的”。'),
    q('u3.talk', 1, '情景交际', '你想问同学最喜欢什么玩具，你说（　）', "What's your favourite toy?", [['Is it a toy?', M], ['My favourite toy is my ball.', S]], "问最喜欢的玩具：What's your favourite toy?"),
    q('u3.talk', 1, '情景交际', '朋友问你最喜欢的玩具，你最喜欢玩具熊，你回答（　）', 'My favourite toy is my toy bear.', [['My favourite toy is my toy plane.', M], ['Is it a toy bear?', S]], '玩具熊是 toy bear。'),
    q('u3.talk', 2, '情景交际', '玩“猜玩具”游戏，你猜盒子里是一个机器人，你问（　）', 'Is it a robot?', [["What's a robot?", S], ['Is it a doll?', M]], '猜“它是……吗？”用 Is it a…?'),
    q('u3.talk', 2, '情景交际', '玩“猜玩具”游戏，朋友猜对了，你说（　）', 'Yes, it is.', [["No, it isn't.", M], ['Yes, I am.', S]], '猜对了说 Yes, it is.'),
    q('u3.talk', 2, '情景交际', '玩“猜玩具”游戏，朋友猜错了，你说（　）', "No, it isn't.", [['Yes, it is.', M], ['No, it is.', S]], "猜错了说 No, it isn't."),
    q('u3.talk', 2, '连词成句', "把单词排成正确的句子：your / what's / toy / favourite / ?", "What's your favourite toy?", [["What's favourite your toy?", S], ["Your favourite toy what's?", S]], "What's 放最前面，your favourite toy 连在一起。"),
    q('u3.talk', 2, '连词成句', '把单词排成正确的句子：it / is / a / ball / ?', 'Is it a ball?', [['Is a it ball?', S], ['Ball is it a?', S]], '问句把 Is 放在最前面：Is it a ball?'),
    q('u3.talk', 3, '选出正确的句子', '选出书写正确的句子：我最喜欢的玩具是我的机器人。', 'My favourite toy is my robot.', [['my favourite toy is my robot.', S], ['My favourite toy is my robot', S], ['My favourite toy my robot.', S]], '句首大写，句末有句号，中间的 is 不能漏。'),
    q('u3.talk', 2, '句型选择', '哪一句是在问问题？', 'Is it a doll?', [["It's a doll.", S], ['I like my doll.', S]], '问句开头是 Is，末尾有问号。'),
    q('u3.talk', 2, '句型选择', '哪一句是在说自己最喜欢的玩具？', 'My favourite toy is my ball.', [["What's your favourite toy?", S], ['Is it a ball?', S]], 'My favourite toy is… 是说自己最喜欢的玩具。'),
    // 拔高
    q('u3.talk', 3, '找错句', '下面哪一组问答是错的？', "— Is it a ball? — Yes, it isn't.", [['— Is it a ball? — Yes, it is.', S], ["— Is it a doll? — No, it isn't.", S]], "Yes 后面接 it is，No 后面接 it isn't。", 'stretch'),
    q('u3.talk', 3, '补全对话', "— （　）\n— No, it isn't. It's a toy bear.", 'Is it a doll?', [["What's your favourite toy?", S], ['Is it a toy bear?', S]], "回答说“不是，是玩具熊”，所以问的是别的玩具：Is it a doll?", 'stretch'),
    q('u3.talk', 3, '看中文选英文', '它不是洋娃娃，它是一个机器人。', "It isn't a doll. It's a robot.", [["It's a doll. It isn't a robot.", M], ["It isn't a robot. It's a doll.", M]], "不是用 It isn't，是用 It's。", 'stretch'),
    q('u3.talk', 3, '对话排序', "给对话排序：\n① No, it isn't.\n② Is it a ball?\n③ Is it a robot?\n④ Yes, it is.", '②①③④', [['①②④③', S], ['④③①②', S]], '每问一句 Is it…?，后面紧跟回答。', 'stretch'),
    q('u3.talk', 3, '选词填空', 'Kitty 最喜欢玩具熊，Sam 最喜欢机器人。Sam 说：My favourite toy is my （　）.', 'robot', [['toy bear', M], ['doll', M]], 'Sam 最喜欢机器人：robot。', 'stretch'),
    q('u3.talk', 3, '句型选择', "哪一句能回答 What's your favourite toy?", 'My favourite toy is my ball.', [['Yes, it is.', S], ['Is it a ball?', S]], '问最喜欢的玩具，要说出玩具：My favourite toy is…', 'stretch'),
    // 创新
    q('u3.talk', 2, '读一读', "Kitty: What's your favourite toy, Sam?\nSam: My favourite toy is my robot. It's red.\nSam 最喜欢的玩具是什么颜色？", '红色', [['蓝色', M], ['黄色', M]], "It's red. 说明机器人是红色的。", 'creative'),
    q('u3.talk', 2, '读一读', "A: Is it a doll?\nB: No, it isn't.\nA: Is it a ball?\nB: Yes, it is.\n盒子里是什么？", '球', [['洋娃娃', M], ['机器人', M]], "问 ball 时回答 Yes, it is.，所以是球。", 'creative'),
    q('u3.talk', 2, '情景交际', '在玩具店，你看到一个会动的机器人，非常喜欢。你对妈妈说（　）', 'I like the robot.', [['I like the doll.', M], ['Is it a doll?', S]], '喜欢机器人：I like the robot.', 'creative'),
    q('u3.talk', 3, '情景交际', '你给新朋友介绍自己最喜欢的玩具——拼图，你说（　）', 'My favourite toy is my jigsaw puzzle.', [['My favourite toy is my toy plane.', M], ["What's your favourite toy?", S]], '拼图是 jigsaw puzzle。', 'creative'),

    // ================================================================ Unit 4
    // ------------------------------------------------------ u4.words
    rhyme('u4.words', 1, 'hen', 'pen', 'big', 'dig', '-en'),
    rhyme('u4.words', 1, 'big', 'dig', 'ten', 'hen', '-ig'),
    family('u4.words', 1, '-en', 'ten', 'wig', 'dig'),
    family('u4.words', 1, '-ig', 'wig', 'pen', 'hen'),
    blend('u4.words', 1, 't', 'en', 'ten', 'hen', 'big'),
    blend('u4.words', 1, 'd', 'ig', 'dig', 'wig', 'pen'),
    swap('u4.words', 2, 'hen', 'h', 'p', 'pen', 'ten', 'big'),
    swap('u4.words', 2, 'big', 'b', 'w', 'wig', 'dig', 'ten'),
    odd('u4.words', 2, 'hen / pen / big', 'big', 'hen', 'pen', 'hen、pen 结尾是 -en，big 结尾是 -ig。'),
    odd('u4.words', 2, 'dig / wig / ten', 'ten', 'dig', 'wig', 'dig、wig 结尾是 -ig，ten 结尾是 -en。'),
    q('u4.words', 1, '选词填空', '想看电影，去（　）', 'cinema', [['zoo', M], ['park', M]], 'cinema 是电影院。'),
    q('u4.words', 1, '选词填空', '想看大熊猫和老虎，去（　）', 'zoo', [['cinema', M], ['toy shop', M]], 'zoo 是动物园。'),
    q('u4.words', 1, '选词填空', '想买荔枝和香蕉，去（　）', 'fruit shop', [['pet shop', M], ['toy shop', M]], 'fruit shop 是水果店。'),
    q('u4.words', 1, '选词填空', '想买一只小猫当宠物，去（　）', 'pet shop', [['fruit shop', M], ['cinema', M]], 'pet shop 是宠物店。'),
    q('u4.words', 1, '选词填空', '想买机器人和洋娃娃，去（　）', 'toy shop', [['fruit shop', M], ['zoo', M]], 'toy shop 是玩具店。'),
    q('u4.words', 1, '选词填空', '想在草地上散步、放风筝，去（　）', 'park', [['cinema', M], ['pet shop', M]], 'park 是公园。'),
    q('u4.words', 2, '补全单词', '选字母补全单词：c（　）nema（电影院）', 'i', [['e', P], ['a', P]], '电影院 cinema 拼作 c-i-n-e-m-a。'),
    q('u4.words', 2, '补全单词', '选字母补全单词：p（　）rk（公园）', 'a', [['u', P], ['i', P]], '公园 park 拼作 p-a-r-k。'),
    // 拔高
    q('u4.words', 3, '词义辨析', 'pet shop、fruit shop、toy shop 里都有 shop，shop 的意思是（　）', '商店', [['宠物', M], ['玩具', M]], 'shop 是商店：宠物店、水果店、玩具店。', 'stretch'),
    q('u4.words', 3, '拼读', '哪一组单词的结尾音都一样？（-en / -ig）', 'hen, pen, ten', [['hen, big, ten', P], ['dig, wig, pen', P]], 'hen、pen、ten 都在 -en 家族。', 'stretch'),
    q('u4.words', 3, '拼读', '哪个单词和 big 押韵，意思是“挖”？', 'dig', [['wig', M], ['pen', P]], 'dig（挖）和 big 都在 -ig 家族；wig 是假发。', 'stretch'),
    q('u4.words', 3, '找不同', '下面哪个词不是地方？', 'hen', [['zoo', M], ['park', M]], 'zoo、park 是地方，hen 是母鸡。', 'stretch'),
    // 创新
    q('u4.words', 2, '读一读', 'Look! Ten hens in the park!\n公园里有几只母鸡？', '十只', [['两只', M], ['一只', M]], 'ten 是“十”，hens 是母鸡。', 'creative'),
    q('u4.words', 2, '猜一猜', '猜一猜：这里有大屏幕和很多座位，可以看电影，是（　）', 'cinema', [['park', M], ['zoo', M]], '看电影的地方是 cinema。', 'creative'),
    q('u4.words', 3, '看图说话', '图上：一个戴假发的男人在公园里挖土。选出正确的一组词', 'wig, dig, park', [['wig, big, park', M], ['pen, dig, zoo', M]], '假发 wig，挖 dig，公园 park。', 'creative'),

    // ------------------------------------------------------ u4.talk
    q('u4.talk', 1, '选词填空', '（　） a park near my home.', "There's", [['This', S], ['It', S]], "说“有一个……”用 There's a…"),
    q('u4.talk', 1, '选词填空', "There's a cinema （　） my home.", 'near', [['with', S], ['and', S]], 'near 是“在……附近”：near my home。'),
    q('u4.talk', 1, '选词填空', "There's a （　） near my home.（家附近有个水果店）", 'fruit shop', [['pet shop', M], ['toy shop', M]], '水果店是 fruit shop。'),
    q('u4.talk', 1, '选词填空', "There's a （　） near my home.（家附近有个动物园）", 'zoo', [['park', M], ['cinema', M]], '动物园是 zoo。'),
    q('u4.talk', 1, '选词填空', "There's a （　） near my home.（家附近有个电影院）", 'cinema', [['zoo', M], ['toy shop', M]], '电影院是 cinema。'),
    q('u4.talk', 1, '选词填空', "There's a （　） near my home.（家附近有个宠物店）", 'pet shop', [['fruit shop', M], ['park', M]], '宠物店是 pet shop。'),
    q('u4.talk', 1, '选词填空', "There's a （　） near my home.（家附近有个玩具店）", 'toy shop', [['pet shop', M], ['cinema', M]], '玩具店是 toy shop。'),
    q('u4.talk', 2, '选词填空', 'Is （　） a pet shop near your home?', 'there', [['it', S], ['this', S]], '问“有……吗？”用 Is there a…?'),
    q('u4.talk', 2, '选词填空', "There's a toy shop near my （　）.", 'home', [['I', S], ['is', S]], 'near my home 是“在我家附近”。'),
    q('u4.talk', 2, '选词填空', "There's （　） cinema near my home.", 'a', [['an', S], ['is', S]], "There's a… 后面加 a，cinema 前用 a。"),
    q('u4.talk', 1, '看中文选英文', '我家附近有一个公园。', "There's a park near my home.", [["There's a zoo near my home.", M], ["There's a park in my home.", M]], "“附近”是 near，公园是 park。"),
    q('u4.talk', 1, '看中文选英文', '我家附近有一个电影院。', "There's a cinema near my home.", [["There's a toy shop near my home.", M], ["There's cinema near my home.", S]], "There's 后面要有 a：There's a cinema…"),
    q('u4.talk', 2, '看中文选英文', '我喜欢这个公园。', 'I like this park.', [['I like this zoo.', M], ['This is a park.', M]], 'I like 是“我喜欢”，this park 是这个公园。'),
    q('u4.talk', 1, '句子意思', "There's a pet shop near my home. 的意思是（　）", '我家附近有一个宠物店。', [['我家附近有一个玩具店。', M], ['我家里有一只宠物。', M]], 'pet shop 是宠物店，near my home 是在我家附近。'),
    q('u4.talk', 1, '句子意思', 'Is there a zoo near your home? 的意思是（　）', '你家附近有动物园吗？', [['你家附近有公园吗？', M], ['我家附近有一个动物园。', M]], 'Is there…? 是问“有……吗？”，zoo 是动物园。'),
    q('u4.talk', 1, '句子意思', 'I like the zoo. 的意思是（　）', '我喜欢动物园。', [['我喜欢公园。', M], ['我家附近有动物园。', M]], 'I like 是“我喜欢”，zoo 是动物园。'),
    q('u4.talk', 1, '句子意思', 'Yes, there is. 的意思是（　）', '是的，有。', [['不，没有。', M], ['是的，它是。', M]], 'Yes, there is. 回答 Is there…?，意思是“是的，有”。'),
    q('u4.talk', 2, '补全对话', '— Is there a park near your home?\n— Yes, （　）.', 'there is', [["there isn't", S], ['it is', S]], 'Is there…? 用 Yes, there is. 回答。'),
    q('u4.talk', 2, '补全对话', '— Is there a cinema near your home?\n— No, （　）.', "there isn't", [['there is', S], ["it isn't", S]], "Is there…? 否定回答 No, there isn't."),
    q('u4.talk', 2, '补全对话', "— （　）\n— Yes, there is. It's a big zoo.", 'Is there a zoo near your home?', [["What's your favourite toy?", S], ["There's a zoo near my home.", S]], '回答 Yes, there is.，问句是 Is there…?'),
    q('u4.talk', 1, '情景交际', '你想告诉新朋友你家附近有个公园，你说（　）', "There's a park near my home.", [["There's a zoo near my home.", M], ['Is there a park near your home?', S]], "介绍家附近的地方：There's a park near my home."),
    q('u4.talk', 1, '情景交际', '你想问朋友家附近有没有玩具店，你说（　）', 'Is there a toy shop near your home?', [["There's a toy shop near my home.", S], ['Is there a pet shop near your home?', M]], '问“有……吗？”：Is there a toy shop near your home?'),
    q('u4.talk', 2, '情景交际', '朋友问你家附近有没有电影院，你家附近没有，你回答（　）', "No, there isn't.", [['Yes, there is.', M], ['No, there is.', S]], "没有就说 No, there isn't."),
    q('u4.talk', 2, '情景交际', '朋友问你家附近有没有水果店，你家附近有，你回答（　）', 'Yes, there is.', [["No, there isn't.", M], ["Yes, there isn't.", S]], '有就说 Yes, there is.'),
    q('u4.talk', 2, '情景交际', '你家附近有个宠物店，你想告诉 Kitty，你说（　）', "There's a pet shop near my home.", [["There's a pet near my home.", M], ['Is there a pet shop near your home?', S]], "宠物店是 pet shop：There's a pet shop near my home."),
    q('u4.talk', 2, '连词成句', "把单词排成正确的句子：near / there's / a / zoo / my / home / .", "There's a zoo near my home.", [["There's a zoo my home near.", S], ["A zoo there's near my home.", S]], "There's a zoo 放前面，near my home 放后面。"),
    q('u4.talk', 3, '连词成句', '把单词排成正确的句子：there / is / a / park / near / your / home / ?', 'Is there a park near your home?', [['Is a park there near your home?', S], ['Is there near a park your home?', S]], '问句顺序：Is there a park near your home?'),
    q('u4.talk', 3, '选出正确的句子', '选出书写正确的句子：我家附近有一个动物园。', "There's a zoo near my home.", [["there's a zoo near my home.", S], ['Theres a zoo near my home.', S], ["There's a zoo near my home", S]], "句首大写，There's 中间有一撇，句末有句号。"),
    q('u4.talk', 3, '选出正确的句子', '选出书写正确的问句：你家附近有宠物店吗？', 'Is there a pet shop near your home?', [['Is there a pet shop near your home.', S], ['is there a pet shop near your home?', S], ['Is there a pet shop near you home?', S]], '问句用问号，句首大写，“你的家”是 your home。'),
    q('u4.talk', 2, '句型选择', '哪一句是在问“你家附近有……吗？”', 'Is there a park near your home?', [["There's a park near my home.", S], ['I like the park.', S]], 'Is there…? 是问“有……吗？”'),
    q('u4.talk', 2, '句型选择', '哪一句是在介绍自己家附近的地方？', "There's a cinema near my home.", [['Is there a cinema near your home?', S], ["What's your favourite toy?", S]], "There's a… near my home. 是介绍自己家附近。"),
    // 拔高
    q('u4.talk', 3, '找错句', '下面哪一组问答不对？', '— Is there a park near your home? — Yes, it is.', [['— Is there a park near your home? — Yes, there is.', S], ["— Is there a zoo near your home? — No, there isn't.", S]], "Is there…? 要用 there is / there isn't 回答。", 'stretch'),
    q('u4.talk', 3, '补全对话', "— （　）\n— No, there isn't. There's a toy shop near my home.", 'Is there a pet shop near your home?', [['Is there a toy shop near your home?', S], ["What's your favourite toy?", S]], '回答说“没有，有的是玩具店”，所以问的是别的店。', 'stretch'),
    q('u4.talk', 3, '看中文选英文', '我家附近有一个公园和一个动物园。', "There's a park and a zoo near my home.", [["There's a park and a cinema near my home.", M], ["There's a zoo and a pet shop near my home.", M]], '公园 park，动物园 zoo，用 and 连起来。', 'stretch'),
    q('u4.talk', 3, '对话排序', "给对话排序：\n① No, there isn't.\n② Is there a zoo near your home?\n③ Is there a park near your home?\n④ Yes, there is.", '②①③④', [['①②④③', S], ['④③①②', S]], '每问一句 Is there…?，后面紧跟回答。', 'stretch'),
    // 创新
    q('u4.talk', 2, '读一读', "Around my new home\nThere's a park near my home. There's a fruit shop too. I like the park.\n小作者最喜欢哪里？", '公园', [['水果店', M], ['动物园', M]], 'I like the park. 说明喜欢公园。', 'creative'),
    q('u4.talk', 2, '情景交际', "新同学问你 “Is there a cinema near your home?” 你家旁边就有个电影院。你回答（　）", 'Yes, there is.', [["No, there isn't.", M], ['Yes, it is.', S]], '有就说 Yes, there is.', 'creative'),
    q('u4.talk', 3, '情景交际', '你做小报告，介绍你家附近有一个宠物店，你很喜欢它。你说（　）', "There's a pet shop near my home. I like it.", [["There's a toy shop near my home. I like it.", M], ['Is there a pet shop near your home? I like it.', S]], "介绍家附近：There's a pet shop near my home.", 'creative'),

    // ================================================================ Unit 5
    // ------------------------------------------------------ u5.words
    rhyme('u5.words', 1, 'pin', 'bin', 'ship', 'lip', '-in'),
    rhyme('u5.words', 1, 'ship', 'lip', 'fin', 'bin', '-ip'),
    family('u5.words', 1, '-in', 'fin', 'zip', 'lip'),
    family('u5.words', 1, '-ip', 'zip', 'pin', 'bin'),
    blend('u5.words', 1, 'b', 'in', 'bin', 'pin', 'ship'),
    blend('u5.words', 1, 'z', 'ip', 'zip', 'lip', 'fin'),
    swap('u5.words', 2, 'pin', 'p', 'f', 'fin', 'bin', 'ship'),
    swap('u5.words', 2, 'lip', 'l', 'sh', 'ship', 'zip', 'pin'),
    odd('u5.words', 2, 'pin / bin / lip', 'lip', 'pin', 'bin', 'pin、bin 结尾是 -in，lip 结尾是 -ip。'),
    odd('u5.words', 2, 'ship / zip / fin', 'fin', 'ship', 'zip', 'ship、zip 结尾是 -ip，fin 结尾是 -in。'),
    q('u5.words', 1, '选词填空', '“哞哞”叫、能产奶的动物是（　）', 'cow', [['sheep', M], ['pig', M]], 'cow 是奶牛。'),
    q('u5.words', 1, '选词填空', '身上长满白白的羊毛的动物是（　）', 'sheep', [['cow', M], ['duck', M]], 'sheep 是绵羊。'),
    q('u5.words', 1, '选词填空', '“嘎嘎”叫、会在水里游的动物是（　）', 'duck', [['chick', M], ['pig', M]], 'duck 是鸭子。'),
    q('u5.words', 1, '选词填空', '刚从蛋壳里出来的毛茸茸小鸡是（　）', 'chick', [['chicken', M], ['duck', M]], 'chick 是小鸡，长大了才是 chicken。'),
    q('u5.words', 1, '选词填空', '“哼哼”叫、吃饱了就睡的动物是（　）', 'pig', [['cow', M], ['sheep', M]], 'pig 是猪。'),
    q('u5.words', 2, '选词填空', 'chick 长大了，变成（　）', 'chicken', [['duck', M], ['cow', M]], '小鸡 chick 长大就是鸡 chicken。'),
    q('u5.words', 2, '补全单词', '选字母补全单词：sh（　）p（绵羊）', 'ee', [['ea', P], ['e', P]], '绵羊 sheep 中间有两个 e。'),
    q('u5.words', 2, '补全单词', '选字母补全单词：chi（　）ken（鸡）', 'c', [['k', P], ['s', P]], '鸡 chicken 拼作 c-h-i-c-k-e-n，ck 连在一起。'),
    // 拔高
    q('u5.words', 3, '词义辨析', 'chick 和 chicken 有什么不同？', 'chick 是小鸡，chicken 是鸡', [['两个词意思一样', M], ['chick 是鸭子，chicken 是鸡', M]], 'chick 是刚出生的小鸡，长大了叫 chicken。', 'stretch'),
    q('u5.words', 3, '拼读', '哪一组单词的结尾音都一样？（-in / -ip）', 'ship, lip, zip', [['ship, pin, zip', P], ['bin, lip, fin', P]], 'ship、lip、zip 都在 -ip 家族。', 'stretch'),
    q('u5.words', 3, '拼读', '哪个单词和 pig 押韵？', 'dig', [['pin', P], ['pen', P]], 'pig 和 dig 都在 -ig 家族；pin 是 -in，pen 是 -en。', 'stretch'),
    q('u5.words', 3, '找不同', '下面哪个不是农场动物？', 'ship', [['cow', M], ['duck', M]], 'cow、duck 是农场动物，ship 是轮船；小心别把 ship 和 sheep 弄混。', 'stretch'),
    // 创新
    q('u5.words', 2, '读一读', 'On the farm, I can see a cow, two pigs and three ducks.\n农场上有几只鸭子？', '三只', [['两只', M], ['一只', M]], 'three ducks 是三只鸭子。', 'creative'),
    q('u5.words', 2, '猜一猜', '猜一猜：黄黄的、小小的，长大了变成 chicken，是（　）', 'chick', [['duck', M], ['pig', M]], '小鸡是 chick。', 'creative'),
    q('u5.words', 3, '看图说话', '图上：一条小鱼摆动着鱼鳍，游到一艘大轮船旁边。选出正确的一组词', 'fin, ship', [['fin, zip', M], ['pin, ship', M]], '鱼鳍 fin，轮船 ship。', 'creative'),

    // ------------------------------------------------------ u5.talk
    q('u5.talk', 1, '选词填空', "I like （　）. They're big.（奶牛）", 'cows', [['cow', S], ['cowes', S]], '说喜欢一类动物用复数：cows。'),
    q('u5.talk', 1, '选词填空', "I like （　）. They're small.（小鸡）", 'chicks', [['chick', S], ['chickes', S]], '说喜欢一类动物用复数：chicks。'),
    q('u5.talk', 1, '选词填空', "I like （　）. They're cute.（鸭子）", 'ducks', [['duck', S], ['duckes', S]], '说喜欢一类动物用复数：ducks。'),
    q('u5.talk', 1, '选词填空', 'I like （　）.（猪）', 'pigs', [['pig', S], ['piges', S]], '说喜欢一类动物用复数：pigs。'),
    q('u5.talk', 2, '选词填空', 'I like （　）.（绵羊）', 'sheep', [['sheeps', S], ['sheepes', S]], 'sheep 的复数还是 sheep，不加 s。'),
    q('u5.talk', 1, '选词填空', 'I like cows. （　） big.', "They're", [["It's", S], ["He's", S]], "说很多只动物用 They're（它们是）。"),
    q('u5.talk', 1, '选词填空', "I like chicks. They're （　）.（小鸡很小）", 'small', [['big', M], ['old', M]], '小鸡很小：small。'),
    q('u5.talk', 1, '选词填空', "I like cows. They're （　）.（奶牛很大）", 'big', [['small', M], ['young', M]], '奶牛很大：big。'),
    q('u5.talk', 2, '选词填空', "Look at the （　）. They're small.", 'chicks', [['cow', S], ['pig', S]], "They're 说的是很多只，要用复数 chicks。"),
    q('u5.talk', 2, '选词填空', 'What do you （　）? I like pigs.', 'like', [['see', S], ['is', S]], '回答 I like…，问句是 What do you like?'),
    q('u5.talk', 1, '看中文选英文', '我喜欢鸭子。', 'I like ducks.', [['I like duck.', S], ['I like chicks.', M]], '喜欢一类动物用复数：ducks。'),
    q('u5.talk', 2, '看中文选英文', '我喜欢小鸡，它们很可爱。', "I like chicks. They're cute.", [["I like chicks. They're big.", M], ["I like chick. They're cute.", S]], "小鸡用复数 chicks，它们是 They're，可爱是 cute。"),
    q('u5.talk', 2, '看中文选英文', '我喜欢绵羊。', 'I like sheep.', [['I like sheeps.', S], ['I like ships.', M]], 'sheep 的复数不变；ship 是轮船。'),
    q('u5.talk', 2, '看中文选英文', '两只小鸭子', 'two ducks', [['two duck', S], ['two duckes', S]], '两只以上要用复数：two ducks。'),
    q('u5.talk', 2, '看中文选英文', '三只绵羊', 'three sheep', [['three sheeps', S], ['three sheepes', S]], 'sheep 的复数还是 sheep：three sheep。'),
    q('u5.talk', 1, '句子意思', 'I like pigs. 的意思是（　）', '我喜欢猪。', [['我喜欢鸭子。', M], ['我是一头猪。', M]], 'I like 是“我喜欢”，pigs 是猪。'),
    q('u5.talk', 1, '句子意思', "They're big. 的意思是（　）", '它们很大。', [['它们很小。', M], ['它很大。', M]], "They're 是“它们是”，big 是“大的”。"),
    q('u5.talk', 1, '句子意思', 'What do you like? 的意思是（　）', '你喜欢什么？', [['你看见了什么？', M], ['你喜欢鸭子吗？', M]], 'What 是“什么”，like 是“喜欢”。'),
    q('u5.talk', 2, '句子意思', "I like sheep. They're cute. 的意思是（　）", '我喜欢绵羊，它们很可爱。', [['我喜欢轮船，它们很可爱。', M], ['我喜欢绵羊，它们很大。', M]], 'sheep 是绵羊，cute 是可爱的。'),
    q('u5.talk', 2, '补全对话', '— What do you like?\n— （　）', 'I like cows.', [["They're big.", S], ["I'm a cow.", S]], '问“你喜欢什么”，回答 I like…'),
    q('u5.talk', 2, '补全对话', '— （　）\n— I like chickens.', 'What do you like?', [['What can you see?', S], ["Who's he?", S]], '回答 I like…，问句是 What do you like?'),
    q('u5.talk', 2, '补全对话', '— What do you like?\n— I like ducks. （　）', "They're cute.", [["It's cute.", S], ["He's cute.", S]], "ducks 是很多只，用 They're。"),
    q('u5.talk', 1, '情景交际', '在农场，你想告诉朋友你喜欢奶牛，你说（　）', 'I like cows.', [['I like cow.', S], ['I like sheep.', M]], '喜欢奶牛：I like cows.'),
    q('u5.talk', 1, '情景交际', '你想问朋友喜欢什么，你说（　）', 'What do you like?', [['What can you see?', M], ['I like pigs.', S]], '问“你喜欢什么”：What do you like?'),
    q('u5.talk', 2, '情景交际', '你想说“小猪们很可爱”，你说（　）', "They're cute.", [["They're old.", M], ["It's cute.", S]], "很多只用 They're，可爱是 cute。"),
    q('u5.talk', 2, '情景交际', '在农场看到一群小鸡，你说“看，小鸡们！它们很小。”（　）', "Look! Chicks! They're small.", [["Look! Chick! They're small.", S], ["Look! Chicks! They're big.", M]], "一群小鸡用复数 chicks，很小是 small。"),
    q('u5.talk', 2, '连词成句', '把单词排成正确的句子：like / I / ducks / .', 'I like ducks.', [['I ducks like.', S], ['Like I ducks.', S]], '顺序是 I + like + 动物：I like ducks.'),
    q('u5.talk', 2, '连词成句', '把单词排成正确的句子：do / what / you / like / ?', 'What do you like?', [['What you do like?', S], ['What like you do?', S]], '问句顺序：What do you like?'),
    q('u5.talk', 3, '选出正确的句子', '选出正确的句子：我喜欢奶牛，它们很大。', "I like cows. They're big.", [["I like cow. They're big.", S], ["I like cows. It's big.", S], ["i like cows. They're big.", S]], "奶牛用复数 cows，它们用 They're，I 要大写。"),
    q('u5.talk', 2, '句型选择', '哪一句说的是很多只动物？', "They're cute.", [["It's cute.", S], ["I'm cute.", S]], "They're 是“它们是”，说很多只。"),
    q('u5.talk', 2, '句型选择', '说喜欢猪（很多只），哪一句是对的？', 'I like pigs.', [['I like pig.', S], ['I like piges.', S]], 'pig 的复数是 pigs，直接加 s。'),
    // 拔高
    q('u5.talk', 3, '找错句', '（说很多只动物）下面哪一句写错了？', 'I like sheeps.', [['I like cows.', S], ['I like ducks.', S]], 'sheep 的复数还是 sheep，不能加 s。', 'stretch'),
    q('u5.talk', 3, '补全对话', "— （　）\n— I like pigs. They're cute.", 'What do you like?', [['What can you see?', S], ["What's your favourite toy?", S]], '回答 I like pigs.，问句是 What do you like?', 'stretch'),
    q('u5.talk', 3, '看中文选英文', '我喜欢奶牛和绵羊，它们很大。', "I like cows and sheep. They're big.", [["I like cows and sheeps. They're big.", S], ["I like cow and sheep. It's big.", S]], "cows 加 s，sheep 不变；很多只用 They're。", 'stretch'),
    q('u5.talk', 3, '对话排序', "给对话排序：\n① I like ducks.\n② They're cute.\n③ What do you like?", '③①②', [['①②③', S], ['②③①', S]], "先问 What do you like?，再答 I like ducks.，最后说 They're cute.", 'stretch'),
    // 创新
    q('u5.talk', 2, '读一读', "Kitty: What do you like?\nSam: I like cows. They're big.\nSam 喜欢什么？为什么？", '奶牛，因为它们很大', [['奶牛，因为它们很小', M], ['小鸡，因为它们很大', M]], "I like cows. They're big. 喜欢奶牛，因为它们很大。", 'creative'),
    q('u5.talk', 2, '情景交际', '在农家乐，你看到一群毛茸茸的小鸡，想告诉妈妈你喜欢它们。你说（　）', "I like chicks. They're cute.", [["I like chicks. They're old.", M], ["I like chick. It's cute.", S]], "小鸡用复数 chicks，可爱是 cute。", 'creative'),
    q('u5.talk', 3, '看图说话', '图上：池塘里有三只鸭子在游泳。选出正确的句子', 'I can see three ducks.', [['I can see three duck.', S], ['I can see three chicks.', M]], '三只鸭子：three ducks，要用复数。', 'creative'),

    // ================================================================ Unit 6
    // ------------------------------------------------------ u6.words
    q('u6.words', 1, '选词填空', '抬头看天上圆圆的月亮，是（　）', 'look at the moon', [['solve riddles', M], ['play with lanterns', M]], 'look at the moon 是赏月。'),
    q('u6.words', 1, '选词填空', '吃圆圆的、甜甜的月饼，是（　）', 'eat mooncakes', [['look at the moon', M], ['solve riddles', M]], 'eat mooncakes 是吃月饼。'),
    q('u6.words', 1, '选词填空', '提着兔子灯走来走去，是（　）', 'play with lanterns', [['eat mooncakes', M], ['solve riddles', M]], 'play with lanterns 是玩灯笼。'),
    q('u6.words', 1, '选词填空', '读灯笼上的谜面，想出答案，是（　）', 'solve riddles', [['play with lanterns', M], ['look at the moon', M]], 'solve riddles 是猜谜语。'),
    q('u6.words', 1, '选词填空', 'eat （　）（吃月饼）', 'mooncakes', [['lanterns', M], ['riddles', M]], '吃月饼：eat mooncakes。'),
    q('u6.words', 1, '选词填空', 'play with （　）（玩灯笼）', 'lanterns', [['mooncakes', M], ['riddles', M]], '玩灯笼：play with lanterns。'),
    q('u6.words', 1, '选词填空', 'solve （　）（猜谜语）', 'riddles', [['mooncakes', M], ['lanterns', M]], '猜谜语：solve riddles。'),
    q('u6.words', 1, '选词填空', 'look at the （　）（赏月）', 'moon', [['riddles', M], ['mooncakes', M]], '赏月：look at the moon。'),
    q('u6.words', 2, '补全单词', '选字母补全单词：m（　）n（月亮）', 'oo', [['ee', P], ['ou', P]], '月亮 moon 中间是两个 o。'),
    q('u6.words', 2, '补全单词', '选字母补全单词：l（　）ntern（灯笼）', 'a', [['e', P], ['o', P]], '灯笼 lantern 拼作 l-a-n-t-e-r-n。'),
    q('u6.words', 2, '拼读', '复习：哪个单词和 ten 押韵？', 'hen', [['pin', P], ['ham', P]], 'ten 和 hen 都在 -en 家族。'),
    q('u6.words', 2, '拼读', '复习：哪个单词和 zip 押韵？', 'ship', [['zoo', P], ['jam', P]], 'zip 和 ship 都在 -ip 家族。'),
    q('u6.words', 2, '拼读', '复习：哪个单词和 net 押韵？', 'pet', [['pen', P], ['pin', P]], 'net 和 pet 都在 -et 家族。'),
    q('u6.words', 2, '拼读', '复习：哪个单词和 fan 押韵？', 'man', [['fin', P], ['bed', P]], 'fan 和 man 都在 -an 家族。'),
    q('u6.words', 2, '拼读', '复习：给单词找家，hat 属于（　）家族', '-at', [['-ap', P], ['-et', P]], 'hat 的结尾是 at，属于 -at 家族。'),
    q('u6.words', 2, '拼读', '复习：给单词找家，dig 属于（　）家族', '-ig', [['-in', P], ['-ip', P]], 'dig 的结尾是 ig，属于 -ig 家族。'),
    q('u6.words', 2, '拼读', '复习：给单词找家，jam 属于（　）家族', '-am', [['-an', P], ['-ap', P]], 'jam 的结尾是 am，属于 -am 家族。'),
    // 拔高
    q('u6.words', 3, '找不同', '下面哪个不是中秋节的传统活动？', 'play with a robot', [['play with lanterns', M], ['eat mooncakes', M]], '中秋节玩灯笼、吃月饼；玩机器人不是中秋的传统活动。', 'stretch'),
    q('u6.words', 3, '拼读', '复习：哪两个单词押韵？', 'red, bed', [['red, rat', P], ['bed, bin', P]], 'red 和 bed 都在 -ed 家族。', 'stretch'),
    q('u6.words', 3, '拼读', '复习：把 pin 中间的 i 换成 e，变成（　）', 'pen', [['pan', P], ['pig', P]], 'pin 换中间的元音 e，变成 pen（钢笔）。', 'stretch'),
    q('u6.words', 3, '词组搭配', '中秋节的活动，哪一组搭配全对？', 'eat mooncakes, look at the moon', [['eat lanterns, look at the moon', M], ['eat mooncakes, look at the riddles', M]], '吃的是月饼 eat mooncakes，看的是月亮 look at the moon。', 'stretch'),
    // 创新
    q('u6.words', 2, '读一读', 'We eat mooncakes. We play with lanterns. We look at the moon.\n短文没有说到哪件事？', '猜谜语', [['吃月饼', M], ['赏月', M]], '短文说了吃月饼、玩灯笼、赏月，没有说猜谜语（solve riddles）。', 'creative'),
    q('u6.words', 2, '猜一猜', '猜一猜：圆圆的，挂在天上，中秋节晚上最亮，是（　）', 'moon', [['mooncake', M], ['lantern', M]], '挂在天上的是月亮 moon。', 'creative'),
    q('u6.words', 3, '看图说话', '图上：小朋友提着兔子灯笼，在猜灯谜。选出正确的一组', 'play with lanterns, solve riddles', [['play with lanterns, eat mooncakes', M], ['look at the moon, solve riddles', M]], '提灯笼是 play with lanterns，猜灯谜是 solve riddles。', 'creative'),

    // ------------------------------------------------------ u6.talk
    q('u6.talk', 1, '选词填空', 'At the Mid-Autumn Festival, we （　） mooncakes.', 'eat', [['play', M], ['look', M]], '吃月饼：eat mooncakes。'),
    q('u6.talk', 1, '选词填空', 'At the Mid-Autumn Festival, we play with （　）.', 'lanterns', [['mooncakes', M], ['the moon', M]], '玩灯笼：play with lanterns。'),
    q('u6.talk', 1, '选词填空', 'At the Mid-Autumn Festival, we look at the （　）.（赏月）', 'moon', [['riddles', M], ['mooncakes', M]], '赏月：look at the moon。'),
    q('u6.talk', 1, '选词填空', 'At the Mid-Autumn Festival, we solve （　）.（猜谜语）', 'riddles', [['mooncakes', M], ['moon', M]], '猜谜语：solve riddles。'),
    q('u6.talk', 2, '选词填空', '（　） the Mid-Autumn Festival, we eat mooncakes.', 'At', [['With', S], ['Is', S]], '“在中秋节”说 At the Mid-Autumn Festival。'),
    q('u6.talk', 2, '选词填空', 'At the Mid-Autumn Festival, （　） eat mooncakes.', 'we', [['us', S], ['our', S]], '“我们吃月饼”：we eat mooncakes。'),
    q('u6.talk', 2, '选词填空', 'We play （　） lanterns.', 'with', [['at', S], ['eat', S]], '玩灯笼：play with lanterns。'),
    q('u6.talk', 2, '选词填空', 'We look （　） the moon.', 'at', [['with', S], ['eat', S]], '赏月：look at the moon。'),
    q('u6.talk', 2, '选词填空', 'We eat mooncakes and （　） at the moon.', 'look', [['eat', M], ['play', M]], '赏月是 look at the moon。'),
    q('u6.talk', 1, '看中文选英文', '中秋节，我们吃月饼。', 'At the Mid-Autumn Festival, we eat mooncakes.', [['At the Mid-Autumn Festival, we play with mooncakes.', M], ['At the Mid-Autumn Festival, we eat lanterns.', M]], '吃月饼是 eat mooncakes。'),
    q('u6.talk', 1, '看中文选英文', '我们赏月。', 'We look at the moon.', [['We eat the moon.', M], ['We look at mooncakes.', M]], '赏月是 look at the moon。'),
    q('u6.talk', 1, '看中文选英文', '我们玩灯笼。', 'We play with lanterns.', [['We play with mooncakes.', M], ['We eat lanterns.', M]], '玩灯笼是 play with lanterns。'),
    q('u6.talk', 1, '看中文选英文', '我们猜谜语。', 'We solve riddles.', [['We eat riddles.', M], ['We solve lanterns.', M]], '猜谜语是 solve riddles。'),
    q('u6.talk', 1, '看中文选英文', '中秋节快乐！', 'Happy Mid-Autumn Festival!', [['Happy New Year!', M], ['Good Mid-Autumn Festival!', S]], '节日祝福用 Happy…：Happy Mid-Autumn Festival!'),
    q('u6.talk', 2, '看中文选英文', '我们一起吃月饼、赏月。', 'We eat mooncakes and look at the moon.', [['We eat the moon and look at mooncakes.', M], ['We play with mooncakes and look at the moon.', M]], '吃月饼 eat mooncakes，赏月 look at the moon。'),
    q('u6.talk', 1, '句子意思', 'We look at the moon. 的意思是（　）', '我们赏月。', [['我们吃月饼。', M], ['我们看灯笼。', M]], 'look at the moon 是赏月。'),
    q('u6.talk', 1, '句子意思', 'We solve riddles. 的意思是（　）', '我们猜谜语。', [['我们玩灯笼。', M], ['我们讲故事。', M]], 'solve riddles 是猜谜语。'),
    q('u6.talk', 1, '句子意思', 'I like mooncakes. 的意思是（　）', '我喜欢月饼。', [['我喜欢月亮。', M], ['我喜欢灯笼。', M]], 'mooncakes 是月饼，moon 才是月亮。'),
    q('u6.talk', 2, '句子意思', 'At the Mid-Autumn Festival, we play with lanterns. 的意思是（　）', '中秋节，我们玩灯笼。', [['中秋节，我们吃月饼。', M], ['春节，我们玩灯笼。', M]], 'Mid-Autumn Festival 是中秋节，play with lanterns 是玩灯笼。'),
    q('u6.talk', 2, '补全对话', '— What do you do at the Mid-Autumn Festival?\n— （　）', 'We eat mooncakes.', [['I like cows.', S], ["There's a park near my home.", S]], '问中秋节做什么，回答中秋活动：We eat mooncakes.'),
    q('u6.talk', 2, '补全对话', '— （　）\n— We play with lanterns.', 'What do you do at the Mid-Autumn Festival?', [["What's your favourite toy?", S], ['What do you like?', S]], '回答的是中秋活动，问句问中秋节做什么。'),
    q('u6.talk', 2, '补全对话', '— Happy Mid-Autumn Festival!\n— （　）', 'Happy Mid-Autumn Festival!', [['Yes, it is.', S], ['I like cows.', S]], '别人祝你节日快乐，你也回一句 Happy Mid-Autumn Festival!'),
    q('u6.talk', 1, '情景交际', '外国小朋友问你中秋节做什么，你想说“我们赏月”（　）', 'We look at the moon.', [['We eat the moon.', M], ['We play with the moon.', M]], '赏月是 look at the moon。'),
    q('u6.talk', 1, '情景交际', '你想告诉朋友你喜欢月饼，你说（　）', 'I like mooncakes.', [['I like lanterns.', M], ['We eat lanterns.', M]], '月饼是 mooncakes。'),
    q('u6.talk', 1, '情景交际', '中秋节晚上，你想叫朋友看月亮，你说（　）', 'Look at the moon!', [['Look at the mooncake!', M], ['Eat the moon!', M]], '看月亮：Look at the moon!'),
    q('u6.talk', 1, '情景交际', '中秋节见到邻居奶奶，你祝她节日快乐，你说（　）', 'Happy Mid-Autumn Festival!', [['Good night!', S], ['Thank you!', S]], '节日祝福：Happy Mid-Autumn Festival!'),
    q('u6.talk', 2, '连词成句', '把单词排成正确的句子：eat / we / mooncakes / .', 'We eat mooncakes.', [['We mooncakes eat.', S], ['Eat we mooncakes.', S]], '顺序是 We + eat + mooncakes。'),
    q('u6.talk', 2, '连词成句', '把单词排成正确的句子：look / we / the / at / moon / .', 'We look at the moon.', [['We look the at moon.', S], ['We at look the moon.', S]], 'look at the moon 要连在一起说。'),
    q('u6.talk', 3, '选出正确的句子', '选出书写正确的句子：中秋节，我们吃月饼。', 'At the Mid-Autumn Festival, we eat mooncakes.', [['At the mid-autumn festival, we eat mooncakes.', S], ['at the Mid-Autumn Festival, we eat mooncakes.', S]], '句首大写，节日名 Mid-Autumn Festival 每个词首字母大写。'),
    q('u6.talk', 2, '句型选择', '哪一句说的是中秋节的活动？', 'We look at the moon.', [['I like cows.', S], ["There's a zoo near my home.", S]], '赏月 look at the moon 是中秋节的活动。'),
    q('u6.talk', 2, '句型选择', '哪一句是在问中秋节做什么？', 'What do you do at the Mid-Autumn Festival?', [['Happy Mid-Autumn Festival!', S], ['We eat mooncakes.', S]], 'What do you do…? 是问“做什么”。'),
    // 拔高
    q('u6.talk', 3, '找错句', '（中秋节）下面哪一句说错了？', 'We eat lanterns.', [['We eat mooncakes.', S], ['We play with lanterns.', S]], '灯笼不能吃，要说 play with lanterns。', 'stretch'),
    q('u6.talk', 3, '补全对话', '— （　）\n— We eat mooncakes and look at the moon.', 'What do you do at the Mid-Autumn Festival?', [['What do you like?', S], ['What can you see?', S]], '回答说的是中秋活动，问句问中秋节做什么。', 'stretch'),
    q('u6.talk', 3, '看中文选英文', '中秋节，我们玩灯笼，还猜谜语。', 'At the Mid-Autumn Festival, we play with lanterns and solve riddles.', [['At the Mid-Autumn Festival, we play with riddles and solve lanterns.', M], ['At the Mid-Autumn Festival, we eat lanterns and solve riddles.', M]], '玩灯笼 play with lanterns，猜谜语 solve riddles，用 and 连起来。', 'stretch'),
    q('u6.talk', 3, '对话排序', '给对话排序：\n① We eat mooncakes and look at the moon.\n② Happy Mid-Autumn Festival!\n③ What do you do at the Mid-Autumn Festival?\n④ Happy Mid-Autumn Festival!', '②④③①', [['③②①④', S], ['①②③④', S]], '先互相祝福，再问中秋节做什么，最后回答。', 'stretch'),
    // 创新
    q('u6.talk', 2, '读一读', 'Kitty: What do you do at the Mid-Autumn Festival?\nSam: We eat mooncakes. We solve riddles.\nSam 中秋节做什么？', '吃月饼、猜谜语', [['吃月饼、赏月', M], ['玩灯笼、猜谜语', M]], 'Sam 说 We eat mooncakes. We solve riddles.', 'creative'),
    q('u6.talk', 3, '情景交际', '你给外国小朋友做小报告，介绍中秋节要赏月、吃月饼。你说（　）', 'At the Mid-Autumn Festival, we look at the moon and eat mooncakes.', [['At the Mid-Autumn Festival, we look at mooncakes and eat the moon.', M], ['At the Mid-Autumn Festival, we play with lanterns and eat mooncakes.', M]], '赏月 look at the moon，吃月饼 eat mooncakes。', 'creative'),
    q('u6.talk', 2, '情景交际', '听完嫦娥奔月的故事，中秋节晚上你和奶奶一起抬头看月亮。你说（　）', 'Look at the moon, Grandma!', [['Look at the mooncake, Grandma!', M], ['Eat the moon, Grandma!', M]], '看月亮：Look at the moon!', 'creative'),
  ],
};
