import type { DictationList } from './types';

/**
 * 语文 四年级上册 词语听写表（家长拍摄的班级听写表），按课文知识点排列；语文园地的词语放在各单元的 garden 知识点，
 * 第五单元习作例文的词语放在 u5.kaleidoscope。拼音先用 pinyin-pro 生成，再逐个人工核对多音字和轻声：
 * 一、不 按变调标（一溜烟 yí liù yān、刀枪不入 bú rù）；词典里读轻声的标轻声（暖和 nuǎn huo、玻璃 bō li）。
 * 听写表上看不清（标 ?）的词没有收录。
 */
export const YW_G4A_WORDS: DictationList = {
  'u1.tide': [
    { w: '观潮', py: 'guān cháo' },
    { w: '据说', py: 'jù shuō' },
    { w: '随着', py: 'suí zhe' },
    { w: '一堵墙', py: 'yì dǔ qiáng' },
    { w: '堤岸', py: 'dī àn' },
    { w: '宽阔', py: 'kuān kuò' },
    { w: '滚动', py: 'gǔn dòng' },
    { w: '顿时', py: 'dùn shí' },
    { w: '逐渐', py: 'zhú jiàn' },
    { w: '堵塞', py: 'dǔ sè' },
    { w: '犹如', py: 'yóu rú' },
    { w: '霎时', py: 'shà shí' },
    { w: '余波', py: 'yú bō' },
    { w: '奇观', py: 'qí guān' },
    { w: '人山人海', py: 'rén shān rén hǎi' },
    { w: '齐头并进', py: 'qí tóu bìng jìn' },
    { w: '若隐若现', py: 'ruò yǐn ruò xiàn' },
    { w: '山崩地裂', py: 'shān bēng dì liè' },
    { w: '人声鼎沸', py: 'rén shēng dǐng fèi' },
    { w: '风平浪静', py: 'fēng píng làng jìng' },
    { w: '水天相接', py: 'shuǐ tiān xiāng jiē' },
    { w: '浩浩荡荡', py: 'hào hào dàng dàng' },
    { w: '风号浪吼', py: 'fēng háo làng hǒu' },
    { w: '漫天卷地', py: 'màn tiān juǎn dì' },
  ],
  'u1.stars': [
    { w: '繁星', py: 'fán xīng' },
    { w: '密密麻麻', py: 'mì mì má má' },
    { w: '忘记', py: 'wàng jì' },
    { w: '谈话', py: 'tán huà' },
    { w: '渐渐', py: 'jiàn jiàn' },
    { w: '模糊', py: 'mó hu' },
    { w: '周围', py: 'zhōu wéi' },
    { w: '飞舞', py: 'fēi wǔ' },
    { w: '柔和', py: 'róu hé' },
    { w: '梦幻', py: 'mèng huàn' },
    { w: '怀抱', py: 'huái bào' },
    { w: '沉睡', py: 'chén shuì' },
    { w: '静寂', py: 'jìng jì' },
    { w: '熟悉', py: 'shú xī' },
    { w: '躺下', py: 'tǎng xià' },
  ],
  'u1.garden': [
    { w: '人声鼎沸', py: 'rén shēng dǐng fèi' },
    { w: '锣鼓喧天', py: 'luó gǔ xuān tiān' },
    { w: '震耳欲聋', py: 'zhèn ěr yù lóng' },
    { w: '响彻云霄', py: 'xiǎng chè yún xiāo' },
    { w: '低声细语', py: 'dī shēng xì yǔ' },
    { w: '窃窃私语', py: 'qiè qiè sī yǔ' },
    { w: '鸦雀无声', py: 'yā què wú shēng' },
    { w: '悄无声息', py: 'qiǎo wú shēng xī' },
  ],
  'u2.peas': [
    { w: '豌豆', py: 'wān dòu' },
    { w: '舒适', py: 'shū shì' },
    { w: '僵硬', py: 'jiāng yìng' },
    { w: '曾经', py: 'céng jīng' },
    { w: '水沟', py: 'shuǐ gōu' },
    { w: '洋溢', py: 'yáng yì' },
    { w: '探出', py: 'tàn chū' },
    { w: '暖洋洋', py: 'nuǎn yáng yáng' },
    { w: '预感', py: 'yù gǎn' },
    { w: '揭晓', py: 'jiē xiǎo' },
    { w: '囚犯', py: 'qiú fàn' },
    { w: '劈柴', py: 'pī chái' },
    { w: '窗框', py: 'chuāng kuàng' },
    { w: '亲吻', py: 'qīn wěn' },
    { w: '脏水', py: 'zāng shuǐ' },
    { w: '健康', py: 'jiàn kāng' },
    { w: '打滚', py: 'dǎ gǔn' },
    { w: '滑落', py: 'huá luò' },
    { w: '擦桌子', py: 'cā zhuō zi' },
    { w: '涨潮', py: 'zhǎng cháo' },
    { w: '身份', py: 'shēn fèn' },
    { w: '暖和', py: 'nuǎn huo' },
    { w: '的确', py: 'dí què' },
    { w: '注视', py: 'zhù shì' },
  ],
  'u2.night-flight': [
    { w: '蚊子', py: 'wén zi' },
    { w: '灵巧', py: 'líng qiǎo' },
    { w: '绳子', py: 'shéng zi' },
    { w: '苍蝇', py: 'cāng ying' },
    { w: '证明', py: 'zhèng míng' },
    { w: '研究', py: 'yán jiū' },
    { w: '秘密', py: 'mì mì' },
    { w: '系上', py: 'jì shang' },
    { w: '即使', py: 'jí shǐ' },
    { w: '问题', py: 'wèn tí' },
    { w: '相互', py: 'xiāng hù' },
    { w: '配合', py: 'pèi hé' },
    { w: '类似', py: 'lèi sì' },
    { w: '能够', py: 'néng gòu' },
    { w: '蝙蝠', py: 'biān fú' },
    { w: '飞蛾', py: 'fēi é' },
    { w: '避开', py: 'bì kāi' },
    { w: '敏锐', py: 'mǐn ruì' },
    { w: '障碍', py: 'zhàng ài' },
    { w: '荧光屏', py: 'yíng guāng píng' },
    { w: '嘴巴', py: 'zuǐ ba' },
    { w: '驾驶员', py: 'jià shǐ yuán' },
    { w: '横七竖八', py: 'héng qī shù bā' },
  ],
  'u2.square-hats': [
    { w: '帽子', py: 'mào zi' },
    { w: '脑袋', py: 'nǎo dai' },
    { w: '舒服', py: 'shū fu' },
    { w: '假如', py: 'jiǎ rú' },
    { w: '设法', py: 'shè fǎ' },
    { w: '懂事', py: 'dǒng shì' },
    { w: '摆放', py: 'bǎi fàng' },
    { w: '玻璃', py: 'bō li' },
    { w: '橱窗', py: 'chú chuāng' },
    { w: '香蕉', py: 'xiāng jiāo' },
    { w: '扣在', py: 'kòu zài' },
    { w: '叫嚷', py: 'jiào rǎng' },
    { w: '圆筒', py: 'yuán tǒng' },
    { w: '古董', py: 'gǔ dǒng' },
    { w: '一溜烟', py: 'yí liù yān' },
    { w: '各式各样', py: 'gè shì gè yàng' },
  ],
  'u2.garden': [
    { w: '提纲', py: 'tí gāng' },
    { w: '生锈', py: 'shēng xiù' },
    { w: '泡沫', py: 'pào mò' },
    { w: '综合', py: 'zōng hé' },
    { w: '氧气', py: 'yǎng qì' },
    { w: '结账', py: 'jié zhàng' },
    { w: '矿物', py: 'kuàng wù' },
    { w: '俱乐部', py: 'jù lè bù' },
  ],
  'u3.ancient-poems': [
    { w: '残缺', py: 'cán quē' },
    { w: '铺设', py: 'pū shè' },
    { w: '墙壁', py: 'qiáng bì' },
    { w: '横竖', py: 'héng shù' },
    { w: '侧面', py: 'cè miàn' },
    { w: '山峰', py: 'shān fēng' },
    { w: '庐山', py: 'lú shān' },
    { w: '缘故', py: 'yuán gù' },
    { w: '降落', py: 'jiàng luò' },
    { w: '投降', py: 'tóu xiáng' },
    { w: '评议', py: 'píng yì' },
    { w: '文章', py: 'wén zhāng' },
    { w: '服输', py: 'fú shū' },
  ],
  'u3.ivy': [
    { w: '爬山虎', py: 'pá shān hǔ' },
    { w: '操场', py: 'cāo chǎng' },
    { w: '嫩绿', py: 'nèn lǜ' },
    { w: '新鲜', py: 'xīn xiān' },
    { w: '均匀', py: 'jūn yún' },
    { w: '空隙', py: 'kòng xì' },
    { w: '叶柄', py: 'yè bǐng' },
    { w: '触角', py: 'chù jiǎo' },
    { w: '弯曲', py: 'wān qū' },
    { w: '痕迹', py: 'hén jì' },
    { w: '瞧不起', py: 'qiáo bu qǐ' },
    { w: '脚步', py: 'jiǎo bù' },
  ],
  'u3.cricket': [
    { w: '住宅', py: 'zhù zhái' },
    { w: '选择', py: 'xuǎn zé' },
    { w: '住址', py: 'zhù zhǐ' },
    { w: '大厅', py: 'dà tīng' },
    { w: '柔弱', py: 'róu ruò' },
    { w: '平坦', py: 'píng tǎn' },
    { w: '光滑', py: 'guāng huá' },
    { w: '修理', py: 'xiū lǐ' },
    { w: '重要', py: 'zhòng yào' },
    { w: '增长', py: 'zēng zhǎng' },
    { w: '专家', py: 'zhuān jiā' },
    { w: '比较', py: 'bǐ jiào' },
    { w: '后腿', py: 'hòu tuǐ' },
    { w: '优良', py: 'yōu liáng' },
    { w: '洞穴', py: 'dòng xué' },
    { w: '随遇而安', py: 'suí yù ér ān' },
  ],
  'u4.pangu': [
    { w: '斧头', py: 'fǔ tóu' },
    { w: '缓缓', py: 'huǎn huǎn' },
    { w: '浑浊', py: 'hún zhuó' },
    { w: '丈量', py: 'zhàng liáng' },
    { w: '四肢', py: 'sì zhī' },
    { w: '躯干', py: 'qū gàn' },
    { w: '血液', py: 'xuè yè' },
    { w: '睡醒', py: 'shuì xǐng' },
    { w: '翻身', py: 'fān shēn' },
    { w: '踏步', py: 'tà bù' },
    { w: '支撑', py: 'zhī chēng' },
    { w: '照耀', py: 'zhào yào' },
    { w: '整个', py: 'zhěng gè' },
    { w: '宇宙', py: 'yǔ zhòu' },
    { w: '黑乎乎', py: 'hēi hū hū' },
    { w: '下降', py: 'xià jiàng' },
    { w: '飘动', py: 'piāo dòng' },
    { w: '奔流不息', py: 'bēn liú bù xī' },
    { w: '茂盛', py: 'mào shèng' },
    { w: '精疲力竭', py: 'jīng pí lì jié' },
  ],
  'u4.jingwei': [
    { w: '名曰', py: 'míng yuē' },
    { w: '溺水', py: 'nì shuǐ' },
    { w: '填塞', py: 'tián sè' },
    { w: '炎帝', py: 'yán dì' },
    { w: '女娃', py: 'nǚ wá' },
    { w: '衔接', py: 'xián jiē' },
  ],
  'u4.prometheus': [
    { w: '斯文', py: 'sī wén' },
    { w: '悲惨', py: 'bēi cǎn' },
    { w: '盗取', py: 'dào qǔ' },
    { w: '飞驰', py: 'fēi chí' },
    { w: '敬佩', py: 'jìng pèi' },
    { w: '违抗', py: 'wéi kàng' },
    { w: '锁链', py: 'suǒ liàn' },
    { w: '遭受', py: 'zāo shòu' },
    { w: '肝脏', py: 'gān zàng' },
    { w: '愤愤不平', py: 'fèn fèn bù píng' },
    { w: '砸碎', py: 'zá suì' },
    { w: '颗粒', py: 'kē lì' },
    { w: '气急败坏', py: 'qì jí bài huài' },
    { w: '忍受', py: 'rěn shòu' },
    { w: '既然', py: 'jì rán' },
    { w: '屈服', py: 'qū fú' },
    { w: '获得', py: 'huò dé' },
    { w: '严厉', py: 'yán lì' },
    { w: '立即', py: 'lì jí' },
    { w: '执行', py: 'zhí xíng' },
    { w: '坚定', py: 'jiān dìng' },
    { w: '尽管', py: 'jǐn guǎn' },
  ],
  'u4.nuwa': [
    { w: '野兽', py: 'yě shòu' },
    { w: '惊慌失措', py: 'jīng huāng shī cuò' },
    { w: '陷入', py: 'xiàn rù' },
    { w: '混乱', py: 'hùn luàn' },
    { w: '挑拣', py: 'tiāo jiǎn' },
    { w: '燃气', py: 'rán qì' },
    { w: '熔炼', py: 'róng liàn' },
    { w: '熄灭', py: 'xī miè' },
    { w: '石浆', py: 'shí jiāng' },
    { w: '杀害', py: 'shā hài' },
    { w: '传颂', py: 'chuán sòng' },
  ],
  'u4.garden': [
    { w: '花卉', py: 'huā huì' },
    { w: '玫瑰', py: 'méi gui' },
    { w: '牡丹', py: 'mǔ dan' },
    { w: '花蕾', py: 'huā lěi' },
    { w: '茉莉', py: 'mò lì' },
    { w: '海棠', py: 'hǎi táng' },
    { w: '腾云驾雾', py: 'téng yún jià wù' },
    { w: '上天入地', py: 'shàng tiān rù dì' },
    { w: '神机妙算', py: 'shén jī miào suàn' },
    { w: '各显神通', py: 'gè xiǎn shén tōng' },
    { w: '三头六臂', py: 'sān tóu liù bì' },
    { w: '神通广大', py: 'shén tōng guǎng dà' },
    { w: '未卜先知', py: 'wèi bǔ xiān zhī' },
    { w: '刀枪不入', py: 'dāo qiāng bú rù' },
  ],
  'u5.sparrow': [
    { w: '麻雀', py: 'má què' },
    { w: '悄悄', py: 'qiāo qiāo' },
    { w: '猛烈', py: 'měng liè' },
    { w: '无可奈何', py: 'wú kě nài hé' },
    { w: '身躯', py: 'shēn qū' },
    { w: '掩护', py: 'yǎn hù' },
    { w: '紧张', py: 'jǐn zhāng' },
    { w: '浑身', py: 'hún shēn' },
    { w: '牺牲', py: 'xī shēng' },
    { w: '庞大', py: 'páng dà' },
    { w: '强大', py: 'qiáng dà' },
    { w: '力量', py: 'lì liàng' },
    { w: '勇气', py: 'yǒng qì' },
    { w: '嗅觉', py: 'xiù jué' },
    { w: '绝望', py: 'jué wàng' },
    { w: '打猎', py: 'dǎ liè' },
  ],
  'u5.tiandu': [
    { w: '假日', py: 'jià rì' },
    { w: '云彩', py: 'yún cai' },
    { w: '石级', py: 'shí jí' },
    { w: '铁链', py: 'tiě liàn' },
    { w: '发颤', py: 'fā chàn' },
    { w: '攀登', py: 'pān dēng' },
    { w: '年纪', py: 'nián jì' },
    { w: '奋力', py: 'fèn lì' },
    { w: '猴子', py: 'hóu zi' },
    { w: '纪念', py: 'jì niàn' },
    { w: '辫子', py: 'biàn zi' },
    { w: '鼓舞', py: 'gǔ wǔ' },
    { w: '居然', py: 'jū rán' },
  ],
  'u5.kaleidoscope': [
    { w: '笑呵呵', py: 'xiào hē hē' },
    { w: '好哩', py: 'hǎo li' },
    { w: '笔陡', py: 'bǐ dǒu' },
    { w: '好险', py: 'hǎo xiǎn' },
    { w: '胀鼓鼓', py: 'zhàng gǔ gǔ' },
    { w: '颤颤巍巍', py: 'chàn chàn wēi wēi' },
    { w: '形影不离', py: 'xíng yǐng bù lí' },
  ],
  'u6.great-wall': [
    { w: '崇山峻岭', py: 'chóng shān jùn lǐng' },
    { w: '盘旋', py: 'pán xuán' },
    { w: '修筑', py: 'xiū zhù' },
    { w: '平整', py: 'píng zhěng' },
    { w: '打仗', py: 'dǎ zhàng' },
    { w: '自然', py: 'zì rán' },
    { w: '当地', py: 'dāng dì' },
    { w: '耗费', py: 'hào fèi' },
    { w: '大量', py: 'dà liàng' },
    { w: '智慧', py: 'zhì huì' },
    { w: '工程', py: 'gōng chéng' },
    { w: '奇迹', py: 'qí jì' },
    { w: '石砖', py: 'shí zhuān' },
    { w: '隔开', py: 'gé kāi' },
    { w: '扶手', py: 'fú shǒu' },
    { w: '建筑', py: 'jiàn zhù' },
  ],
  'u6.summer-palace': [
    { w: '柱子', py: 'zhù zi' },
    { w: '栏杆', py: 'lán gān' },
    { w: '人物', py: 'rén wù' },
    { w: '神清气爽', py: 'shén qīng qì shuǎng' },
    { w: '绕过', py: 'rào guò' },
    { w: '一幅画', py: 'yì fú huà' },
    { w: '栽种', py: 'zāi zhòng' },
    { w: '耸立', py: 'sǒng lì' },
    { w: '半山腰', py: 'bàn shān yāo' },
    { w: '金碧辉煌', py: 'jīn bì huī huáng' },
    { w: '镜子', py: 'jìng zi' },
    { w: '隐隐约约', py: 'yǐn yǐn yuē yuē' },
  ],
  'u6.garden': [
    { w: '游人', py: 'yóu rén' },
    { w: '狮子', py: 'shī zi' },
    { w: '姿态', py: 'zī tài' },
    { w: '陵寝', py: 'líng qǐn' },
    { w: '景观', py: 'jǐng guān' },
    { w: '丝绸', py: 'sī chóu' },
    { w: '拉萨', py: 'lā sà' },
    { w: '廊道', py: 'láng dào' },
    { w: '哈尼族', py: 'hā ní zú' },
    { w: '都江堰', py: 'dū jiāng yàn' },
    { w: '大昭寺', py: 'dà zhāo sì' },
  ],
  'u7.ox-goose': [
    { w: '白鹅', py: 'bái é' },
    { w: '骑行', py: 'qí xíng' },
    { w: '拳头', py: 'quán tou' },
    { w: '横竖', py: 'héng shù' },
    { w: '竟然', py: 'jìng rán' },
    { w: '心胸', py: 'xīn xiōng' },
    { w: '抛鞋', py: 'pāo xié' },
    { w: '胳膊', py: 'gē bo' },
    { w: '握住', py: 'wò zhù' },
    { w: '摔倒', py: 'shuāi dǎo' },
    { w: '虽然', py: 'suī rán' },
    { w: '神气', py: 'shén qì' },
    { w: '欺负', py: 'qī fu' },
    { w: '酒瓶', py: 'jiǔ píng' },
    { w: '顽皮', py: 'wán pí' },
    { w: '恐怖', py: 'kǒng bù' },
    { w: '无所谓', py: 'wú suǒ wèi' },
    { w: '无缘无故', py: 'wú yuán wú gù' },
    { w: '摇摇摆摆', py: 'yáo yáo bǎi bǎi' },
    { w: '凭借', py: 'píng jiè' },
    { w: '指住', py: 'zhǐ zhù' },
    { w: '故意', py: 'gù yì' },
    { w: '扑打', py: 'pū dǎ' },
    { w: '慌乱', py: 'huāng luàn' },
    { w: '助威', py: 'zhù wēi' },
    { w: '结实', py: 'jiē shi' },
    { w: '汉子', py: 'hàn zi' },
    { w: '可笑', py: 'kě xiào' },
    { w: '平台', py: 'píng tái' },
    { w: '摸肚子', py: 'mō dù zi' },
  ],
  'u7.tiger': [
    { w: '文艺', py: 'wén yì' },
    { w: '表演', py: 'biǎo yǎn' },
    { w: '班级', py: 'bān jí' },
    { w: '角色', py: 'jué sè' },
    { w: '笨拙', py: 'bèn zhuō' },
    { w: '期待', py: 'qī dài' },
    { w: '排练', py: 'pái liàn' },
    { w: '主意', py: 'zhǔ yi' },
    { w: '危机', py: 'wēi jī' },
    { w: '充分', py: 'chōng fèn' },
    { w: '自信', py: 'zì xìn' },
    { w: '提示', py: 'tí shì' },
    { w: '演技', py: 'yǎn jì' },
    { w: '等候', py: 'děng hòu' },
    { w: '摘下', py: 'zhāi xià' },
    { w: '推门', py: 'tuī mén' },
    { w: '紧张', py: 'jǐn zhāng' },
    { w: '砸锅', py: 'zá guō' },
    { w: '至今', py: 'zhì jīn' },
    { w: '套上', py: 'tào shang' },
    { w: '逃亡', py: 'táo wáng' },
    { w: '连衣裙', py: 'lián yī qún' },
    { w: '兄妹俩', py: 'xiōng mèi liǎ' },
    { w: '严严实实', py: 'yán yán shí shí' },
    { w: '接连不断', py: 'jiē lián bú duàn' },
    { w: '唉声叹气', py: 'āi shēng tàn qì' },
    { w: '通情达理', py: 'tōng qíng dá lǐ' },
    { w: '哄堂大笑', py: 'hōng táng dà xiào' },
    { w: '垂头丧气', py: 'chuí tóu sàng qì' },
    { w: '事到临头', py: 'shì dào lín tóu' },
  ],
  'u7.garden': [
    { w: '韭菜', py: 'jiǔ cài' },
    { w: '芹菜', py: 'qín cài' },
    { w: '辣椒', py: 'là jiāo' },
    { w: '红薯', py: 'hóng shǔ' },
    { w: '莲藕', py: 'lián ǒu' },
    { w: '芋头', py: 'yù tou' },
    { w: '打头阵', py: 'dǎ tóu zhèn' },
    { w: '挑大梁', py: 'tiǎo dà liáng' },
    { w: '占上风', py: 'zhàn shàng fēng' },
    { w: '破天荒', py: 'pò tiān huāng' },
    { w: '栽跟头', py: 'zāi gēn tou' },
    { w: '敲边鼓', py: 'qiāo biān gǔ' },
    { w: '开绿灯', py: 'kāi lǜ dēng' },
    { w: '碰钉子', py: 'pèng dīng zi' },
  ],
  'u8.selfless': [
    { w: '主席', py: 'zhǔ xí' },
    { w: '举行', py: 'jǔ xíng' },
    { w: '心情', py: 'xīn qíng' },
    { w: '补充', py: 'bǔ chōng' },
    { w: '激动', py: 'jī dòng' },
    { w: '状态', py: 'zhuàng tài' },
    { w: '奉献', py: 'fèng xiàn' },
    { w: '运动员', py: 'yùn dòng yuán' },
    { w: '训练', py: 'xùn liàn' },
    { w: '建设', py: 'jiàn shè' },
    { w: '勤劳', py: 'qín láo' },
    { w: '邀请', py: 'yāo qǐng' },
    { w: '抛出', py: 'pāo chū' },
    { w: '亿万', py: 'yì wàn' },
  ],
  'u8.rise': [
    { w: '崛起', py: 'jué qǐ' },
    { w: '严肃', py: 'yán sù' },
    { w: '干脆', py: 'gān cuì' },
    { w: '默默', py: 'mò mò' },
    { w: '清晰', py: 'qīng xī' },
    { w: '离开', py: 'lí kāi' },
    { w: '随便', py: 'suí biàn' },
    { w: '忘怀', py: 'wàng huái' },
    { w: '非凡', py: 'fēi fán' },
    { w: '惩处', py: 'chéng chǔ' },
    { w: '训斥', py: 'xùn chì' },
    { w: '燃烧', py: 'rán shāo' },
    { w: '响亮', py: 'xiǎng liàng' },
    { w: '模范', py: 'mó fàn' },
    { w: '疑惑不解', py: 'yí huò bù jiě' },
    { w: '轧死', py: 'yà sǐ' },
    { w: '肇事', py: 'zhào shì' },
    { w: '屈辱', py: 'qū rǔ' },
  ],
  'u8.ancient-poems': [
    { w: '催促', py: 'cuī cù' },
    { w: '君子', py: 'jūn zǐ' },
    { w: '征战', py: 'zhēng zhàn' },
    { w: '出塞', py: 'chū sài' },
    { w: '秦朝', py: 'qín cháo' },
    { w: '杰出', py: 'jié chū' },
    { w: '鬼雄', py: 'guǐ xióng' },
    { w: '词语', py: 'cí yǔ' },
    { w: '葡萄', py: 'pú tao' },
    { w: '杯子', py: 'bēi zi' },
    { w: '将领', py: 'jiàng lǐng' },
    { w: '项目', py: 'xiàng mù' },
  ],
  'u8.garden': [
    { w: '志存高远', py: 'zhì cún gāo yuǎn' },
    { w: '精忠报国', py: 'jīng zhōng bào guó' },
    { w: '大义凛然', py: 'dà yì lǐn rán' },
    { w: '英勇无畏', py: 'yīng yǒng wú wèi' },
    { w: '视死如归', py: 'shì sǐ rú guī' },
    { w: '铁面无私', py: 'tiě miàn wú sī' },
    { w: '秉公执法', py: 'bǐng gōng zhí fǎ' },
    { w: '刚正不阿', py: 'gāng zhèng bù ē' },
  ],
};

/**
 * Real words (or accepted variant spellings, or words unfit for children) that the
 * homophone swap would otherwise offer as “wrong” options, e.g. 身份→身分, 懂事→董事, 山峰→山风.
 */
export const YW_G4A_SOUNDALIKE_WORDS: readonly string[] = [
  '身分', '密密', '混浊', '混身', '董事', '山风', '充份', '机动', '一万', '记念',
  '栏干', '酒菜', '结出', '精子', '主义', '奇技',
];
