import type { ChineseBank } from './types';

/**
 * 语文 二年级上册（统编版 2024 修订）第一、二单元：字词与多音字。kp = 知识点 id 去掉 "yw-g2a."
 * 《场景歌》只用各版本转录一致的句子（海鸥、沙滩、军舰、帆船、鱼塘、翠竹、队旗、铜号）。
 */
export const YW_G2A: ChineseBank = {
  items: [
    // ---------------------------------------------------------------- u1.tadpole
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '读音',
      prompt: '「宽」的读音是（　）',
      answer: 'kuān',
      wrong: [
        ['kuāng', 'char-pinyin'],
        ['guān', 'char-pinyin'],
      ],
      explain: '宽读 kuān，是前鼻音，宽大的宽。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '读音',
      prompt: '「脑」的读音是（　）',
      answer: 'nǎo',
      wrong: [
        ['lǎo', 'char-pinyin'],
        ['nào', 'char-pinyin'],
      ],
      explain: '脑读 nǎo，声母是 n，第三声。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '读音',
      prompt: '「蹲」的读音是（　）',
      answer: 'dūn',
      wrong: [
        ['dōng', 'char-pinyin'],
        ['tūn', 'char-pinyin'],
      ],
      explain: '蹲读 dūn，是前鼻音，第一声。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '看拼音选字',
      prompt: 'yǎn jing：眼（　）',
      answer: '睛',
      wrong: [
        ['晴', 'similar-char'],
        ['清', 'similar-char'],
      ],
      explain: '眼睛的睛是目字旁，目就是眼睛。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '反义词',
      prompt: '「前腿」的「前」，反义词是（　）',
      answer: '后',
      wrong: [
        ['上', 'word-usage'],
        ['左', 'word-usage'],
      ],
      explain: '前和后意思相反，小蝌蚪有前腿，也有后腿。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '量词',
      prompt: '池塘里有一（　）小蝌蚪。',
      answer: '群',
      wrong: [
        ['棵', 'word-usage'],
        ['朵', 'word-usage'],
      ],
      explain: '很多小蝌蚪在一起，就是一群小蝌蚪。',
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      kind: '课文理解',
      prompt: '小蝌蚪最先长出来的是（　）',
      answer: '两条后腿',
      wrong: [
        ['两条前腿', 'word-usage'],
        ['宽嘴巴', 'word-usage'],
      ],
      explain: '小蝌蚪先长出两条后腿，再长出两条前腿。',
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      kind: '选词填空',
      prompt: '课文里，小蝌蚪（　）地游来游去。',
      answer: '快活',
      wrong: [
        ['难过', 'word-usage'],
        ['生气', 'word-usage'],
      ],
      explain: '小蝌蚪甩着尾巴，快活地游来游去。',
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      kind: '选词填空',
      prompt: '小蝌蚪看见乌龟，连忙（　）上去叫妈妈。',
      answer: '追',
      wrong: [
        ['迎', 'word-usage'],
        ['跳', 'word-usage'],
      ],
      explain: '乌龟在前面游，小蝌蚪在后面赶，是追上去。',
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      kind: '词语搭配',
      prompt: '青蛙妈妈（　）着碧绿的衣裳。',
      answer: '披',
      wrong: [
        ['露', 'word-usage'],
        ['鼓', 'word-usage'],
      ],
      explain: '课文说青蛙披着碧绿的衣裳，露着雪白的肚皮，鼓着大眼睛。',
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      kind: '形近字',
      prompt: '小青蛙向前一（　），蹦到了荷叶上。',
      answer: '跳',
      wrong: [
        ['桃', 'similar-char'],
        ['挑', 'similar-char'],
      ],
      explain: '跳要用脚，所以是足字旁。',
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      kind: '词义',
      prompt: '「捕食」的意思是（　）',
      answer: '捉东西吃',
      wrong: [
        ['玩捉迷藏', 'word-usage'],
        ['去找妈妈', 'word-usage'],
      ],
      explain: '鲤鱼妈妈教小鲤鱼捕食，就是教它捉东西吃。',
    },
    {
      kp: 'u1.tadpole',
      level: 3,
      kind: '课文理解',
      prompt: '鲤鱼阿姨说，小蝌蚪的妈妈（　）',
      answer: '四条腿，宽嘴巴',
      wrong: [
        ['头顶上有两只大眼睛', 'word-usage'],
        ['甩着长长的尾巴', 'word-usage'],
      ],
      explain: '说“四条腿，宽嘴巴”的是鲤鱼阿姨，说大眼睛的是乌龟。',
    },
    // ---------------------------------------------------------------- u1.what-am-i
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '课文理解',
      prompt: '课文《我是什么》里的“我”是（　）',
      answer: '水',
      wrong: [
        ['太阳', 'word-usage'],
        ['风', 'word-usage'],
      ],
      explain: '水会变成汽、云、雨、冰雹和雪，课文里的“我”是水。',
    },
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '读音',
      prompt: '冰「雹」的「雹」读（　）',
      answer: 'báo',
      wrong: [
        ['páo', 'char-pinyin'],
        ['bāo', 'char-pinyin'],
      ],
      explain: '雹读 báo，声母是 b，第二声。',
    },
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '读音',
      prompt: '「晒」的读音是（　）',
      answer: 'shài',
      wrong: [
        ['sài', 'char-pinyin'],
        ['shǎi', 'char-pinyin'],
      ],
      explain: '晒读 shài，是翘舌音，第四声。',
    },
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '形近字',
      prompt: '冬天，雪花从空中（　）下来。',
      answer: '飘',
      wrong: [
        ['漂', 'similar-char'],
        ['票', 'similar-char'],
      ],
      explain: '在空中随风飘，用风字旁的飘。',
    },
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '看拼音选字',
      prompt: 'tài yáng yí shài：太阳一（　）',
      answer: '晒',
      wrong: [
        ['洒', 'similar-char'],
        ['西', 'similar-char'],
      ],
      explain: '晒要有太阳，所以是日字旁。',
    },
    {
      kp: 'u1.what-am-i',
      level: 1,
      kind: '词义',
      prompt: '「傍晚」是（　）',
      answer: '天快黑的时候',
      wrong: [
        ['天刚亮的时候', 'word-usage'],
        ['中午的时候', 'word-usage'],
      ],
      explain: '傍晚就是太阳快落山、天快黑的时候。',
    },
    {
      kp: 'u1.what-am-i',
      level: 2,
      kind: '选词填空',
      prompt: '有时候，我变成小硬球（　）下来，人们叫我冰雹。',
      answer: '打',
      wrong: [
        ['飘', 'word-usage'],
        ['吹', 'word-usage'],
      ],
      explain: '冰雹又硬又重，是打下来的。',
    },
    {
      kp: 'u1.what-am-i',
      level: 2,
      kind: '反义词',
      prompt: '「温和」的反义词是（　）',
      answer: '暴躁',
      wrong: [
        ['安静', 'word-usage'],
        ['开心', 'word-usage'],
      ],
      explain: '水有时候很温和，有时候很暴躁，这两个词意思相反。',
    },
    {
      kp: 'u1.what-am-i',
      level: 2,
      kind: '课文理解',
      prompt: '下面哪一件是水做的好事？',
      answer: '灌溉田地',
      wrong: [
        ['淹没庄稼', 'word-usage'],
        ['冲毁房屋', 'word-usage'],
      ],
      explain: '灌溉田地是好事，淹没庄稼、冲毁房屋是坏事。',
    },
    {
      kp: 'u1.what-am-i',
      level: 2,
      kind: '词语搭配',
      prompt: '（　）田地',
      answer: '灌溉',
      wrong: [
        ['飘浮', 'word-usage'],
        ['散步', 'word-usage'],
      ],
      explain: '给田地浇水叫灌溉田地。',
    },
    {
      kp: 'u1.what-am-i',
      level: 3,
      kind: '形近字',
      prompt: '小纸船在水面上（　）着。',
      answer: '漂',
      wrong: [
        ['飘', 'similar-char'],
        ['票', 'similar-char'],
      ],
      explain: '在水上用三点水的漂，在空中用风字旁的飘。',
    },
    {
      kp: 'u1.what-am-i',
      level: 3,
      kind: '课文理解',
      prompt: '早晨和傍晚，“我”把什么披在身上？',
      answer: '红袍',
      wrong: [
        ['白衣服', 'word-usage'],
        ['黑衣服', 'word-usage'],
      ],
      explain: '课文说早晨和傍晚，“我”把红袍披在身上。',
    },
    // ---------------------------------------------------------------- u1.plant-mothers
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '读音',
      prompt: '「豌」豆的「豌」读（　）',
      answer: 'wān',
      wrong: [
        ['wǎn', 'char-pinyin'],
        ['wàn', 'char-pinyin'],
      ],
      explain: '豌豆的豌读第一声 wān。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '读音',
      prompt: '「苍」耳的「苍」读（　）',
      answer: 'cāng',
      wrong: [
        ['cān', 'char-pinyin'],
        ['chāng', 'char-pinyin'],
      ],
      explain: '苍读 cāng，是平舌音、后鼻音。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '形近字',
      prompt: '（　）豆妈妈更有办法。',
      answer: '豌',
      wrong: [
        ['碗', 'similar-char'],
        ['婉', 'similar-char'],
      ],
      explain: '豌豆是一种豆子，所以是豆字旁。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '看拼音选字',
      prompt: 'jiàng luò sǎn：降落（　）',
      answer: '伞',
      wrong: [
        ['散', 'similar-char'],
        ['全', 'similar-char'],
      ],
      explain: '降落伞是一种伞，就是雨伞的伞。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '课文理解',
      prompt: '蒲公英妈妈靠（　）送孩子去旅行。',
      answer: '风',
      wrong: [
        ['动物', 'word-usage'],
        ['太阳', 'word-usage'],
      ],
      explain: '有风吹过，蒲公英的孩子就乘着风出发了。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '课文理解',
      prompt: '靠动物帮忙送孩子去旅行的是（　）妈妈。',
      answer: '苍耳',
      wrong: [
        ['蒲公英', 'word-usage'],
        ['豌豆', 'word-usage'],
      ],
      explain: '苍耳的刺能挂住动物的皮毛，靠动物帮忙。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      kind: '反义词',
      prompt: '「粗心」的反义词是（　）',
      answer: '细心',
      wrong: [
        ['开心', 'word-usage'],
        ['伤心', 'word-usage'],
      ],
      explain: '粗心和细心意思相反。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      kind: '读音',
      prompt: '「乘」着风的「乘」读（　）',
      answer: 'chéng',
      wrong: [
        ['chén', 'char-pinyin'],
        ['céng', 'char-pinyin'],
      ],
      explain: '乘读 chéng，是翘舌音、后鼻音。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      kind: '课文理解',
      prompt: '苍耳妈妈给孩子穿上（　）',
      answer: '带刺的铠甲',
      wrong: [
        ['降落伞', 'word-usage'],
        ['绿衣裳', 'word-usage'],
      ],
      explain: '苍耳妈妈给孩子穿上带刺的铠甲。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      kind: '词义',
      prompt: '「纷纷」的意思是（　）',
      answer: '一个接一个，很多',
      wrong: [
        ['只有一个', 'word-usage'],
        ['一动不动', 'word-usage'],
      ],
      explain: '孩子们纷纷出发，就是一个接一个地出发。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      kind: '词义',
      prompt: '「四海为家」的意思是（　）',
      answer: '走到哪里就在哪里安家',
      wrong: [
        ['在大海里安家', 'word-usage'],
        ['有四个家', 'word-usage'],
      ],
      explain: '植物的孩子走到哪里，就在哪里安家。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      kind: '形近字',
      prompt: '植物妈妈有（　）法。',
      answer: '办',
      wrong: [
        ['为', 'similar-char'],
        ['力', 'similar-char'],
      ],
      explain: '办法的办，是“力”的两边各有一点。',
    },
    {
      kp: 'u1.plant-mothers',
      level: 3,
      kind: '形近字',
      prompt: '豌豆妈妈让豆（　）晒在太阳底下。',
      answer: '荚',
      wrong: [
        ['英', 'similar-char'],
        ['夹', 'similar-char'],
      ],
      explain: '豆荚是包着豆子的壳，是草字头下面一个夹。',
    },
    // ---------------------------------------------------------------- u1.fun-animals
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '量词',
      prompt: '一（　）小狗',
      answer: '只',
      wrong: [
        ['棵', 'word-usage'],
        ['朵', 'word-usage'],
      ],
      explain: '小狗、小猫、小鸟都用“只”。棵用在树上，朵用在花上。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '量词',
      prompt: '一（　）大象',
      answer: '头',
      wrong: [
        ['条', 'word-usage'],
        ['棵', 'word-usage'],
      ],
      explain: '大象个子大，可以说一头大象。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '读音',
      prompt: '「趣」的读音是（　）',
      answer: 'qù',
      wrong: [
        ['qǔ', 'char-pinyin'],
        ['jù', 'char-pinyin'],
      ],
      explain: '有趣的趣读 qù，第四声。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '读音',
      prompt: '「问」的读音是（　）',
      answer: 'wèn',
      wrong: [
        ['wèng', 'char-pinyin'],
        ['mèn', 'char-pinyin'],
      ],
      explain: '请问的问读 wèn，是前鼻音。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '看拼音选字',
      prompt: 'qǐng wèn：（　）问',
      answer: '请',
      wrong: [
        ['清', 'similar-char'],
        ['晴', 'similar-char'],
      ],
      explain: '请是言字旁，和说话有关。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '选词填空',
      prompt: '想提问的时候，先说（　），更有礼貌。',
      answer: '请问',
      wrong: [
        ['喂', 'word-usage'],
        ['快说', 'word-usage'],
      ],
      explain: '用“请问”开头提问，最有礼貌。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '课文理解',
      prompt: '别人介绍动物的时候，我们要（　）',
      answer: '认真听',
      wrong: [
        ['大声插话', 'word-usage'],
        ['和同桌说话', 'word-usage'],
      ],
      explain: '别人说话时要认真听，说完了再提问。',
    },
    {
      kp: 'u1.fun-animals',
      level: 1,
      kind: '词义',
      prompt: '「有趣」的意思是（　）',
      answer: '让人觉得好玩',
      wrong: [
        ['让人害怕', 'word-usage'],
        ['让人生气', 'word-usage'],
      ],
      explain: '有趣就是好玩，让人喜欢。',
    },
    {
      kp: 'u1.fun-animals',
      level: 2,
      kind: '形近字',
      prompt: '我喜欢有（　）的动物。',
      answer: '趣',
      wrong: [
        ['取', 'similar-char'],
        ['越', 'similar-char'],
      ],
      explain: '有趣的趣，是走字旁加一个取。',
    },
    {
      kp: 'u1.fun-animals',
      level: 2,
      kind: '形近字',
      prompt: '请（　），青蛙小时候是什么样子？',
      answer: '问',
      wrong: [
        ['间', 'similar-char'],
        ['闷', 'similar-char'],
      ],
      explain: '问是门字框里面一个口，要用嘴巴问。',
    },
    {
      kp: 'u1.fun-animals',
      level: 2,
      kind: '量词',
      prompt: '一（　）鲤鱼',
      answer: '条',
      wrong: [
        ['头', 'word-usage'],
        ['棵', 'word-usage'],
      ],
      explain: '鱼长长的，要用“条”，一条鲤鱼。',
    },
    {
      kp: 'u1.fun-animals',
      level: 3,
      kind: '量词',
      prompt: '下面量词用得对的是（　）',
      answer: '一头牛',
      wrong: [
        ['一头小鸟', 'word-usage'],
        ['一条小猫', 'word-usage'],
      ],
      explain: '牛可以说一头牛；小鸟、小猫都要说一只。',
    },
    // ---------------------------------------------------------------- u2.scene-song
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '量词',
      prompt: '一（　）帆船',
      answer: '条',
      wrong: [
        ['朵', 'word-usage'],
        ['棵', 'word-usage'],
      ],
      explain: '课文里说“一条帆船”。朵用在花上，棵用在树上。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '量词',
      prompt: '一（　）军舰',
      answer: '艘',
      wrong: [
        ['片', 'word-usage'],
        ['座', 'word-usage'],
      ],
      explain: '艘专门用来说船，一艘军舰。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '量词',
      prompt: '一（　）海鸥',
      answer: '只',
      wrong: [
        ['条', 'word-usage'],
        ['片', 'word-usage'],
      ],
      explain: '海鸥是鸟，鸟要用“只”。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '量词',
      prompt: '一（　）沙滩',
      answer: '片',
      wrong: [
        ['只', 'word-usage'],
        ['艘', 'word-usage'],
      ],
      explain: '沙滩又大又平，铺成一大片，所以说一片沙滩。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '读音',
      prompt: '「艘」的读音是（　）',
      answer: 'sōu',
      wrong: [
        ['shōu', 'char-pinyin'],
        ['sāo', 'char-pinyin'],
      ],
      explain: '艘读 sōu，是平舌音。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '看拼音选字',
      prompt: 'hǎi ōu：海（　）',
      answer: '鸥',
      wrong: [
        ['欧', 'similar-char'],
        ['区', 'similar-char'],
      ],
      explain: '海鸥是一种鸟，所以鸥的右边是鸟。',
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      kind: '课文理解',
      prompt: '“一只海鸥，一片沙滩”写的是哪里的景色？',
      answer: '海边',
      wrong: [
        ['森林', 'word-usage'],
        ['操场', 'word-usage'],
      ],
      explain: '海鸥、沙滩、军舰、帆船，都在海边。',
    },
    {
      kp: 'u2.scene-song',
      level: 2,
      kind: '量词',
      prompt: '一（　）鱼塘',
      answer: '方',
      wrong: [
        ['条', 'word-usage'],
        ['只', 'word-usage'],
      ],
      explain: '鱼塘方方正正的，课文里说一方鱼塘。',
    },
    {
      kp: 'u2.scene-song',
      level: 2,
      kind: '量词',
      prompt: '一（　）铜号',
      answer: '把',
      wrong: [
        ['面', 'word-usage'],
        ['片', 'word-usage'],
      ],
      explain: '课文里说“一面队旗，一把铜号”。',
    },
    {
      kp: 'u2.scene-song',
      level: 2,
      kind: '量词',
      prompt: '一（　）翠竹',
      answer: '丛',
      wrong: [
        ['孔', 'word-usage'],
        ['艘', 'word-usage'],
      ],
      explain: '竹子长在一起，一丛一丛的，说一丛翠竹。',
    },
    {
      kp: 'u2.scene-song',
      level: 2,
      kind: '形近字',
      prompt: '海上有一条（　）船。',
      answer: '帆',
      wrong: [
        ['凡', 'similar-char'],
        ['巾', 'similar-char'],
      ],
      explain: '帆是用布做的，左边是巾字旁，右边是凡。',
    },
    {
      kp: 'u2.scene-song',
      level: 2,
      kind: '词义',
      prompt: '「场景」的意思是（　）',
      answer: '眼睛看到的一幅画面',
      wrong: [
        ['一个大操场', 'word-usage'],
        ['一首好听的歌', 'word-usage'],
      ],
      explain: '场景就是我们看到的一幅画面。',
    },
    {
      kp: 'u2.scene-song',
      level: 3,
      kind: '量词',
      prompt: '下面数量词搭配正确的是（　）',
      answer: '一艘军舰',
      wrong: [
        ['一艘海鸥', 'word-usage'],
        ['一片帆船', 'word-usage'],
      ],
      explain: '船用艘；海鸥要说一只，帆船要说一条。',
    },
    {
      kp: 'u2.scene-song',
      level: 3,
      kind: '读音',
      prompt: '「场景」的「场」读（　）',
      answer: 'chǎng',
      wrong: [
        ['cháng', 'char-pinyin'],
        ['chāng', 'char-pinyin'],
      ],
      explain: '场景的场读第三声 chǎng，和操场的场一样。',
    },
    // ---------------------------------------------------------------- u2.tree-song
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '形近字',
      prompt: '（　）树秋天叶儿红。',
      answer: '枫',
      wrong: [
        ['风', 'similar-char'],
        ['疯', 'similar-char'],
      ],
      explain: '枫树是一种树，所以是木字旁的“枫”。',
    },
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '读音',
      prompt: '「杨」的读音是（　）',
      answer: 'yáng',
      wrong: [
        ['yǎng', 'char-pinyin'],
        ['yán', 'char-pinyin'],
      ],
      explain: '杨读 yáng，是后鼻音，第二声。',
    },
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '看拼音选字',
      prompt: 'sōng shù：（　）树',
      answer: '松',
      wrong: [
        ['公', 'similar-char'],
        ['送', 'similar-char'],
      ],
      explain: '松树是树，木字旁加一个公。',
    },
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '看拼音选字',
      prompt: 'róng shù：（　）树',
      answer: '榕',
      wrong: [
        ['容', 'similar-char'],
        ['溶', 'similar-char'],
      ],
      explain: '榕树是树，所以是木字旁。',
    },
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '课文理解',
      prompt: '梧桐树叶像（　）',
      answer: '手掌',
      wrong: [
        ['扇子', 'word-usage'],
        ['雪花', 'word-usage'],
      ],
      explain: '课文说“梧桐树叶像手掌”。',
    },
    {
      kp: 'u2.tree-song',
      level: 1,
      kind: '反义词',
      prompt: '「南方」的反义词是（　）',
      answer: '北方',
      wrong: [
        ['东方', 'word-usage'],
        ['上方', 'word-usage'],
      ],
      explain: '南方和北方意思相反，木棉在南方，桦树守北疆。',
    },
    {
      kp: 'u2.tree-song',
      level: 2,
      kind: '读音',
      prompt: '松「柏」的「柏」读（　）',
      answer: 'bǎi',
      wrong: [
        ['bái', 'char-pinyin'],
        ['pǎi', 'char-pinyin'],
      ],
      explain: '松柏的柏读第三声 bǎi。',
    },
    {
      kp: 'u2.tree-song',
      level: 2,
      kind: '课文理解',
      prompt: '儿歌里，（　）喜暖在南方。',
      answer: '木棉',
      wrong: [
        ['桦树', 'word-usage'],
        ['松柏', 'word-usage'],
      ],
      explain: '木棉喜欢温暖，长在南方；桦树不怕冷，守着北疆。',
    },
    {
      kp: 'u2.tree-song',
      level: 2,
      kind: '形近字',
      prompt: '梧（　）树叶像手掌。',
      answer: '桐',
      wrong: [
        ['洞', 'similar-char'],
        ['铜', 'similar-char'],
      ],
      explain: '梧桐是树，所以是木字旁。',
    },
    {
      kp: 'u2.tree-song',
      level: 2,
      kind: '形近字',
      prompt: '金（　）开花满院香。',
      answer: '桂',
      wrong: [
        ['挂', 'similar-char'],
        ['佳', 'similar-char'],
      ],
      explain: '桂花树是树，所以是木字旁。',
    },
    {
      kp: 'u2.tree-song',
      level: 2,
      kind: '词义',
      prompt: '「耐寒」的意思是（　）',
      answer: '不怕冷',
      wrong: [
        ['不怕热', 'word-usage'],
        ['很怕冷', 'word-usage'],
      ],
      explain: '耐寒就是不怕冷，桦树耐寒守北疆。',
    },
    {
      kp: 'u2.tree-song',
      level: 3,
      kind: '形近字',
      prompt: '（　）杏水杉活化石。',
      answer: '银',
      wrong: [
        ['很', 'similar-char'],
        ['跟', 'similar-char'],
      ],
      explain: '银杏是一种树，银是金字旁。',
    },
    {
      kp: 'u2.tree-song',
      level: 3,
      kind: '课文理解',
      prompt: '一年四季都是绿绿的，是（　）',
      answer: '松柏',
      wrong: [
        ['枫树', 'word-usage'],
        ['桦树', 'word-usage'],
      ],
      explain: '课文说“松柏四季披绿装”。',
    },
    // ---------------------------------------------------------------- u2.clap-song
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '看拼音选字',
      prompt: 'huáng lí：黄（　）',
      answer: '鹂',
      wrong: [
        ['丽', 'similar-char'],
        ['莉', 'similar-char'],
      ],
      explain: '黄鹂是一种鸟，所以带“鸟”字。',
    },
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '读音',
      prompt: '锦鸡的「锦」读（　）',
      answer: 'jǐn',
      wrong: [
        ['jīn', 'char-pinyin'],
        ['jìn', 'char-pinyin'],
      ],
      explain: '锦读 jǐn，第三声，左边是金字旁。',
    },
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '读音',
      prompt: '「雁」的读音是（　）',
      answer: 'yàn',
      wrong: [
        ['yān', 'char-pinyin'],
        ['yàng', 'char-pinyin'],
      ],
      explain: '雁读 yàn，是前鼻音，第四声。',
    },
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '看拼音选字',
      prompt: 'xióng yīng：雄（　）',
      answer: '鹰',
      wrong: [
        ['应', 'similar-char'],
        ['英', 'similar-char'],
      ],
      explain: '鹰是一种鸟，下面有个鸟字。',
    },
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '课文理解',
      prompt: '儿歌里说，孔雀和（　）是伙伴。',
      answer: '锦鸡',
      wrong: [
        ['雄鹰', 'word-usage'],
        ['熊猫', 'word-usage'],
      ],
      explain: '课文说“孔雀锦鸡是伙伴”。',
    },
    {
      kp: 'u2.clap-song',
      level: 1,
      kind: '词义',
      prompt: '「嬉戏」的意思是（　）',
      answer: '开心地玩耍',
      wrong: [
        ['大口吃东西', 'word-usage'],
        ['睡大觉', 'word-usage'],
      ],
      explain: '熊猫在竹林里嬉戏，就是开心地玩。',
    },
    {
      kp: 'u2.clap-song',
      level: 2,
      kind: '课文理解',
      prompt: '儿歌里说，丛林深处有（　）',
      answer: '猛虎',
      wrong: [
        ['熊猫', 'word-usage'],
        ['孔雀', 'word-usage'],
      ],
      explain: '课文说“丛林深处有猛虎”，熊猫在竹林里。',
    },
    {
      kp: 'u2.clap-song',
      level: 2,
      kind: '课文理解',
      prompt: '「天空雁群会写字」，是说大雁（　）',
      answer: '飞的时候排成“人”字或“一”字',
      wrong: [
        ['会拿笔写字', 'word-usage'],
        ['在天上画画', 'word-usage'],
      ],
      explain: '大雁排队飞，像在天空写字。',
    },
    {
      kp: 'u2.clap-song',
      level: 2,
      kind: '形近字',
      prompt: '黄鹂百灵唱不（　）',
      answer: '休',
      wrong: [
        ['体', 'similar-char'],
        ['林', 'similar-char'],
      ],
      explain: '唱不休就是唱个不停，休是单人旁加一个木。',
    },
    {
      kp: 'u2.clap-song',
      level: 2,
      kind: '量词',
      prompt: '天空飞过一（　）大雁。',
      answer: '群',
      wrong: [
        ['头', 'word-usage'],
        ['棵', 'word-usage'],
      ],
      explain: '很多大雁在一起飞，是一群大雁。',
    },
    {
      kp: 'u2.clap-song',
      level: 3,
      kind: '形近字',
      prompt: '下面哪个字里的「鸟」在下面？',
      answer: '鹰',
      wrong: [
        ['鸡', 'similar-char'],
        ['鹂', 'similar-char'],
        ['鸥', 'similar-char'],
      ],
      explain: '鹰的鸟在下面，鸡、鹂、鸥的鸟在右边。',
    },
    {
      kp: 'u2.clap-song',
      level: 3,
      kind: '同音字',
      prompt: '竹林熊猫在嬉（　）',
      answer: '戏',
      wrong: [
        ['细', 'similar-char'],
        ['系', 'similar-char'],
      ],
      explain: '嬉戏是玩耍，是游戏的戏。',
    },
    // ---------------------------------------------------------------- u2.farm-seasons
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '词义',
      prompt: '「农事」的意思是（　）',
      answer: '种田的事情',
      wrong: [
        ['农民的故事', 'word-usage'],
        ['农村的节日', 'word-usage'],
      ],
      explain: '农事就是种田、收粮这些农活。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '读音',
      prompt: '「季」的读音是（　）',
      answer: 'jì',
      wrong: [
        ['jǐ', 'char-pinyin'],
        ['zì', 'char-pinyin'],
      ],
      explain: '季读 jì，第四声。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '读音',
      prompt: '「秧」的读音是（　）',
      answer: 'yāng',
      wrong: [
        ['yān', 'char-pinyin'],
        ['yáng', 'char-pinyin'],
      ],
      explain: '秧读 yāng，是后鼻音，第一声。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '形近字',
      prompt: '春（　）里，春风吹。',
      answer: '季',
      wrong: [
        ['李', 'similar-char'],
        ['秀', 'similar-char'],
      ],
      explain: '季的上面是禾，下面是子。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '课文理解',
      prompt: '农民采桑、插秧，是在（　）',
      answer: '夏季',
      wrong: [
        ['秋季', 'word-usage'],
        ['冬季', 'word-usage'],
      ],
      explain: '课文说夏季里农事忙，采了蚕桑又插秧。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      kind: '反义词',
      prompt: '「早起」的「早」，反义词是（　）',
      answer: '晚',
      wrong: [
        ['快', 'word-usage'],
        ['高', 'word-usage'],
      ],
      explain: '早和晚意思相反。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      kind: '课文理解',
      prompt: '冬季里，农民穿上了（　）',
      answer: '新棉衣',
      wrong: [
        ['花裙子', 'word-usage'],
        ['新凉鞋', 'word-usage'],
      ],
      explain: '课文说冬季里“新制棉衣暖又轻”。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      kind: '词义',
      prompt: '「插秧」是（　）',
      answer: '把秧苗插到水田里',
      wrong: [
        ['把花插到瓶子里', 'word-usage'],
        ['给麦苗浇水', 'word-usage'],
      ],
      explain: '插秧就是把一棵棵秧苗插进水田里。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      kind: '选词填空',
      prompt: '麦苗儿多（　），桑叶儿正肥。',
      answer: '嫩',
      wrong: [
        ['老', 'word-usage'],
        ['硬', 'word-usage'],
      ],
      explain: '春天的麦苗刚长出来，又嫩又软。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      kind: '同音字',
      prompt: '夏季里，农事（　）',
      answer: '忙',
      wrong: [
        ['芒', 'similar-char'],
        ['盲', 'similar-char'],
      ],
      explain: '忙是竖心旁，农民每天都很忙。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      kind: '词义',
      prompt: '「笑盈盈」的意思是（　）',
      answer: '满脸都是笑',
      wrong: [
        ['哭得很伤心', 'word-usage'],
        ['生气地大叫', 'word-usage'],
      ],
      explain: '一年农事做完了，大家满脸都是笑。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 3,
      kind: '同音字',
      prompt: '秋季里，稻上场，（　）像黄金粒粒香。',
      answer: '谷',
      wrong: [
        ['古', 'similar-char'],
        ['骨', 'similar-char'],
      ],
      explain: '稻谷的谷，金黄金黄的像黄金。',
    },
    {
      kp: 'u2.farm-seasons',
      level: 3,
      kind: '形近字',
      prompt: '夏季里，采了（　）桑又插秧。',
      answer: '蚕',
      wrong: [
        ['吞', 'similar-char'],
        ['天', 'similar-char'],
      ],
      explain: '蚕宝宝是小虫子，所以蚕的下面是虫。',
    },
  ],
  polyphones: [
    {
      kp: 'u1.tadpole',
      level: 1,
      char: '长',
      readings: [
        { pinyin: 'cháng', meaning: '两头离得远，和“短”相反', words: ['长短', '很长', '长江'] },
        { pinyin: 'zhǎng', meaning: '生出来；变大', words: ['长大', '长高', '生长'] },
      ],
      sentences: [{ text: '小蝌蚪「长」出了两条后腿。', pinyin: 'zhǎng' }],
    },
    {
      kp: 'u1.tadpole',
      level: 2,
      char: '教',
      readings: [
        { pinyin: 'jiāo', meaning: '把本领传给别人', words: ['教书', '教给'] },
        { pinyin: 'jiào', meaning: '和上课、学习有关', words: ['教室', '教师'] },
      ],
      sentences: [{ text: '鲤鱼妈妈在「教」小鲤鱼捕食。', pinyin: 'jiāo' }],
    },
    {
      kp: 'u1.tadpole',
      level: 1,
      char: '地',
      readings: [
        { pinyin: 'de', meaning: '用在词语后面，说怎么做', words: ['快活地', '慢慢地', '轻轻地'] },
        { pinyin: 'dì', meaning: '土地、地面', words: ['地上', '田地', '草地'] },
      ],
      sentences: [{ text: '小蝌蚪快活「地」游来游去。', pinyin: 'de' }],
    },
    {
      kp: 'u1.what-am-i',
      level: 2,
      char: '空',
      readings: [
        { pinyin: 'kōng', meaning: '天空；里面没有东西', words: ['天空', '空中', '空瓶子'] },
        { pinyin: 'kòng', meaning: '闲着的时间或地方', words: ['有空', '空地'] },
      ],
      sentences: [{ text: '我升到天「空」，变成了云。', pinyin: 'kōng' }],
    },
    {
      kp: 'u1.plant-mothers',
      level: 3,
      char: '得',
      readings: [
        { pinyin: 'děi', meaning: '必须、应该', words: ['就得走', '我得去'] },
        { pinyin: 'dé', meaning: '拿到、得到', words: ['得到', '得奖'] },
        { pinyin: 'de', meaning: '用在做事的词后面，说做得怎么样', words: ['跑得快', '说得好'] },
      ],
      sentences: [
        { text: '孩子长大了，就「得」告别妈妈。', pinyin: 'děi' },
        { text: '粗心的小朋友却「得」不到它。', pinyin: 'dé' },
      ],
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      char: '为',
      readings: [
        { pinyin: 'wéi', meaning: '当作、成为', words: ['四海为家', '成为'] },
        { pinyin: 'wèi', meaning: '为了；因为', words: ['为什么', '因为'] },
      ],
      sentences: [{ text: '孩子们长大了，要四海「为」家。', pinyin: 'wéi' }],
    },
    {
      kp: 'u1.plant-mothers',
      level: 1,
      char: '炸',
      readings: [
        { pinyin: 'zhà', meaning: '突然破开', words: ['炸开', '爆炸'] },
        { pinyin: 'zhá', meaning: '放在热油里做熟', words: ['炸鸡', '油炸'] },
      ],
      sentences: [{ text: '啪的一声，豆荚「炸」开了。', pinyin: 'zhà' }],
    },
    {
      kp: 'u1.plant-mothers',
      level: 2,
      char: '行',
      readings: [
        { pinyin: 'xíng', meaning: '走；可以', words: ['旅行', '步行', '不行'] },
        { pinyin: 'háng', meaning: '排成的一排；也用在银行里', words: ['一行字', '银行'] },
      ],
      sentences: [{ text: '植物妈妈送孩子去旅「行」。', pinyin: 'xíng' }],
    },
    {
      kp: 'u2.scene-song',
      level: 1,
      char: '只',
      readings: [
        { pinyin: 'zhī', meaning: '用来数动物', words: ['一只', '两只'] },
        { pinyin: 'zhǐ', meaning: '仅仅', words: ['只要', '只有'] },
      ],
      sentences: [{ text: '沙滩上飞来一「只」海鸥。', pinyin: 'zhī' }],
    },
    {
      kp: 'u2.clap-song',
      level: 2,
      char: '处',
      readings: [
        { pinyin: 'chù', meaning: '地方', words: ['深处', '到处', '住处'] },
        { pinyin: 'chǔ', meaning: '和别人在一起；办事情', words: ['相处', '处理'] },
      ],
      sentences: [{ text: '丛林深「处」住着猛虎。', pinyin: 'chù' }],
    },
    {
      kp: 'u2.farm-seasons',
      level: 1,
      char: '了',
      readings: [
        { pinyin: 'le', meaning: '用在词语后面，表示事情做完了', words: ['走了', '吃了'] },
        { pinyin: 'liǎo', meaning: '结束、完了；明白', words: ['了解', '了不起'] },
      ],
      sentences: [
        { text: '一年农事「了」，大家笑盈盈。', pinyin: 'liǎo' },
        { text: '夏季里，采「了」蚕桑又插秧。', pinyin: 'le' },
      ],
    },
    {
      kp: 'u2.farm-seasons',
      level: 2,
      char: '场',
      readings: [
        {
          pinyin: 'cháng',
          meaning: '晒粮食、打谷的平地；也用来数一次风雨',
          words: ['场院', '一场雨'],
        },
        { pinyin: 'chǎng', meaning: '许多人活动的地方', words: ['操场', '广场', '场景'] },
      ],
      sentences: [{ text: '秋季里，稻上「场」。', pinyin: 'cháng' }],
    },
  ],
};
