import type { DictationList } from './types';

/**
 * 语文 二年级上册 词语听写表 (from the class's handout the parent photographed),
 * by lesson knowledge point. Pinyin as printed in the textbook: 一/不 with their changed tones,
 * neutral tones as in 现代汉语词典 (妈妈 mā ma, 休息 xiū xi, 哪里 nǎ li), 儿化 written as a toneless 「er」
 * so every character has one syllable.
 */
export const YW_G2A_WORDS: DictationList = {
  'u1.tadpole': [
    { w: '两条', py: 'liǎng tiáo' },
    { w: '哪里', py: 'nǎ li' },
    { w: '宽广', py: 'kuān guǎng' },
    { w: '长短', py: 'cháng duǎn' },
    { w: '那边', py: 'nà bian' },
    { w: '孩子', py: 'hái zi' },
    { w: '变成', py: 'biàn chéng' },
    { w: '妈妈', py: 'mā ma' },
    { w: '他们', py: 'tā men' },
    { w: '看见', py: 'kàn jiàn' },
    { w: '我们', py: 'wǒ men' },
    { w: '雪白', py: 'xuě bái' },
    { w: '过去', py: 'guò qù' },
    { w: '什么', py: 'shén me' },
  ],
  'u1.what-am-i': [
    { w: '一起', py: 'yì qǐ' },
    { w: '海洋', py: 'hǎi yáng' },
    { w: '工作', py: 'gōng zuò' },
    { w: '办法', py: 'bàn fǎ' },
    { w: '许多', py: 'xǔ duō' },
    { w: '连忙', py: 'lián máng' },
    { w: '太阳', py: 'tài yáng' },
    { w: '天空', py: 'tiān kōng' },
    { w: '冬天', py: 'dōng tiān' },
    { w: '花朵', py: 'huā duǒ' },
    { w: '池子', py: 'chí zi' },
    { w: '江河', py: 'jiāng hé' },
    { w: '田地', py: 'tián dì' },
    { w: '你们', py: 'nǐ men' },
  ],
  'u1.plant-mothers': [
    { w: '如果', py: 'rú guǒ' },
    { w: '已经', py: 'yǐ jīng' },
    { w: '告别', py: 'gào bié' },
    { w: '出发', py: 'chū fā' },
    { w: '知识', py: 'zhī shi' },
    { w: '胆子', py: 'dǎn zi' },
    { w: '肚子', py: 'dù zi' },
    { w: '轻轻', py: 'qīng qīng' },
    { w: '那里', py: 'nà li' },
    { w: '自己', py: 'zì jǐ' },
    { w: '动物', py: 'dòng wù' },
    { w: '四海为家', py: 'sì hǎi wéi jiā' },
  ],
  'u1.garden': [
    { w: '转身', py: 'zhuǎn shēn' },
    { w: '夹杂', py: 'jiā zá' },
  ],
  'u2.scene-song': [
    { w: '深处', py: 'shēn chù' },
    { w: '花园', py: 'huā yuán' },
    { w: '一块', py: 'yí kuài' },
    { w: '一座', py: 'yí zuò' },
    { w: '石桥', py: 'shí qiáo' },
    { w: '一群', py: 'yì qún' },
    { w: '队旗', py: 'duì qí' },
    { w: '铜号', py: 'tóng hào' },
    { w: '红领巾', py: 'hóng lǐng jīn' },
    { w: '飞鸟', py: 'fēi niǎo' },
    { w: '欢笑', py: 'huān xiào' },
  ],
  'u2.tree-song': [
    { w: '杨树', py: 'yáng shù' },
    { w: '强壮', py: 'qiáng zhuàng' },
    { w: '梧桐', py: 'wú tóng' },
    { w: '枫树', py: 'fēng shù' },
    { w: '松柏', py: 'sōng bǎi' },
    { w: '木棉', py: 'mù mián' },
    { w: '水杉', py: 'shuǐ shān' },
    { w: '化石', py: 'huà shí' },
    { w: '金桂', py: 'jīn guì' },
    { w: '树叶', py: 'shù yè' },
    { w: '开花', py: 'kāi huā' },
  ],
  'u2.clap-song': [
    { w: '拍手', py: 'pāi shǒu' },
    { w: '世界', py: 'shì jiè' },
    { w: '云彩', py: 'yún cai' },
    { w: '丛林', py: 'cóng lín' },
    { w: '休息', py: 'xiū xi' },
    { w: '竹林', py: 'zhú lín' },
    { w: '朋友', py: 'péng you' },
    { w: '保护', py: 'bǎo hù' },
  ],
  'u2.farm-seasons': [
    { w: '四季', py: 'sì jì' },
    { w: '春风', py: 'chūn fēng' },
    { w: '月光', py: 'yuè guāng' },
    { w: '身体', py: 'shēn tǐ' },
    { w: '心里', py: 'xīn li' },
    { w: '大家', py: 'dà jiā' },
    { w: '肥料', py: 'féi liào' },
    { w: '农事', py: 'nóng shì' },
    { w: '赶忙', py: 'gǎn máng' },
    { w: '归来', py: 'guī lái' },
    { w: '穿戴', py: 'chuān dài' },
    { w: '辛苦', py: 'xīn kǔ' },
    { w: '谷子', py: 'gǔ zi' },
    { w: '年初', py: 'nián chū' },
  ],
  'u2.garden-2': [
    { w: '美丑', py: 'měi chǒu' },
    { w: '真诚', py: 'zhēn chéng' },
  ],
  'u3.rainbow': [
    { w: '天上', py: 'tiān shàng' },
    { w: '美丽', py: 'měi lì' },
    { w: '爸爸', py: 'bà ba' },
    { w: '下来', py: 'xià lái' },
    { w: '不用', py: 'bú yòng' },
    { w: '高兴', py: 'gāo xìng' },
    { w: '哥哥', py: 'gē ge' },
    { w: '秋千', py: 'qiū qiān' },
    { w: '彩云', py: 'cǎi yún' },
    { w: '提出', py: 'tí chū' },
    { w: '是吗', py: 'shì ma' },
    { w: '圆形', py: 'yuán xíng' },
    { w: '加挂', py: 'jiā guà' },
    { w: '好啊', py: 'hǎo a' },
  ],
  'u3.grandma-house': [
    { w: '宝贝', py: 'bǎo bèi' },
    { w: '干活', py: 'gàn huó' },
    { w: '回来', py: 'huí lái' },
    { w: '一些', py: 'yì xiē' },
    { w: '天气', py: 'tiān qì' },
    { w: '欢快', py: 'huān kuài' },
    { w: '它们', py: 'tā men' },
    { w: '告诉', py: 'gào su' },
    { w: '名字', py: 'míng zi' },
    { w: '出门', py: 'chū mén' },
    { w: '好玩', py: 'hǎo wán' },
    { w: '不是', py: 'bú shì' },
    { w: '小曲', py: 'xiǎo qǔ' },
    { w: '送给', py: 'sòng gěi' },
    { w: '香气', py: 'xiāng qì' },
  ],
  'u3.star-counter': [
    { w: '星星', py: 'xīng xing' },
    { w: '晚上', py: 'wǎn shang' },
    { w: '无数', py: 'wú shù' },
    { w: '奶奶', py: 'nǎi nai' },
    { w: '中间', py: 'zhōng jiān' },
    { w: '总是', py: 'zǒng shì' },
    { w: '爷爷', py: 'yé ye' },
    { w: '北边', py: 'běi bian' },
    { w: '勺子', py: 'sháo zi' },
    { w: '转动', py: 'zhuàn dòng' },
    { w: '这个', py: 'zhè ge' },
    { w: '后来', py: 'hòu lái' },
    { w: '您好', py: 'nín hǎo' },
    { w: '很多', py: 'hěn duō' },
    { w: '汉代', py: 'hàn dài' },
    { w: '变化', py: 'biàn huà' },
  ],
  'u3.garden-3': [
    { w: '图形', py: 'tú xíng' },
    { w: '泥土', py: 'ní tǔ' },
    { w: '铁环', py: 'tiě huán' },
  ],
  'u4.poems': [
    { w: '依靠', py: 'yī kào' },
    { w: '尽头', py: 'jìn tóu' },
    { w: '无穷', py: 'wú qióng' },
    { w: '一层', py: 'yì céng' },
    { w: '光照', py: 'guāng zhào' },
    { w: '香炉', py: 'xiāng lú' },
    { w: '浓烟', py: 'nóng yān' },
    { w: '山川', py: 'shān chuān' },
    { w: '直线', py: 'zhí xiàn' },
    { w: '银河', py: 'yín hé' },
  ],
  'u4.huangshan': [
    { w: '仙人', py: 'xiān rén' },
    { w: '仙女', py: 'xiān nǚ' },
    { w: '山头', py: 'shān tóu' },
    { w: '山顶', py: 'shān dǐng' },
    { w: '巨人', py: 'jù rén' },
    { w: '一位', py: 'yí wèi' },
    { w: '金光闪闪', py: 'jīn guāng shǎn shǎn' },
    { w: '黄狗', py: 'huáng gǒu' },
    { w: '形状', py: 'xíng zhuàng' },
    { w: '那些', py: 'nà xiē' },
    { w: '云海', py: 'yún hǎi' },
    { w: '前方', py: 'qián fāng' },
  ],
  'u4.sun-moon-lake': [
    { w: '湖水', py: 'hú shuǐ' },
    { w: '山区', py: 'shān qū' },
    { w: '群山', py: 'qún shān' },
    { w: '树木', py: 'shù mù' },
    { w: '灯光', py: 'dēng guāng' },
    { w: '中午', py: 'zhōng wǔ' },
    { w: '眼前', py: 'yǎn qián' },
    { w: '细雨', py: 'xì yǔ' },
    { w: '风光', py: 'fēng guāng' },
    { w: '名胜古迹', py: 'míng shèng gǔ jì' },
    { w: '小岛', py: 'xiǎo dǎo' },
    { w: '弯弯', py: 'wān wān' },
    { w: '展现', py: 'zhǎn xiàn' },
    { w: '就像', py: 'jiù xiàng' },
    { w: '中外', py: 'zhōng wài' },
  ],
  'u4.grape-valley': [
    { w: '地方', py: 'dì fang' },
    { w: '水果', py: 'shuǐ guǒ' },
    { w: '月份', py: 'yuè fèn' },
    { w: '枝叶', py: 'zhī yè' },
    { w: '五光十色', py: 'wǔ guāng shí sè' },
    { w: '好客', py: 'hào kè' },
    { w: '老乡', py: 'lǎo xiāng' },
    { w: '有的', py: 'yǒu de' },
    { w: '城市', py: 'chéng shì' },
    { w: '空气', py: 'kōng qì' },
    { w: '水分', py: 'shuǐ fèn' },
    { w: '这里', py: 'zhè li' },
    { w: '小孔', py: 'xiǎo kǒng' },
    { w: '钉着', py: 'dìng zhe' },
    { w: '味道', py: 'wèi dao' },
    { w: '有名', py: 'yǒu míng' },
  ],
  'u4.garden-4': [
    { w: '号码', py: 'hào mǎ' },
    { w: '丰收', py: 'fēng shōu' },
  ],
  'u5.well-frog': [
    { w: '哪儿', py: 'nǎ er' },
    { w: '不过', py: 'bú guò' },
    { w: '那么', py: 'nà me' },
    { w: '观看', py: 'guān kàn' },
    { w: '回答', py: 'huí dá' },
    { w: '口渴', py: 'kǒu kě' },
    { w: '喝水', py: 'hē shuǐ' },
    { w: '大话', py: 'dà huà' },
    { w: '坐井观天', py: 'zuò jǐng guān tiān' },
    { w: '抬头', py: 'tái tóu' },
    { w: '相信', py: 'xiāng xìn' },
    { w: '好呀', py: 'hǎo ya' },
    { w: '能力', py: 'néng lì' },
  ],
  'u5.hanhao-bird': [
    { w: '当作', py: 'dàng zuò' },
    { w: '前面', py: 'qián mian' },
    { w: '出去', py: 'chū qù' },
    { w: '过冬', py: 'guò dōng' },
    { w: '知道', py: 'zhī dào' },
    { w: '赶快', py: 'gǎn kuài' },
    { w: '正好', py: 'zhèng hǎo' },
    { w: '明天', py: 'míng tiān' },
    { w: '清早', py: 'qīng zǎo' },
    { w: '好像', py: 'hǎo xiàng' },
    { w: '一样', py: 'yí yàng' },
    { w: '天亮', py: 'tiān liàng' },
    { w: '出来', py: 'chū lái' },
    { w: '一阵', py: 'yí zhèn' },
    { w: '冰冻', py: 'bīng dòng' },
    { w: '做饭', py: 'zuò fàn' },
    { w: '第一', py: 'dì yī' },
    { w: '寒冷', py: 'hán lěng' },
  ],
  'u5.gourd': [
    { w: '种树', py: 'zhòng shù' },
    { w: '以后', py: 'yǐ hòu' },
    { w: '梦想', py: 'mèng xiǎng' },
    { w: '居住', py: 'jū zhù' },
    { w: '一棵', py: 'yì kē' },
    { w: '次序', py: 'cì xù' },
    { w: '好吧', py: 'hǎo ba' },
    { w: '奇怪', py: 'qí guài' },
    { w: '邻居', py: 'lín jū' },
    { w: '从前', py: 'cóng qián' },
    { w: '多么', py: 'duō me' },
    { w: '那个', py: 'nà ge' },
    { w: '叶子', py: 'yè zi' },
    { w: '虫子', py: 'chóng zi' },
    { w: '自言自语', py: 'zì yán zì yǔ' },
  ],
  'u5.garden-5': [
    { w: '货物', py: 'huò wù' },
    { w: '科学', py: 'kē xué' },
  ],
  'u6.bajiao-tower': [
    { w: '八角楼', py: 'bā jiǎo lóu' },
    { w: '年代', py: 'nián dài' },
    { w: '穿着', py: 'chuān zhe' },
    { w: '明亮', py: 'míng liàng' },
    { w: '星星之火', py: 'xīng xīng zhī huǒ' },
    { w: '凝视', py: 'níng shì' },
    { w: '中国', py: 'zhōng guó' },
    { w: '胜利', py: 'shèng lì' },
    { w: '道路', py: 'dào lù' },
  ],
  'u6.zhude-pole': [
    { w: '同志', py: 'tóng zhì' },
    { w: '红军', py: 'hóng jūn' },
    { w: '敌人', py: 'dí rén' },
    { w: '生产', py: 'shēng chǎn' },
    { w: '常常', py: 'cháng cháng' },
    { w: '来回', py: 'lái huí' },
    { w: '非常', py: 'fēi cháng' },
    { w: '每次', py: 'měi cì' },
    { w: '一块儿', py: 'yí kuài er' },
    { w: '战士', py: 'zhàn shì' },
    { w: '白天', py: 'bái tiān' },
    { w: '戴着', py: 'dài zhe' },
  ],
  'u6.water-festival': [
    { w: '难忘', py: 'nán wàng' },
    { w: '火红', py: 'huǒ hóng' },
    { w: '人民', py: 'rén mín' },
    { w: '因为', py: 'yīn wèi' },
    { w: '总理', py: 'zǒng lǐ' },
    { w: '人们', py: 'rén men' },
    { w: '四面八方', py: 'sì miàn bā fāng' },
    { w: '为了', py: 'wèi le' },
    { w: '一串串', py: 'yí chuàn chuàn' },
    { w: '人群', py: 'rén qún' },
    { w: '欢乐', py: 'huān lè' },
    { w: '开心', py: 'kāi xīn' },
    { w: '长裤', py: 'cháng kù' },
    { w: '令人', py: 'lìng rén' },
  ],
  'u6.liu-hulan': [
    { w: '反动派', py: 'fǎn dòng pài' },
    { w: '山村', py: 'shān cūn' },
    { w: '由于', py: 'yóu yú' },
    { w: '共产党员', py: 'gòng chǎn dǎng yuán' },
    { w: '共产党', py: 'gòng chǎn dǎng' },
    { w: '大声', py: 'dà shēng' },
    { w: '被动', py: 'bèi dòng' },
    { w: '几岁', py: 'jǐ suì' },
    { w: '现在', py: 'xiàn zài' },
    { w: '一点儿', py: 'yì diǎn er' },
    { w: '消息', py: 'xiāo xi' },
  ],
  'u6.garden-6': [
    { w: '抄写', py: 'chāo xiě' },
    { w: '炒菜', py: 'chǎo cài' },
  ],
  'u7.poems': [
    { w: '绝对', py: 'jué duì' },
    { w: '破灭', py: 'pò miè' },
    { w: '孤舟', py: 'gū zhōu' },
    { w: '独自', py: 'dú zì' },
    { w: '阴山', py: 'yīn shān' },
    { w: '似的', py: 'shì de' },
    { w: '田野', py: 'tián yě' },
    { w: '高低', py: 'gāo dī' },
  ],
  'u7.fog': [
    { w: '于是', py: 'yú shì' },
    { w: '无论', py: 'wú lùn' },
    { w: '船只', py: 'chuán zhī' },
    { w: '同时', py: 'tóng shí' },
    { w: '行人', py: 'xíng rén' },
    { w: '一切', py: 'yí qiè' },
    { w: '上空', py: 'shàng kōng' },
    { w: '看来', py: 'kàn lái' },
    { w: '不久', py: 'bù jiǔ' },
    { w: '路上', py: 'lù shang' },
    { w: '出现', py: 'chū xiàn' },
    { w: '散步', py: 'sàn bù' },
    { w: '消失', py: 'xiāo shī' },
    { w: '黑猫', py: 'hēi māo' },
    { w: '应该', py: 'yīng gāi' },
  ],
  'u7.snow-child': [
    { w: '空地', py: 'kòng dì' },
    { w: '伙伴', py: 'huǒ bàn' },
    { w: '唱歌', py: 'chàng gē' },
    { w: '回家', py: 'huí jiā' },
    { w: '一会儿', py: 'yí huì er' },
    { w: '着火', py: 'zháo huǒ' },
    { w: '火星', py: 'huǒ xīng' },
    { w: '一边', py: 'yì biān' },
    { w: '连忙', py: 'lián máng' },
    { w: '树林', py: 'shù lín' },
    { w: '水汽', py: 'shuǐ qì' },
    { w: '白云', py: 'bái yún' },
    { w: '要是', py: 'yào shi' },
    { w: '关闭', py: 'guān bì' },
    { w: '谁的', py: 'shuí de' },
    { w: '得救', py: 'dé jiù' },
  ],
  'u7.garden-7': [
    { w: '饥饿', py: 'jī è' },
    { w: '车库', py: 'chē kù' },
    { w: '安宁', py: 'ān níng' },
  ],
  'u8.praise': [
    { w: '拿走', py: 'ná zǒu' },
    { w: '仔细', py: 'zǐ xì' },
    { w: '太极', py: 'tài jí' },
    { w: '送行', py: 'sòng xíng' },
    { w: '椅子', py: 'yǐ zi' },
    { w: '怎么', py: 'zěn me' },
    { w: '拉开', py: 'lā kāi' },
    { w: '接收', py: 'jiē shōu' },
    { w: '果子', py: 'guǒ zi' },
    { w: '木工', py: 'mù gōng' },
    { w: '身边', py: 'shēn biān' },
    { w: '能干', py: 'néng gàn' },
    { w: '自信', py: 'zì xìn' },
    { w: '从来', py: 'cóng lái' },
    { w: '这么', py: 'zhè me' },
  ],
  'u8.paper-boat': [
    { w: '折纸', py: 'zhé zhǐ' },
    { w: '抓住', py: 'zhuā zhù' },
    { w: '线条', py: 'xiàn tiáo' },
    { w: '吵架', py: 'chǎo jià' },
    { w: '但是', py: 'dàn shì' },
    { w: '难受', py: 'nán shòu' },
    { w: '句子', py: 'jù zi' },
    { w: '大哭', py: 'dà kū' },
    { w: '上面', py: 'shàng mian' },
    { w: '快乐', py: 'kuài lè' },
    { w: '可是', py: 'kě shì' },
    { w: '难过', py: 'nán guò' },
    { w: '和好', py: 'hé hǎo' },
  ],
  'u8.happy-river': [
    { w: '游戏', py: 'yóu xì' },
    { w: '可爱', py: 'kě ài' },
    { w: '跳高', py: 'tiào gāo' },
    { w: '咱们', py: 'zán men' },
    { w: '好呢', py: 'hǎo ne' },
    { w: '眼泪', py: 'yǎn lèi' },
    { w: '水花', py: 'shuǐ huā' },
    { w: '青草', py: 'qīng cǎo' },
    { w: '只有', py: 'zhǐ yǒu' },
    { w: '可以', py: 'kě yǐ' },
    { w: '多少', py: 'duō shǎo' },
    { w: '田野', py: 'tián yě' },
    { w: '大地', py: 'dà dì' },
    { w: '远方', py: 'yuǎn fāng' },
  ],
  'u8.garden-8': [
    { w: '狼群', py: 'láng qún' },
    { w: '蛇虫', py: 'shé chóng' },
  ],
};

/**
 * Real words a one-character homophone swap of a listed word produces with the same (or
 * almost the same) pinyin, e.g. 是的 for 似的 (shì de), 当做 for 当作: never offered as a wrong spelling.
 */
export const YW_G2A_SOUNDALIKE_WORDS: readonly string[] = [
  '是的', '当做', '水气', '细语', '战事', '可视', '出线', '一味', '水份', '视界',
  '身处', '初来', '行状', '子细', '初发', '心理', '有得', '知事', '要事', '巨子',
];
