import type { ChoiceItem } from './types';

/**
 * 语文 四年级上册（统编版 2026 修订）第一、二单元：字词。kp = 知识点 id 去掉 "yw-g4a."。
 * 每个知识点 12 题以上；level 1 基础 / 2 理解运用 / 3 易混辨析。多音字另见 yw-g4a-poly.ts。
 */
export const YW_G4A_ITEMS: ChoiceItem[] = [
  // ---------------------------------------------------------------- u1.tide
  {
    kp: 'u1.tide',
    level: 1,
    kind: '读音',
    prompt: '「潮」的读音是（　）',
    answer: 'cháo',
    wrong: [
      ['cáo', 'char-pinyin'],
      ['zhāo', 'char-pinyin'],
    ],
    explain: '潮读 cháo，是翘舌音，第二声。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '读音',
    prompt: '「堤」的读音是（　）',
    answer: 'dī',
    wrong: [
      ['dǐ', 'char-pinyin'],
      ['dì', 'char-pinyin'],
    ],
    explain: '堤读第一声 dī，大堤的堤。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '读音',
    prompt: '「山崩地裂」的「崩」读（　）',
    answer: 'bēng',
    wrong: [
      ['bēn', 'char-pinyin'],
      ['péng', 'char-pinyin'],
    ],
    explain: '崩读 bēng，是后鼻音，第一声。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '读音',
    prompt: '「霎时」的「霎」读（　）',
    answer: 'shà',
    wrong: [
      ['sà', 'char-pinyin'],
      ['shā', 'char-pinyin'],
    ],
    explain: '霎读 shà，翘舌音，第四声。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '读音',
    prompt: '「震」的读音是（　）',
    answer: 'zhèn',
    wrong: [
      ['zèn', 'char-pinyin'],
      ['zhèng', 'char-pinyin'],
    ],
    explain: '震读 zhèn，翘舌音、前鼻音，第四声。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '看拼音选字',
    prompt: 'dà dī：大（　）',
    answer: '堤',
    wrong: [
      ['提', 'similar-char'],
      ['低', 'similar-char'],
    ],
    explain: '大堤是用土筑成的，所以是土字旁的“堤”。',
  },
  {
    kp: 'u1.tide',
    level: 1,
    kind: '看拼音选字',
    prompt: 'shān bēng dì liè：山（　）地裂',
    answer: '崩',
    wrong: [
      ['蹦', 'similar-char'],
      ['绷', 'similar-char'],
    ],
    explain: '山塌下来叫崩，所以是山字头的“崩”。',
  },
  {
    kp: 'u1.tide',
    level: 2,
    kind: '同音字',
    prompt: '顿时人声鼎（　），有人告诉我们，潮来了！',
    answer: '沸',
    wrong: [
      ['费', 'similar-char'],
      ['废', 'similar-char'],
    ],
    explain: '人声鼎沸形容人声吵闹，像锅里的水烧开了一样，所以是三点水的“沸”。',
  },
  {
    kp: 'u1.tide',
    level: 2,
    kind: '同音字',
    prompt: '浪潮越来越近，（　）如千万匹白色战马齐头并进。',
    answer: '犹',
    wrong: [
      ['尤', 'similar-char'],
      ['由', 'similar-char'],
    ],
    explain: '犹如就是好像，要写反犬旁的“犹”。',
  },
  {
    kp: 'u1.tide',
    level: 2,
    kind: '形近字',
    prompt: '过了好久，钱塘江才（　）复了平静。',
    answer: '恢',
    wrong: [
      ['灰', 'similar-char'],
      ['诙', 'similar-char'],
    ],
    explain: '恢复是变回原来的样子，要写竖心旁的“恢”。',
  },
  {
    kp: 'u1.tide',
    level: 2,
    kind: '词义',
    prompt: '「天下奇观」中「奇观」的意思是（　）',
    answer: '奇特、少见的壮观景象',
    wrong: [
      ['奇怪的想法', 'word-usage'],
      ['平常的风景', 'word-usage'],
    ],
    explain: '奇观就是奇特、少见的壮观景象，钱塘江大潮自古就被称为天下奇观。',
  },
  {
    kp: 'u1.tide',
    level: 2,
    kind: '课文理解',
    prompt: '《观潮》中，一年一度的观潮日是（　）',
    answer: '农历八月十八',
    wrong: [
      ['农历八月十五', 'word-usage'],
      ['农历正月十五', 'word-usage'],
    ],
    explain: '课文里说，农历八月十八是一年一度的观潮日。八月十五是中秋节。',
  },
  {
    kp: 'u1.tide',
    level: 3,
    kind: '课文理解',
    prompt: '潮来时，浪潮的样子先后像（　）',
    answer: '一条白线、白色城墙、白色战马',
    wrong: [
      ['白色战马、白色城墙、一条白线', 'word-usage'],
      ['白色城墙、一条白线、白色战马', 'word-usage'],
    ],
    explain: '浪潮由远到近，先是一条白线，再像白色城墙，最后像千万匹白色战马。',
  },
  {
    kp: 'u1.tide',
    level: 3,
    kind: '同音字',
    prompt: '钱塘江的江面十分宽（　）。',
    answer: '阔',
    wrong: [
      ['扩', 'similar-char'],
      ['括', 'similar-char'],
    ],
    explain: '宽阔是又宽又大的意思，要写门字框的“阔”。',
  },
  {
    kp: 'u1.tide',
    level: 3,
    kind: '同音字',
    prompt: '那条白线逐渐拉长，变粗，横（　）江面。',
    answer: '贯',
    wrong: [
      ['惯', 'similar-char'],
      ['冠', 'similar-char'],
    ],
    explain: '横贯就是横着穿过整个江面，要写“贯穿”的“贯”。',
  },
  {
    kp: 'u1.tide',
    level: 3,
    kind: '近义词',
    prompt: '「犹如」的近义词是（　）',
    answer: '好像',
    wrong: [
      ['犹豫', 'word-usage'],
      ['于是', 'word-usage'],
    ],
    explain: '犹如就是好像；犹豫是拿不定主意，意思不一样。',
  },
  // ---------------------------------------------------------------- u1.modern-poems
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '课文理解',
    prompt: '《花牛歌》的作者是（　）',
    answer: '徐志摩',
    wrong: [
      ['刘大白', 'word-usage'],
      ['巴金', 'word-usage'],
    ],
    explain: '《花牛歌》是徐志摩写的，《秋晚的江上》是刘大白写的。',
  },
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '读音',
    prompt: '「瞬」的读音是（　）',
    answer: 'shùn',
    wrong: [
      ['sùn', 'char-pinyin'],
      ['shǔn', 'char-pinyin'],
    ],
    explain: '瞬读 shùn，翘舌音，第四声。',
  },
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '读音',
    prompt: '「霸占」的「霸」读（　）',
    answer: 'bà',
    wrong: [
      ['bā', 'char-pinyin'],
      ['pà', 'char-pinyin'],
    ],
    explain: '霸读 bà，第四声。',
  },
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '读音',
    prompt: '「倦」的读音是（　）',
    answer: 'juàn',
    wrong: [
      ['quàn', 'char-pinyin'],
      ['juǎn', 'char-pinyin'],
    ],
    explain: '倦读 juàn，第四声，疲倦的倦。',
  },
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '读音',
    prompt: '「归巢」的「巢」读（　）',
    answer: 'cháo',
    wrong: [
      ['cáo', 'char-pinyin'],
      ['chāo', 'char-pinyin'],
    ],
    explain: '巢读 cháo，翘舌音，第二声，鸟窝就叫巢。',
  },
  {
    kp: 'u1.modern-poems',
    level: 1,
    kind: '看拼音选字',
    prompt: 'tuó zhe xié yáng：（　）着斜阳',
    answer: '驮',
    wrong: [
      ['驼', 'similar-char'],
      ['陀', 'similar-char'],
    ],
    explain: '驮是用背来背东西，马常常驮东西，所以是马字旁的“驮”。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '词义',
    prompt: '「斜阳」的意思是（　）',
    answer: '傍晚快落山的太阳',
    wrong: [
      ['早上刚升起的太阳', 'word-usage'],
      ['中午头顶的太阳', 'word-usage'],
    ],
    explain: '斜阳就是傍晚西斜、快要落山的太阳。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '词义',
    prompt: '「花牛在草地里眠」中「眠」的意思是（　）',
    answer: '睡觉',
    wrong: [
      ['吃草', 'word-usage'],
      ['奔跑', 'word-usage'],
    ],
    explain: '眠就是睡觉，花牛在草地里睡着了。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '词义',
    prompt: '「一瞬的红颜」说明芦苇的红颜（　）',
    answer: '只有很短的时间',
    wrong: [
      ['一直都不会消失', 'word-usage'],
      ['要保持一整天', 'word-usage'],
    ],
    explain: '一瞬就是一眨眼的时间，太阳一落山，红颜就不见了。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '课文理解',
    prompt: '《秋晚的江上》中，“驮着斜阳回去”的是（　）',
    answer: '归巢的鸟儿',
    wrong: [
      ['头白的芦苇', 'word-usage'],
      ['江上的小船', 'word-usage'],
    ],
    explain: '诗里写归巢的鸟儿虽然累了，还驮着斜阳回去。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '课文理解',
    prompt: '《花牛歌》每一小节都用哪几个字开头？',
    answer: '花牛在草地里',
    wrong: [
      ['白云霸占了', 'word-usage'],
      ['花牛在山坡上', 'word-usage'],
    ],
    explain: '每一小节都用“花牛在草地里”开头，读起来像唱歌一样。',
  },
  {
    kp: 'u1.modern-poems',
    level: 2,
    kind: '同音字',
    prompt: '花牛在草地里眠，白云（　）占了半个天。',
    answer: '霸',
    wrong: [
      ['坝', 'similar-char'],
      ['罢', 'similar-char'],
    ],
    explain: '霸占是强占的意思，要写雨字头的“霸”。',
  },
  {
    kp: 'u1.modern-poems',
    level: 3,
    kind: '形近字',
    prompt: '头白的（　）苇，也妆成一瞬的红颜了。',
    answer: '芦',
    wrong: [
      ['卢', 'similar-char'],
      ['炉', 'similar-char'],
    ],
    explain: '芦苇是一种草，两个字都是草字头，所以是“芦”。',
  },
  {
    kp: 'u1.modern-poems',
    level: 3,
    kind: '课文理解',
    prompt: '下面哪篇课文的作者是刘大白？',
    answer: '《秋晚的江上》',
    wrong: [
      ['《花牛歌》', 'word-usage'],
      ['《繁星》', 'word-usage'],
    ],
    explain: '《秋晚的江上》是刘大白写的；《花牛歌》是徐志摩写的，《繁星》是巴金写的。',
  },
  // ---------------------------------------------------------------- u1.stars
  {
    kp: 'u1.stars',
    level: 1,
    kind: '词义',
    prompt: '「繁星」的「繁」意思是（　）',
    answer: '多',
    wrong: [
      ['亮', 'word-usage'],
      ['远', 'word-usage'],
    ],
    explain: '繁是多的意思，繁星就是很多很多的星星。',
  },
  {
    kp: 'u1.stars',
    level: 1,
    kind: '读音',
    prompt: '「纳凉」的「纳」读（　）',
    answer: 'nà',
    wrong: [
      ['là', 'char-pinyin'],
      ['nǎ', 'char-pinyin'],
    ],
    explain: '纳读 nà，是鼻音 n，第四声。',
  },
  {
    kp: 'u1.stars',
    level: 1,
    kind: '读音',
    prompt: '「庭」的读音是（　）',
    answer: 'tíng',
    wrong: [
      ['tǐng', 'char-pinyin'],
      ['tīng', 'char-pinyin'],
    ],
    explain: '庭读 tíng，后鼻音，第二声，庭院的庭。',
  },
  {
    kp: 'u1.stars',
    level: 1,
    kind: '读音',
    prompt: '「摇摇欲坠」的「坠」读（　）',
    answer: 'zhuì',
    wrong: [
      ['zuì', 'char-pinyin'],
      ['duì', 'char-pinyin'],
    ],
    explain: '坠读 zhuì，翘舌音，第四声，意思是掉下来。',
  },
  {
    kp: 'u1.stars',
    level: 1,
    kind: '读音',
    prompt: '「静寂」的「寂」读（　）',
    answer: 'jì',
    wrong: [
      ['jí', 'char-pinyin'],
      ['qī', 'char-pinyin'],
    ],
    explain: '寂读 jì，第四声，宝盖头。',
  },
  {
    kp: 'u1.stars',
    level: 1,
    kind: '看拼音选字',
    prompt: 'tíng yuàn：（　）院',
    answer: '庭',
    wrong: [
      ['廷', 'similar-char'],
      ['停', 'similar-char'],
    ],
    explain: '庭院就是院子，是广字头的“庭”。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '词义',
    prompt: '「静寂」的意思是（　）',
    answer: '非常安静',
    wrong: [
      ['非常热闹', 'word-usage'],
      ['非常寒冷', 'word-usage'],
    ],
    explain: '静寂就是非常安静，一点声音也没有。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '词义',
    prompt: '「摇摇欲坠」的意思是（　）',
    answer: '摇摇晃晃，好像要掉下来',
    wrong: [
      ['摇来摇去，非常稳当', 'word-usage'],
      ['已经掉到了地上', 'word-usage'],
    ],
    explain: '欲是将要，坠是掉下来，摇摇欲坠就是摇摇晃晃、好像要掉下来。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '课文理解',
    prompt: '从前在家乡，作者是在什么时候看星星的？',
    answer: '七八月的夜晚',
    wrong: [
      ['寒冷的冬夜', 'word-usage'],
      ['春天的早晨', 'word-usage'],
    ],
    explain: '课文写的是在家乡七八月的夜晚，在庭院里纳凉的时候看星星。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '课文理解',
    prompt: '如今，作者是在哪里看星星的？',
    answer: '海上的船上',
    wrong: [
      ['家乡的庭院里', 'word-usage'],
      ['南京住处的后门', 'word-usage'],
    ],
    explain: '家乡、南京是从前和三年前，如今作者在海上，每晚和繁星相对。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '同音字',
    prompt: '作者望着星天，仿（　）回到了母亲的怀里。',
    answer: '佛',
    wrong: [
      ['拂', 'similar-char'],
      ['伏', 'similar-char'],
    ],
    explain: '仿佛就是好像，要写单人旁的“佛”。',
  },
  {
    kp: 'u1.stars',
    level: 2,
    kind: '近义词',
    prompt: '「仿佛」的近义词是（　）',
    answer: '好像',
    wrong: [
      ['好看', 'word-usage'],
      ['仿照', 'word-usage'],
    ],
    explain: '仿佛就是好像；仿照是照着样子去做，意思不一样。',
  },
  {
    kp: 'u1.stars',
    level: 3,
    kind: '形近字',
    prompt: '星星半明半（　），像在对我眨眼。',
    answer: '昧',
    wrong: [
      ['味', 'similar-char'],
      ['妹', 'similar-char'],
    ],
    explain: '昧是暗的意思，和日光有关，所以是日字旁的“昧”。',
  },
  {
    kp: 'u1.stars',
    level: 3,
    kind: '看拼音选字',
    prompt: 'yíng huǒ chóng：（　）火虫',
    answer: '萤',
    wrong: [
      ['荧', 'similar-char'],
      ['莹', 'similar-char'],
    ],
    explain: '萤火虫是一种小虫子，所以下面是“虫”字的“萤”。',
  },
  {
    kp: 'u1.stars',
    level: 3,
    kind: '反义词',
    prompt: '「密密麻麻」的反义词是（　）',
    answer: '稀稀拉拉',
    wrong: [
      ['密密层层', 'word-usage'],
      ['满满当当', 'word-usage'],
    ],
    explain: '密密麻麻是又多又密，反义词是稀稀拉拉；密密层层、满满当当都是多的意思。',
  },
  // ---------------------------------------------------------------- u1.recommend-place
  {
    kp: 'u1.recommend-place',
    level: 1,
    kind: '选词填空',
    prompt: '推荐一个好地方，最重要的是写清楚（　）',
    answer: '推荐的理由',
    wrong: [
      ['出发的时间', 'word-usage'],
      ['同去的人数', 'word-usage'],
    ],
    explain: '推荐就是告诉别人为什么值得去，所以要把理由写清楚。',
  },
  {
    kp: 'u1.recommend-place',
    level: 1,
    kind: '读音',
    prompt: '「推荐」的「荐」读（　）',
    answer: 'jiàn',
    wrong: [
      ['jiǎn', 'char-pinyin'],
      ['cún', 'char-pinyin'],
    ],
    explain: '荐读 jiàn，第四声，不要读成下面“存”的音。',
  },
  {
    kp: 'u1.recommend-place',
    level: 1,
    kind: '看拼音选字',
    prompt: 'tuī jiàn：（　）荐',
    answer: '推',
    wrong: [
      ['堆', 'similar-char'],
      ['摧', 'similar-char'],
    ],
    explain: '推荐的推是提手旁，“推”和“堆”“摧”长得像，要分清。',
  },
  {
    kp: 'u1.recommend-place',
    level: 1,
    kind: '看拼音选字',
    prompt: 'tuī jiàn：推（　）',
    answer: '荐',
    wrong: [
      ['存', 'similar-char'],
      ['箭', 'similar-char'],
    ],
    explain: '推荐的荐是草字头，下面是“存”。',
  },
  {
    kp: 'u1.recommend-place',
    level: 1,
    kind: '选词填空',
    prompt: '动笔前，先想好开头、理由和结尾分别写什么，这叫列（　）',
    answer: '提纲',
    wrong: [
      ['名单', 'word-usage'],
      ['地图', 'word-usage'],
    ],
    explain: '写之前先列提纲，写起来就有条理。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '词义',
    prompt: '「推荐」的意思是（　）',
    answer: '把好的人或事物介绍给别人',
    wrong: [
      ['用力向前推', 'word-usage'],
      ['自己一个人偷偷去', 'word-usage'],
    ],
    explain: '推荐就是把好的东西介绍给别人，希望别人也喜欢。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '词义',
    prompt: '写推荐文时，要避免写成“流水账”。「流水账」在这里指（　）',
    answer: '从头到尾什么都记，没有重点',
    wrong: [
      ['写河水流动的样子', 'word-usage'],
      ['把花了多少钱算清楚', 'word-usage'],
    ],
    explain: '流水账是从出门写到回家，什么都记，推荐理由反而没写清楚。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '选词填空',
    prompt: '想推荐深圳图书馆，下面哪句理由写得最具体？',
    answer: '那里的书摆满了好几层楼，我常在儿童区一坐就是一下午',
    wrong: [
      ['那里很好', 'word-usage'],
      ['我很喜欢那里', 'word-usage'],
    ],
    explain: '写出了具体的样子和自己在那里做的事，别人读了才会想去。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '选词填空',
    prompt: '莲花山山顶视野（　），能看到大半个深圳。',
    answer: '开阔',
    wrong: [
      ['开心', 'word-usage'],
      ['开始', 'word-usage'],
    ],
    explain: '视野开阔是说能看得很远很广，和“开阔”搭配。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '选词填空',
    prompt: '推荐的理由要写得（　），别人读了才会心动。',
    answer: '具体',
    wrong: [
      ['越短越好', 'word-usage'],
      ['笼统', 'word-usage'],
    ],
    explain: '每条理由都配上具体的景物或活动，别人才会想去。',
  },
  {
    kp: 'u1.recommend-place',
    level: 2,
    kind: '选词填空',
    prompt: '站在海边，海风吹在脸上，凉凉的，特别（　）。',
    answer: '舒服',
    wrong: [
      ['着急', 'word-usage'],
      ['害怕', 'word-usage'],
    ],
    explain: '凉凉的海风吹在脸上，感觉很舒服，写出感受能让理由更打动人。',
  },
  {
    kp: 'u1.recommend-place',
    level: 3,
    kind: '课文理解',
    prompt: '选择推荐的地方时，下面哪一条不是必须的？',
    answer: '一定要是很有名的景点',
    wrong: [
      ['自己去过、很熟悉', 'word-usage'],
      ['自己真心喜欢', 'word-usage'],
      ['有特别的地方', 'word-usage'],
    ],
    explain: '推荐的地方不一定有名，小区的一个角落也可以，只要熟悉、喜欢、有特别之处。',
  },
  {
    kp: 'u1.recommend-place',
    level: 3,
    kind: '形近字',
    prompt: '结尾发出（　）请，欢迎大家也来看看。',
    answer: '邀',
    wrong: [
      ['激', 'similar-char'],
      ['缴', 'similar-char'],
    ],
    explain: '邀请的邀是走之旁，和“激”“缴”长得像，要看清。',
  },
  // ---------------------------------------------------------------- u2.peas
  {
    kp: 'u2.peas',
    level: 1,
    kind: '读音',
    prompt: '豆「荚」的「荚」读（　）',
    answer: 'jiá',
    wrong: [
      ['jiā', 'char-pinyin'],
      ['xiá', 'char-pinyin'],
    ],
    explain: '豆荚的荚读第二声 jiá。',
  },
  {
    kp: 'u2.peas',
    level: 1,
    kind: '读音',
    prompt: '「豌」的读音是（　）',
    answer: 'wān',
    wrong: [
      ['wǎn', 'char-pinyin'],
      ['yuān', 'char-pinyin'],
    ],
    explain: '豌读 wān，第一声，豌豆的豌。',
  },
  {
    kp: 'u2.peas',
    level: 1,
    kind: '读音',
    prompt: '「鸽子」的「鸽」读（　）',
    answer: 'gē',
    wrong: [
      ['gé', 'char-pinyin'],
      ['hé', 'char-pinyin'],
    ],
    explain: '鸽读 gē，第一声。',
  },
  {
    kp: 'u2.peas',
    level: 1,
    kind: '看拼音选字',
    prompt: 'wān dòu：（　）豆',
    answer: '豌',
    wrong: [
      ['碗', 'similar-char'],
      ['婉', 'similar-char'],
    ],
    explain: '豌豆是一种豆子，所以是豆字旁的“豌”。',
  },
  {
    kp: 'u2.peas',
    level: 1,
    kind: '看拼音选字',
    prompt: 'qīng tái：青（　）',
    answer: '苔',
    wrong: [
      ['台', 'similar-char'],
      ['抬', 'similar-char'],
    ],
    explain: '青苔是一种小植物，所以是草字头的“苔”。',
  },
  {
    kp: 'u2.peas',
    level: 1,
    kind: '课文理解',
    prompt: '《一个豆荚里的五粒豆》的作者安徒生是哪个国家的作家？',
    answer: '丹麦',
    wrong: [
      ['中国', 'word-usage'],
      ['英国', 'word-usage'],
    ],
    explain: '安徒生是丹麦作家，写过很多有名的童话。',
  },
  {
    kp: 'u2.peas',
    level: 2,
    kind: '课文理解',
    prompt: '豆荚和豆子都是绿的，所以一开始五粒豆以为整个世界都是（　）',
    answer: '绿的',
    wrong: [
      ['黄的', 'word-usage'],
      ['蓝的', 'word-usage'],
    ],
    explain: '豆荚是绿的，豌豆也是绿的，所以它们以为整个世界都是绿的。',
  },
  {
    kp: 'u2.peas',
    level: 2,
    kind: '课文理解',
    prompt: '豆荚变黄以后，是谁把五粒豆一粒一粒射了出去？',
    answer: '一个孩子',
    wrong: [
      ['生病的小女孩', 'word-usage'],
      ['一只鸽子', 'word-usage'],
    ],
    explain: '一个孩子把豌豆一粒一粒地射了出去。',
  },
  {
    kp: 'u2.peas',
    level: 2,
    kind: '课文理解',
    prompt: '豌豆苗开出了花，生病的小女孩后来怎么样了？',
    answer: '病一天天好起来了',
    wrong: [
      ['搬到别的地方去了', 'word-usage'],
      ['把豌豆苗拔掉了', 'word-usage'],
    ],
    explain: '豌豆苗给小女孩带来了希望，她的病一天天好起来了。',
  },
  {
    kp: 'u2.peas',
    level: 2,
    kind: '词义',
    prompt: '「青苔」的意思是（　）',
    answer: '长在潮湿地方的绿色小植物',
    wrong: [
      ['青色的石头', 'word-usage'],
      ['一种小鸟', 'word-usage'],
    ],
    explain: '青苔是长在潮湿地方的绿色小植物，最后一粒豆就落在长满青苔的裂缝里。',
  },
  {
    kp: 'u2.peas',
    level: 3,
    kind: '选词填空',
    prompt: '“这个故事想告诉我们什么？”这个问题是针对（　）提出的。',
    answer: '全文',
    wrong: [
      ['一个词语', 'word-usage'],
      ['一句话', 'word-usage'],
    ],
    explain: '要读完整篇课文才能回答，所以是针对全文的问题。',
  },
  {
    kp: 'u2.peas',
    level: 3,
    kind: '形近字',
    prompt: '一个豆（　）里的五粒豆',
    answer: '荚',
    wrong: [
      ['英', 'similar-char'],
      ['莱', 'similar-char'],
    ],
    explain: '豆荚是包着豆子的外壳，草字头下面是“夹”；英、莱长得像，但意思不同。',
  },
  {
    kp: 'u2.peas',
    level: 3,
    kind: '形近字',
    prompt: '最后一粒豆落进了长满青苔的裂（　）里。',
    answer: '缝',
    wrong: [
      ['峰', 'similar-char'],
      ['蜂', 'similar-char'],
    ],
    explain: '裂缝是裂开的缝隙，和线有关，所以是绞丝旁的“缝”。',
  },
  // ---------------------------------------------------------------- u2.night-flight
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '形近字',
    prompt: '（　）蝠在夜里飞行。',
    answer: '蝙',
    wrong: [
      ['编', 'similar-char'],
      ['偏', 'similar-char'],
    ],
    explain: '蝙蝠是一种动物，所以是虫字旁的“蝙”。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '读音',
    prompt: '「蝙蝠」的「蝠」读（　）',
    answer: 'fú',
    wrong: [
      ['fù', 'char-pinyin'],
      ['fǔ', 'char-pinyin'],
    ],
    explain: '蝠读 fú，第二声，蝙蝠读 biān fú。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '读音',
    prompt: '「障」的读音是（　）',
    answer: 'zhàng',
    wrong: [
      ['zàng', 'char-pinyin'],
      ['zhàn', 'char-pinyin'],
    ],
    explain: '障读 zhàng，翘舌音、后鼻音，第四声。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '读音',
    prompt: '「障碍物」的「碍」读（　）',
    answer: 'ài',
    wrong: [
      ['dé', 'char-pinyin'],
      ['ǎi', 'char-pinyin'],
    ],
    explain: '碍读 ài，第四声，不要读成右边像“得”的音。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '读音',
    prompt: '「荧光屏」的「荧」读（　）',
    answer: 'yíng',
    wrong: [
      ['yín', 'char-pinyin'],
      ['yǐng', 'char-pinyin'],
    ],
    explain: '荧读 yíng，后鼻音，第二声。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '看拼音选字',
    prompt: 'líng dang：（　）铛',
    answer: '铃',
    wrong: [
      ['玲', 'similar-char'],
      ['伶', 'similar-char'],
    ],
    explain: '铃铛是金属做的，所以是金字旁的“铃”。',
  },
  {
    kp: 'u2.night-flight',
    level: 1,
    kind: '看拼音选字',
    prompt: 'léi dá：雷（　）',
    answer: '达',
    wrong: [
      ['这', 'similar-char'],
      ['答', 'similar-char'],
    ],
    explain: '雷达的达是走之旁，里面是“大”。',
  },
  {
    kp: 'u2.night-flight',
    level: 2,
    kind: '词义',
    prompt: '「障碍物」的意思是（　）',
    answer: '挡在前面、妨碍通行的东西',
    wrong: [
      ['飞机上的一种仪器', 'word-usage'],
      ['能发出响声的东西', 'word-usage'],
    ],
    explain: '障碍物就是挡在前面、妨碍通行的东西。',
  },
  {
    kp: 'u2.night-flight',
    level: 2,
    kind: '课文理解',
    prompt: '科学家在屋子里拉的绳子上系着许多（　）',
    answer: '铃铛',
    wrong: [
      ['灯泡', 'word-usage'],
      ['镜子', 'word-usage'],
    ],
    explain: '绳子上系着铃铛，蝙蝠一碰到绳子，铃铛就会响。',
  },
  {
    kp: 'u2.night-flight',
    level: 2,
    kind: '课文理解',
    prompt: '飞机上的雷达把反射回来的无线电波显示在（　）上。',
    answer: '荧光屏',
    wrong: [
      ['天线', 'word-usage'],
      ['铃铛', 'word-usage'],
    ],
    explain: '天线发出无线电波，反射回来后显示在荧光屏上，驾驶员一看就知道前面有没有障碍物。',
  },
  {
    kp: 'u2.night-flight',
    level: 2,
    kind: '词义',
    prompt: '课文中的「超声波」是一种（　）',
    answer: '人的耳朵听不见的声音',
    wrong: [
      ['很亮的光', 'word-usage'],
      ['人人都听得见的声音', 'word-usage'],
    ],
    explain: '蝙蝠从嘴里发出超声波，这种声音人的耳朵是听不见的。',
  },
  {
    kp: 'u2.night-flight',
    level: 2,
    kind: '同音字',
    prompt: '科学家经过反复研究，终于（　）开了蝙蝠夜间飞行的秘密。',
    answer: '揭',
    wrong: [
      ['接', 'similar-char'],
      ['街', 'similar-char'],
    ],
    explain: '揭开就是把盖着的东西掀开，要写提手旁的“揭”。',
  },
  {
    kp: 'u2.night-flight',
    level: 3,
    kind: '形近字',
    prompt: '驾（　）员从荧光屏上看到前面有没有障碍物。',
    answer: '驶',
    wrong: [
      ['使', 'similar-char'],
      ['史', 'similar-char'],
    ],
    explain: '驾驶和开车、骑马有关，所以是马字旁的“驶”。',
  },
  {
    kp: 'u2.night-flight',
    level: 3,
    kind: '同音字',
    prompt: '障（　）物',
    answer: '碍',
    wrong: [
      ['爱', 'similar-char'],
      ['艾', 'similar-char'],
    ],
    explain: '障碍物挡住去路，像拦路的石头，所以是石字旁的“碍”；爱、艾读音相同，意思不同。',
  },
  {
    kp: 'u2.night-flight',
    level: 3,
    kind: '课文理解',
    prompt: '三次试验说明，蝙蝠在夜里飞行是靠（　）配合起来探路的。',
    answer: '嘴和耳朵',
    wrong: [
      ['眼睛和耳朵', 'word-usage'],
      ['眼睛和嘴', 'word-usage'],
    ],
    explain: '蒙上眼睛照样飞，塞住耳朵或封住嘴就乱撞，说明靠的是嘴和耳朵。',
  },
  // ---------------------------------------------------------------- u2.square-hats
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '词义',
    prompt: '「古董」在课文里比喻（　）',
    answer: '过时的东西',
    wrong: [
      ['很贵的新东西', 'word-usage'],
      ['古代的人', 'word-usage'],
    ],
    explain: '古董本来指古代留下来的器物，这里比喻已经过时、没人要的东西。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '读音',
    prompt: '「古董」的「董」读（　）',
    answer: 'dǒng',
    wrong: [
      ['dòng', 'char-pinyin'],
      ['děng', 'char-pinyin'],
    ],
    explain: '董读 dǒng，第三声。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '读音',
    prompt: '「帽」的读音是（　）',
    answer: 'mào',
    wrong: [
      ['mò', 'char-pinyin'],
      ['mǎo', 'char-pinyin'],
    ],
    explain: '帽读 mào，第四声。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '读音',
    prompt: '「舒」的读音是（　）',
    answer: 'shū',
    wrong: [
      ['sū', 'char-pinyin'],
      ['shǔ', 'char-pinyin'],
    ],
    explain: '舒读 shū，翘舌音，第一声。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '看拼音选字',
    prompt: 'shì yàng：（　）样',
    answer: '式',
    wrong: [
      ['试', 'similar-char'],
      ['示', 'similar-char'],
    ],
    explain: '式样就是样子，写“方式”的“式”。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '看拼音选字',
    prompt: 'shū fu：（　）服',
    answer: '舒',
    wrong: [
      ['书', 'similar-char'],
      ['抒', 'similar-char'],
    ],
    explain: '舒服的舒，左边是“舍”，右边是“予”。',
  },
  {
    kp: 'u2.square-hats',
    level: 1,
    kind: '反义词',
    prompt: '「方帽子」的「方」，反义词是（　）',
    answer: '圆',
    wrong: [
      ['扁', 'word-usage'],
      ['长', 'word-usage'],
    ],
    explain: '方和圆是一对反义词，故事里就有方帽子和圆帽子。',
  },
  {
    kp: 'u2.square-hats',
    level: 2,
    kind: '词义',
    prompt: '「式样」的意思是（　）',
    answer: '东西的样子',
    wrong: [
      ['考试的题目', 'word-usage'],
      ['开会的仪式', 'word-usage'],
    ],
    explain: '式就是样子，式样就是东西做成的样子。',
  },
  {
    kp: 'u2.square-hats',
    level: 3,
    kind: '近义词',
    prompt: '「舒服」的近义词是（　）',
    answer: '舒适',
    wrong: [
      ['服装', 'word-usage'],
      ['难受', 'word-usage'],
    ],
    explain: '舒服和舒适意思相近；难受是舒服的反义词。',
  },
  {
    kp: 'u2.square-hats',
    level: 2,
    kind: '反义词',
    prompt: '「舒服」的反义词是（　）',
    answer: '难受',
    wrong: [
      ['舒适', 'word-usage'],
      ['高兴', 'word-usage'],
    ],
    explain: '舒服的反义词是难受，舒适是它的近义词。',
  },
  {
    kp: 'u2.square-hats',
    level: 2,
    kind: '课文理解',
    prompt: '方帽子戴在头上为什么不舒服？',
    answer: '人的头是圆的',
    wrong: [
      ['方帽子是用石头做的', 'word-usage'],
      ['天气太热了', 'word-usage'],
    ],
    explain: '人的头是圆的，方帽子戴在头上当然不舒服。',
  },
  {
    kp: 'u2.square-hats',
    level: 2,
    kind: '选词填空',
    prompt: '《方帽子店》告诉我们，做事不能（　），要敢于改变和创新。',
    answer: '一成不变',
    wrong: [
      ['敢于创新', 'word-usage'],
      ['想新办法', 'word-usage'],
    ],
    explain: '方帽子店一成不变，最后被淘汰了；要敢于改变和创新。',
  },
  {
    kp: 'u2.square-hats',
    level: 2,
    kind: '同音字',
    prompt: '他戴上一顶新（　）子，高高兴兴地出门了。',
    answer: '帽',
    wrong: [
      ['冒', 'similar-char'],
      ['茂', 'similar-char'],
    ],
    explain: '帽子是戴在头上的，和布、巾有关，所以是巾字旁的“帽”。',
  },
  {
    kp: 'u2.square-hats',
    level: 3,
    kind: '形近字',
    prompt: '读完故事，我明白了，也读（　）了其中的道理。',
    answer: '懂',
    wrong: [
      ['董', 'similar-char'],
      ['憧', 'similar-char'],
    ],
    explain: '懂是明白的意思，和心有关，所以是竖心旁；古董的董是草字头。',
  },
  {
    kp: 'u2.square-hats',
    level: 3,
    kind: '选词填空',
    prompt: '陈旧、不好用的东西，总会被新的、更好的东西（　）。',
    answer: '代替',
    wrong: [
      ['代表', 'word-usage'],
      ['带领', 'word-usage'],
    ],
    explain: '代替就是换掉原来的，方帽子就被舒服的圆帽子代替了。',
  },
  // ---------------------------------------------------------------- u2.horse-race
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '读音',
    prompt: '田「忌」赛马的「忌」读（　）',
    answer: 'jì',
    wrong: [
      ['jí', 'char-pinyin'],
      ['jǐ', 'char-pinyin'],
    ],
    explain: '忌读第四声 jì。',
  },
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '读音',
    prompt: '「赛」的读音是（　）',
    answer: 'sài',
    wrong: [
      ['shài', 'char-pinyin'],
      ['sāi', 'char-pinyin'],
    ],
    explain: '赛读 sài，平舌音，第四声。',
  },
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '读音',
    prompt: '齐「威」王的「威」读（　）',
    answer: 'wēi',
    wrong: [
      ['wěi', 'char-pinyin'],
      ['wéi', 'char-pinyin'],
    ],
    explain: '威读 wēi，第一声，威风的威。',
  },
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '看拼音选字',
    prompt: 'sài mǎ：（　）马',
    answer: '赛',
    wrong: [
      ['寒', 'similar-char'],
      ['塞', 'similar-char'],
    ],
    explain: '赛马的赛最下面是“贝”，不要和“寒”“塞”写混了。',
  },
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '看拼音选字',
    prompt: 'sūn bìn：孙（　）',
    answer: '膑',
    wrong: [
      ['宾', 'similar-char'],
      ['滨', 'similar-char'],
    ],
    explain: '孙膑的膑是月字旁。',
  },
  {
    kp: 'u2.horse-race',
    level: 1,
    kind: '看拼音选字',
    prompt: 'tián jì：田（　）',
    answer: '忌',
    wrong: [
      ['记', 'similar-char'],
      ['己', 'similar-char'],
    ],
    explain: '田忌的忌，上面是“己”，下面是“心”。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '课文理解',
    prompt: '第一次比赛，田忌的结果是（　）',
    answer: '三场全输',
    wrong: [
      ['两胜一负', 'word-usage'],
      ['三场全胜', 'word-usage'],
    ],
    explain: '每个等级田忌的马都比齐威王的差一点，所以三场全输了。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '课文理解',
    prompt: '赛马时，双方的马分成了（　）',
    answer: '上、中、下三等',
    wrong: [
      ['大、小两等', 'word-usage'],
      ['一、二、三、四四等', 'word-usage'],
    ],
    explain: '双方的马都分成上等马、中等马、下等马三等。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '词义',
    prompt: '「扬长避短」的意思是（　）',
    answer: '发挥长处，避开短处',
    wrong: [
      ['只看别人的长处', 'word-usage'],
      ['把长的马留下，短的马赶走', 'word-usage'],
    ],
    explain: '扬是发挥，避是避开，扬长避短就是发挥自己的长处，避开自己的短处。',
  },
  {
    kp: 'u2.horse-race',
    level: 3,
    kind: '选词填空',
    prompt: '孙膑心里早就想好了办法，显得（　）。',
    answer: '胸有成竹',
    wrong: [
      ['垂头丧气', 'word-usage'],
      ['目瞪口呆', 'word-usage'],
    ],
    explain: '胸有成竹是说做事之前心里早有了主意，正好形容孙膑。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '选词填空',
    prompt: '比赛输了，他（　）地走出了赛马场。',
    answer: '垂头丧气',
    wrong: [
      ['得意洋洋', 'word-usage'],
      ['胸有成竹', 'word-usage'],
    ],
    explain: '垂头丧气是低着头、很失望的样子，输了比赛才会这样。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '选词填空',
    prompt: '马没有换，只调换了出场顺序，田忌就（　）了。',
    answer: '转败为胜',
    wrong: [
      ['一败涂地', 'word-usage'],
      ['半途而废', 'word-usage'],
    ],
    explain: '第一次输，第二次赢，这就叫转败为胜。',
  },
  {
    kp: 'u2.horse-race',
    level: 2,
    kind: '同音字',
    prompt: '田忌常常和齐国的国君齐（　）王赛马。',
    answer: '威',
    wrong: [
      ['危', 'similar-char'],
      ['微', 'similar-char'],
    ],
    explain: '齐威王的威是威风的威，和危险的“危”、微小的“微”读音相同。',
  },
  {
    kp: 'u2.horse-race',
    level: 3,
    kind: '课文理解',
    prompt: '第二次比赛，田忌用（　）对齐威王的下等马。',
    answer: '中等马',
    wrong: [
      ['下等马', 'word-usage'],
      ['上等马', 'word-usage'],
    ],
    explain: '第二次：下等马对上等马，上等马对中等马，中等马对下等马。',
  },
  {
    kp: 'u2.horse-race',
    level: 3,
    kind: '形近字',
    prompt: '孙膑善于观察、分（　），想出了好办法。',
    answer: '析',
    wrong: [
      ['折', 'similar-char'],
      ['拆', 'similar-char'],
    ],
    explain: '分析的析是木字旁，右边是“斤”，不要写成提手旁的“折”“拆”。',
  },
  // ---------------------------------------------------------------- u2.my-family
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '选词填空',
    prompt: '写家人时，要抓住人物的（　）来写。',
    answer: '特点',
    wrong: [
      ['缺点', 'word-usage'],
      ['年龄', 'word-usage'],
    ],
    explain: '抓住特点，别人读了才知道你写的是谁。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '选词填空',
    prompt: '找家人的特点，可以从外貌、性格和（　）几个方面去想。',
    answer: '爱好',
    wrong: [
      ['名字', 'word-usage'],
      ['门牌号', 'word-usage'],
    ],
    explain: '外貌、性格、爱好都能看出一个人的特点。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '量词',
    prompt: '妈妈勤劳得像一（　）忙碌的小蜜蜂。',
    answer: '只',
    wrong: [
      ['条', 'word-usage'],
      ['棵', 'word-usage'],
    ],
    explain: '小蜜蜂是小动物，用“一只”。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '看拼音选字',
    prompt: 'láo dao：唠（　）',
    answer: '叨',
    wrong: [
      ['叼', 'similar-char'],
      ['叮', 'similar-char'],
    ],
    explain: '唠叨的叨，右边是“刀”；叼、叮长得像，要看清。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '看拼音选字',
    prompt: 'qín láo：（　）劳',
    answer: '勤',
    wrong: [
      ['芹', 'similar-char'],
      ['琴', 'similar-char'],
    ],
    explain: '勤劳的勤，右边是“力”，干活要出力。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '反义词',
    prompt: '「急性子」的反义词是（　）',
    answer: '慢性子',
    wrong: [
      ['急脾气', 'word-usage'],
      ['大个子', 'word-usage'],
    ],
    explain: '急和慢相反，急性子的反义词是慢性子。',
  },
  {
    kp: 'u2.my-family',
    level: 1,
    kind: '选词填空',
    prompt: '习作的结尾，要写出自己对家人的（　）。',
    answer: '感情',
    wrong: [
      ['年龄', 'word-usage'],
      ['地址', 'word-usage'],
    ],
    explain: '结尾写出你对家人的感情，文章才温暖。',
  },
  {
    kp: 'u2.my-family',
    level: 2,
    kind: '选词填空',
    prompt: '想表现妈妈很细心，最合适的事例是（　）',
    answer: '出门前，妈妈把我的水壶、雨伞一样一样检查好',
    wrong: [
      ['妈妈唱歌很好听', 'word-usage'],
      ['妈妈的个子很高', 'word-usage'],
    ],
    explain: '事例要和特点相配，一样一样检查东西才能说明细心。',
  },
  {
    kp: 'u2.my-family',
    level: 2,
    kind: '选词填空',
    prompt: '爷爷最爱下棋，这写的是他的（　）。',
    answer: '爱好',
    wrong: [
      ['外貌', 'word-usage'],
      ['年龄', 'word-usage'],
    ],
    explain: '喜欢做的事叫爱好，下棋就是爷爷的爱好。',
  },
  {
    kp: 'u2.my-family',
    level: 2,
    kind: '近义词',
    prompt: '「叮嘱」的近义词是（　）',
    answer: '嘱咐',
    wrong: [
      ['叮咚', 'word-usage'],
      ['称赞', 'word-usage'],
    ],
    explain: '叮嘱和嘱咐都是再三告诉、让人记住的意思。',
  },
  {
    kp: 'u2.my-family',
    level: 2,
    kind: '词义',
    prompt: '「妈妈有点爱唠叨」中「唠叨」的意思是（　）',
    answer: '说起来没完没了',
    wrong: [
      ['说话声音很小', 'word-usage'],
      ['很少说话', 'word-usage'],
    ],
    explain: '唠叨就是说起来没完没了，一件事说好几遍。',
  },
  {
    kp: 'u2.my-family',
    level: 3,
    kind: '词义',
    prompt: '做事、说话总是很着急，一刻也等不了的人，我们常说他是（　）',
    answer: '急性子',
    wrong: [
      ['慢性子', 'word-usage'],
      ['热心肠', 'word-usage'],
    ],
    explain: '急性子的人做事着急，等不了；慢性子正好相反。',
  },
  {
    kp: 'u2.my-family',
    level: 3,
    kind: '同音字',
    prompt: '爸爸是个运动（　），下雨天也要出门跑步。',
    answer: '迷',
    wrong: [
      ['谜', 'similar-char'],
      ['米', 'similar-char'],
    ],
    explain: '运动迷是特别喜欢运动的人，要写走之旁的“迷”；谜是谜语的谜。',
  },
  {
    kp: 'u2.my-family',
    level: 3,
    kind: '选词填空',
    prompt: '下面哪一句用具体的事写出了爷爷“爱看书”？',
    answer: '爷爷戴上老花镜，一看书就是一上午',
    wrong: [
      ['爷爷很爱看书', 'word-usage'],
      ['爷爷的个子很高', 'word-usage'],
    ],
    explain: '第一句写了爷爷具体做的事；只写“很爱看书”不够具体。',
  },
];
